### ISSUE TITLE
Upgrade to 3.3.0 - Performance issue 

### ISSUE THREAD

**Issue by flowdopip** [Kong/kong#11080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

After upgrading from 3.2.2 to 3.3.0 and activating open telemetry with a 0.25 sampling rate this behaviour seams to happen with some recurrence

![image](https://github.com/Kong/kong/assets/5880313/13d9b5b3-7760-4cd9-a991-1614f7e3318e)

### Expected Behavior

With a rollback to 3.2.2, the behaviour disappears,

### Steps To Reproduce

only changing the version of kong. The config of open telemetry is the same for both versions but on 3.2.2 the OTEL does not work since there´s a but that not allow 0.25% of sampling
- kong 3.3.0
- DB-Less

prefix = /apps/loadbalancer-external-apigateway/current/
lua_package_path = /apps/loadbalancer-external-apigateway/current/conf/bin/?.lua;;
admin_access_log = off
admin_error_log = off
status_error_log = off
status_access_log = off
proxy_access_log = /apps/loadbalancer-external-apigateway/current/logs/access/access.log
proxy_error_log = /apps/loadbalancer-external-apigateway/current/logs/error/error.log
declarative_config = conf/kong.yml
log_level = error
anonymous_reports = off
proxy_listen = 0.0.0.0:9101 ssl reuseport backlog=16384
port_maps = 443:9101
nginx_daemon = off
nginx_http_tcp_nodelay = on
nginx_http_keepalive_requests = 3000000
nginx_http_keepalive_timeout = 300
nginx_http_include = /apps/loadbalancer-external-apigateway/current/conf/nginx/monitoring.conf
nginx_http_ssl_protocols = TLSv1.2
nginx_http_ssl_prefer_server_ciphers = on
nginx_http_charset = UTF-8
ssl_cipher_suite = custom
ssl_ciphers = ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
ssl_cert = /apps/loadbalancer-external-apigateway/current/certs/wildcard_xxxx_net.crt
ssl_cert_key = /apps/loadbalancer-external-apigateway/current/certs/wildcard_xxxx_net.key
mem_cache_size = 4096m
db_cache_ttl = 0
database = off
plugins = prometheus, jwt, jwt-validation, jwt-claims-to-path-prefix, response-transformer, request-termination, opentelemetry
headers = off
error_default_type = application/json
dns_stale_ttl = 60
dns_cache_size = 15000
dns_order = LAST,A,CNAME,SRV
dns_valid_ttl = 300
ssl_session_cache_size = 10m
allow_debug_header = false
tracing_instrumentations = all
tracing_sampling_rate = 0.25

The release of upgrade was on 06/05

**Comment by bungle** [comment]
@hanshuebner, do you have an idea why this might be happening? Is opentelemetry plugin also configured through kong.conf? I do not know this code too well.

**Comment by flowdopip** [comment]
yes OTEL is on kong.conf 
tracing_instrumentations = all
tracing_sampling_rate = 0.25

and on kong.yml as a global plugin

**Comment by flowdopip** [comment]
After a deploy that disable the OTEL for all requests






tracing_instrumentations = off
tracing_sampling_rate = 0

![image](https://github.com/Kong/kong/assets/5880313/c242f605-0692-4124-9162-e4a5e7401fba)

**Comment by flowdopip** [comment]
Activated the OTEL again but this time with request instrumentation only? 

tracing_instrumentations = request
tracing_sampling_rate = 0.25

**Comment by hanshuebner** [comment]
@flowdopip You write "Performance issue" and "this behavior", but you don't describe what exactly the problem is, what your expectations are or how previous versions of Kong Gateway behaved.  Is your concern the large amount of memory that is consumed when you enable OpenTelemetry and a large number of telemetry records is being generated?

**Comment by flowdopip** [comment]
Hi,

Sorry for the low information about the issue.
Yes, the main problem is memory consumption, and because of that, we saw the nginx pids being released ( gracefully ), a low increase of CPU and an overall p99 latency increase.

This started with the new OTEL Plugin since we previously used Zipking Plugin.
After further iteration, we reduced the payload of tracing events from "all" to "request", and we saw a normalization of CPU and Memory.

Now we are working on the OTEL Plugin settings to understand the reason for the memory increase. https://docs.konghq.com/hub/kong-inc/opentelemetry/configuration/

**Comment by samugi** [comment]
@flowdopip since changing [tracing_instrumentations](https://docs.konghq.com/gateway/latest/reference/configuration/#tracing_instrumentations) from `all` to `request` produced a "normalization" of CPU and memory utilization, as a next step I would advise testing all the other configuration options listed in our docs, one by one, and monitor resources utilization to see which parameter is producing a spike. Depending on the entity of memory utilization increase, this could be expected. It would also help if you could provide more accurate measurements of the worker's memory utilization that you are considering too high, compared to what you are describing as normal.
