### ISSUE TITLE
Multiple ingress routes with different files not working in kong 2.10.0 on eks

### ISSUE THREAD

**Issue by prashanthkumar122** [Kong/kong#11329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.10.0 latest

### Current Behavior

We are getting below error while applying multiple ingress routes files..

failed posting new config to /config: got status code 400" subsystem=dataplane-synchronizer
time="2023-07-29T19:05:53Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: failed posting new config to /config: got status code 400" subsystem=dataplane-synchronizer
time="2023-07-29T19:05:56Z" level=error msg="could not update kong admin" error="performing update for https://localhost:8444 failed: failed posting new config to /config: got status code 400" subsystem=dataplane-synchronizer
time="2023-07-29T19:05:59Z" level=error msg="could not update kong admin" error="performing update for 

Working fine for only http protocols, if we apply grpc and tcp, it is not creating address for newly created ingress rules...

### Expected Behavior

It should create and show  'ADDRESS' for all the ingress created

### Steps To Reproduce

create multiple ingress files with different hostnames mapped to aws nlb svc.

Only the first created ingress will get the address, which are created after that are not getting the address...

**Comment by guanlan** [comment]
@prashanthkumar122 
2.10.0 has not existed, can you confirm this on the lastest version?

**Comment by prashanthkumar122** [comment]
@guanlan this is the one i was mentioning

https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/#:~:text=Kubernetes%20Ingress%20Controller%20recognizes%20the%20kong%20IngressClass%20and,environment%20variable%20to%20another%20value%20overrides%20these%20defaults.

**Comment by samugi** [comment]
@prashanthkumar122 that is the version of KIC (Kubernetes Ingress Controller), confirming your version of Kong Gateway and adding more details of the logs returned by it would help, thanks.

**Comment by prashanthkumar122** [comment]
HI @samugi,

We have issue in Kubernetes Ingress Controller?? what can be done here ??

**Comment by samugi** [comment]
> We have issue in Kubernetes Ingress Controller?

Possibly. Based on the details provided we can only see that the gateway is responding with a 400 status code when the configuration is reloaded.

> what can be done here?

The gateway logs may contain useful information to troubleshoot this. Knowing the version of the gateway may also help. As per my previous comment I would recommend checking and investigating those; if you need assistance with that feel free to update this issue's description with such details. If the problem turns out to be affecting KIC it would be best to open an issue in the https://github.com/Kong/kubernetes-ingress-controller repository. I also found [a similar issue there](https://github.com/Kong/kubernetes-ingress-controller/issues/4177) but it doesn't look like a duplicate.
