### ISSUE TITLE
I cannot forward request to webdav server

### ISSUE THREAD

**Issue by HaoweiCh** [Kong/kong#11619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.3.0

### Current Behavior

I cannot forward request to webdav server

### Expected Behavior

I can connect to webdav server

**Comment by chobits** [comment]
hi, you need to provide more details about this issue, otherwise other developers or kong fans could not help you.

> I cannot forward request to webdav server

Especially whats the details of your problem, we could not get useful info from this problem description.

And dont skip "steps to reproduce", please give us a minimal reproducible set. TY
