### ISSUE TITLE
Seeing continuous "Connection reset by peer"

### ISSUE THREAD

**Issue by sunny-deo-incontact** [Kong/kong#11785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.8.1

### Current Behavior

We are getting continuous "[info] 1125#0: *16257317 recv() failed (104: Connection reset by peer) while sending to client," in our logs. 
What is the impact of this and how to mitigate this?

### Expected Behavior

No connection reset error should be there.

### Steps To Reproduce

Kong 2.8.1 deployed through docker

Upstream related configurations in Kong.conf are as below:

upstream_keepalive_max_requests = 2000
upstream_keepalive_idle_timeout = 60 
nginx_upstream_keepalive = 600000
nginx_upstream_keepalive_requests = 100000
upstream_keepalive_pool_size = 10000 

### Anything else?

<html>
<body>

```
2023/10/18 16:23:28 [info] 1125#0: *16257317 recv() failed (104: Connection reset by peer) while sending to client, client: 172.20.00.01, server: kong, request: "POST chats/ HTTP/1.1", upstream: "http://100.100.100.100:80/chats", host: "xyz.com:8443", referrer: "https://home.com/"
```
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by chobits** [comment]
This message tells you that the client, or maybe something in between (like a middleman or proxy), abruptly closed the connection with your server. This often happens before your server received all the data. This message is marked as `info`, which means it's not usually a severe problem for your server and client. In a production setting, you can set the log level to "warn" or "error" to reduce the number of these "info" level logs, which are mainly for debugging specific issues.

If you have a significant number of such messages to the point where your error log is overwhelmed, you should consider investigating whether it's due to malicious attacks, network anomalies, or client issues.
