### ISSUE TITLE
request-transformer plugin missing parameters when client request body is larger than client_body_buffer_size

### ISSUE THREAD

**Issue by kanbo** [Kong/kong#11840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.2.2

### Current Behavior

When I upload a file ,Trigger Kong to write temporary file, upstream can only receive request-transformer body,  not receive the file data
kong error.log:
2023/10/25 16:15:49 [warn] 125097#0: *5859 a client request body is buffered to a temporary file /apps/svr/kong/client_body_temp/0000000122,

### Steps To Reproduce

1、kong 3.2.2 ,dbless mode
2、kong_customer.yml
- name: test-sit
  host: test-sit
  connect_timeout: 10000
  protocol: http
  routes:
  - strip_path: false
    preserve_host: true
    name: test-sit
    hosts:
    - test.com
    methods:
    - GET
    - POST
    paths:
    - /
    plugins:
    - name: request-transformer
      config:
        add:
          body:
          - sysFlag:test
3、upload a file , the file size larger than client_body_buffer_size，kong write temporary file ,upstream only receive body sysFlag:test

**Comment by samugi** [comment]
@kanbo thank you for opening this issue. I believe this to be a duplicate of: https://github.com/Kong/kong/issues/10584

The behavior you are observing should be expected, in the logs you should find the following warning:
> request body did not fit into client body buffer, consider raising 'client_body_buffer_size'

can you confirm?

At this time, in order for the `request-transformer` plugin to successfully apply body transformations it is required that the whole body fits in the memory buffer. If the current size of [client_body_buffer_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size) is not enough for the body to fit, you can [adjust its value](https://docs.konghq.com/gateway/latest/reference/configuration/#nginx_http_client_body_buffer_size) in order to ensure the body transformation is applied correctly.
