### ISSUE TITLE
Allow selection of schema for Postgres datastore

### ISSUE THREAD

**Issue by jusw85** [Kong/kong#1193]
Postgres datastore uses 'public' schema implicitly.
Allow configuration to select the schema used.

Implementation wise, probably prefix all SQL/DDL statements with
`SET LOCAL search_path TO <schema_name>;`

**Comment by thefosk** [comment]
By closing #1198 Kong will now uses the default `search_path` whose value is `'"$user", public' ` (http://www.postgresql.org/docs/9.1/static/runtime-config-client.html).

An additional update on the Postgres client is required to make this value configurable. Assigning this to @thibaultCha since he built the Postgres driver.

**Comment by bungle** [comment]
Schema can be selected:
https://github.com/Kong/kong/pull/4167

So closing this.
