### ISSUE TITLE
Error: headers_upstream: invalid entry 'x-kong-request-id'

### ISSUE THREAD

**Issue by theMiddleBlue** [Kong/kong#12153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.5.0

### Current Behavior

upgrading from 3.4 to 3.5.0, I'm not able to run kong anymore with the same configuration file:
```
# kong start --vv
Error: 
/usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:23: headers_upstream: invalid entry 'x-kong-request-id'
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:23: in function 'load_conf'
        /usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:85: in function </usr/local/share/lua/5.1/kong/cmd/utils/inject_confs.lua:84>
        [C]: in function 'xpcall'
        /usr/local/bin/kong:99: in function 'file_gen'
        init_worker_by_lua(nginx.conf:122):47: in function <init_worker_by_lua(nginx.conf:122):45>
        [C]: in function 'xpcall'
        init_worker_by_lua(nginx.conf:122):54: in function <init_worker_by_lua(nginx.conf:122):52>
```

**Comment by ADD-SP** [comment]
@samugi @chobits Could you please take a look?

**Comment by chobits** [comment]
> @samugi @chobits Could you please take a look?

Ok i'll. take a look

**Comment by chobits** [comment]
Hi @theMiddleBlue could you provide a detailed upgrade progress.

I could only reproduce a similar error message when downgrading from the version with request-id feature to `release/3.4.x` branch which does not support request id feature. Normally, upgrading will not trigger similar error messages.

My error message is `Error: headers: invalid entry 'x-kong-request-id'`, but yours is `headers_upstream: invalid entry 'x-kong-request-id'`, note that differences between `headers` and `headers_upstream`

--- 

The following is my investigation:


The reason why i found `headers x-kong-request-id entry invalid` is that there is `x-kong-request-id` in my .kong_env file. 

```
$ grep 'x-kong-request-id' -R /Users/xc/work/dev/kong/bazel-bin/build/kong-dev/kong/servroot/.kong_env
/Users/xc/work/dev/kong/bazel-bin/build/kong-dev/kong/servroot/.kong_env:headers = server_tokens,latency_tokens,x-kong-request-id
```

I think the issue I'm facing is because, previously, i started kong on a version that could generate x-kong-request-idin .kong_envfile, then when i switched to release/3.4.x without the request_id feature, it will reported  Error: headers: invalid entry 'x-kong-request-id' .

**Comment by chobits** [comment]
A simple way to resolve your problem is to remove `x-kong-request-id` from your `.kong_env` file, or just remove this file.
