### ISSUE TITLE
[request] Forward Proxy

### ISSUE THREAD

**Issue by montanaflynn** [Kong/kong#214]
I would love if Kong supported forward proxying where you didn't have to first create the API but it would just accepted any `host` header. This would make Kong easier for testing, open up a whole new set of use cases and allow Kong to integrate with a huge set of tools and services. Not sure how the implementation would work though, definitely needs some thought on that end.

**Comment by ahmadnassri** [comment]
Kong can certainly do that, but creating an API should be required, at the very least for configuring plugins.

an alternative is to built a simple plugin for re-routing the upstream based on a header (like `Host` header or custom)

**Comment by thefosk** [comment]
Happy to discuss about a potential implementation for this.

**Comment by shahamit** [comment]
I am been looking out for a API gateway solution that can act as a forward API proxy. To be on the same page here's what I understand by a forward proxy - a proxy that can intercept third party api calls made by my application to vendors like yammer, twitter, youtube, salesforce etc and have a centralized implementation of some cross cutting concerns to ease product integration's.  
I can see below benefits of it. For each of them I have noted down my analysis with Kong
1. Caching - didn't find a plugin for this
2. Monitoring - Kong provides integration with galileo & nginx plus but since these are paid, what could be an alternative?
3. Logging - the logging plugins fit here
4. Billing - A plugin that can allow configuring the way api calls are priced - pricing per call or subscription based or tiered access. By monitoring the api calls, the plugin can generate a report that gives an idea about the cost.
5. Fault handling - centrally handling network failures & automatic retries

Thoughts?

**Comment by haifengkao** [comment]
I am making a forward proxy plugin for kong. The basic functionality is done (based on @ahmadnassri 's idea). Feel free to join https://github.com/haifengkao/kong_proxy

**Comment by ahmadnassri** [comment]
@haifengkao awesome, will follow progress!

**Comment by samgaw** [comment]
Are there any plans for including this in the roadmap near-term?

The two biggest benefits that I can see would be:
- Key management for 3rd party services
- What I've always known as entitlements i.e. rate-rating, cost management of external APIs etc.

**Comment by krjensen** [comment]
Anything new on this one - the kong_proxy git repo hasn't been touched in a year now?

**Comment by haifengkao** [comment]
Because it works :)

**Comment by thibaultcha** [comment]
Kong Enterprise Edition now has a [Forward proxy](https://getkong.org/plugins/ee-forward-proxy/) plugin - closing this!

**Comment by dekelev** [comment]
For the purpose of local debugging and testing, I've created a [transparent-proxy Kong custom plugin](https://github.com/dekelev/kong-transparent-proxy) that acts as a transparent HTTP proxy.

Since this plugin has to be attached to a service or route, I've included a Kong offline config file with a single route that will match all incoming traffic.

Tested with Kong v2.1 using the shared docker-compose.yml example and a local Kubernetes cluster on a Mac OS.
