### ISSUE TITLE
[request] Serving Static Content

### ISSUE THREAD

**Issue by montanaflynn** [Kong/kong#216]
Sometimes I just want to serve a static file, a string, or even just a response code. Right now Kong only supports setting up APIs or Microservices, which is definitely it's intended use case, but I think is limiting adoption as it prevents completely migrating from something like NGINX to Kong. 

To get around this limitation for the time being I've been modifying the NGINX block inside `kong.yml` and adding my own server blocks. As for an actual implementation I don't know if this is something that should be in the core or made available as a plugin, any thoughts or discussion would be welcomed.

Here are some use cases using NGINX as an example:

Serving a file:

```
server {
  server_name example.com;
  location / {
    root /www;
    index index.html;
  }
}
```

Returning some text:

```
server {
  server_name health.example.com;
  location /marco {
    return 200 'polo';
  }
}
```

Returning a 404:

```
server {
  server_name old.example.com;
  location / {
    return 404;
  }
}
```

**Comment by tyiss** [comment]
I'm planning to proceed with this. thought it could be implemented as plugin, say 'statics' ?

it will hold db table that store route details (uri, response code, static text, path to file, etc).
the routes will be managed throgh the api (8001) so that to add static route:
<pre>
curl kong:8001/statics/add -d "uri=/statics/two" -d "status_code=200" -d "response_text=static text"
</pre>

after kong saved that uri, request to kong:8000/statics/two will response from kong directly (not upstream), with '200' as status code and "static text" as response body.

@thibaultCha, @thefosk @ahmadnassri  any thoughts regarding this ?

**Comment by thibaultCha** [comment]
My thought on that is that soon we will have a better nginx configuration customization. This can already be implemented in the nginx configuration, which will soon be broke down into smaller pieces and assembled on start. I think a plugin for that is overkill.

**Comment by ahmadnassri** [comment]
two points of view:

- if nginx config is split out, and allowed to `include` then we can describe this in a guide rather than in a plugin and allow people to setup their static content that way.

however, what if the purpose of static content is to also use Kong plugins? is the answer to:

- route through Kong localhost loop (x2 http calls)
- or plugin to serve static content?

**Comment by marccardinal** [comment]
What is the recommended workaround in the meantime?

**Comment by Vivekbhusal** [comment]
@tyiss I have same thoughts for approaching this issue. Did you solve this?

**Comment by Tieske** [comment]
@Vivekbhusal have you read this: https://getkong.org/docs/0.11.x/configuration/#serving-both-a-website-and-your-apis-from-kong

**Comment by alepeltier** [comment]
Does anyone know of a way to render static websites with the kong-ingress controller? Is it the same as the above link?

**Comment by zffocussss** [comment]
@alepeltier same here

**Comment by hbagdi** [comment]
> Does anyone know of a way to render static websites with the kong-ingress controller? Is it the same as the above link?

You can simply expose an existing kubernetes service via Ingress spec. It doesn't matter if it is a static website or an API.

**Comment by kuwv** [comment]
This is required for micro-frontend support.

**Comment by nbhadauria** [comment]
I was also looking for something like this, so write a plugin [Link](https://github.com/IntelliGrape/kong-plugin-static-response)

This is my first attempt, so please provide your feedback.

**Comment by bungle** [comment]
Kong has request termination plugin and now there is third party plugin too. So I think that covers it. You can also inject your own blocks in our nginx template. Closing this.
