### ISSUE TITLE
Kong latency headers not always displayed

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#2767]
When a request is prematurely terminated by a Kong plugin, the latency headers are not displayed in the response.

**Comment by thibaultcha** [comment]
This is a side-effect of our plugins runloop and relates very closely to the "log plugins executing after a request is terminated". I've linked this issue to the related internal tracking bug report. For now, let's still leave this open and link it to the other runloop issue if we notice them.

**Comment by thibaultcha** [comment]
Taking a second look at this after #3079, and the following thought crosses my mind: if the request was short-circuited, and thus, not proxied, does it make sense to send the Proxy Latency and the Upstream Latency headers at all? Probably not? If we do send the Proxy Latency header, then its name is incorrect.

**Comment by subnetmarco** [comment]
In the example of a short-circuited request at least the proxy latency should still be sent, as the short-circuiting still involves Kong processing time. The upstream latency doesn't matter (since there is no upstream), and perhaps that can be skipped or defaulted to `0`.

**Comment by bungle** [comment]
I close this because that debate we never ended up implementing this. We need to come up with a proper use-case. So @subnetmarco please reopen if you have one. Implementation-wise it is very easy.

**Comment by subnetmarco** [comment]
@bungle the use-case has been illustrated in this thread:  when a request is short circuited by a plugin, we still want to display the proxy latency that determines how long the processing took.

**Comment by bungle** [comment]
@subnetmarco I undestand that, but one might argue, that Lambda plugin should use `proxy`. This was already proposed on #3123 exactly as you wanted, but the issue was closed.

We can have different cases:
1. request comes to proxy|admin, nginx errors right away
2. request comes to proxy|admin, and kong errors before|after proxying
3. request comes to proxy|admin, and everything is ok
4. request comes to proxy|admin, and plugin short-circuits

There could be others. I think you need to sit down with @thibaultcha to figure out:

1. the actual need for this
2. the proper naming

As seen the implementation is dead-simple, but this is stuck in decision making.

**Comment by thibaultcha** [comment]
All good with me, feel free to add any header you judge useful 👍🏻

**Comment by subnetmarco** [comment]
@bungle today we send a couple of latency headers:

* `X-Kong-Proxy-Latency` which determines the latency of the Kong Proxy/Gateway activity before and after (and not during) a request is being proxied.
* `X-Kong-Upstream-Latency` which determines the latency of the upstream service (and network to reach such service) whenever the request is being proxied.

You agree with me that if the request is not being proxied to an upstream (because, for example, a plugin prematurely terminates the request), that doesn't mean that the Kong process didn't spend computational time to deal with the incoming client request.

This GH issue wants to add the `X-Kong-Proxy-Latency` to every response, even when terminated prematurely because today it's not being sent.

I also want to make sure that by `X-Kong-Proxy-Latency` it is clear that we intend the Kong process latency added before and after the proxying activity: and if no proxying activity is being performed (premature end) the process latency still stands.

**Comment by bungle** [comment]
@subnetmarco, are you fine with adding new header e.g. `X-Kong-Response-Latency` on such cases where we don't use proxy? It is quite hard for us to determine if plugin did send additional request (lambda plugin, forward-proxy plugin) or did the plugin short-circuit and reply immediately (request-termination). I would like to keep `X-Kong-Proxy-Latency` only on those cases where code went to the point where Kong added ´ngx.ctx.KONG_PROXIED=true`. On other cases (including lambda and forward proxy plugin) we add `X-Kong-Response-Latency`.

The `X-Kong-Proxy-Latency` does not contain the latency Kong adds after the request was proxied (e.g. header_filter + body_filter). It could count `header_filter` but it cannot count `body_filter` as at that point it is too late to send any headers (trailers probably, but not headers). That's why I suggest we keep current meaning of `X-Kong-Proxy-Latency` (being the latency added before proxy-module took over, that is after balancer).

We can though add `ctx.KONG_TOTAL_LATENCY` for logging plugins that takes into account both `pre` and `post` proxying latency.

**Comment by bungle** [comment]
Closing this as it is now implemented in #4998.
