### ISSUE TITLE
The `hosts` inside response of `GET /apis` is JSON_OBJECT when api's `hosts` is empty

### ISSUE THREAD

**Issue by devenfan** [Kong/kong#2773]
### Summary

The `hosts` inside response of `GET /apis` is JSON_OBJECT when api's hosts is empty, it should be JSON_ARRAY

### Steps To Reproduce

1. Add an API without `hosts`
2. Call `/apis` with http `GET` method
3. The response is as below:
``` json
{
  "data": [
    {
      "http_if_terminated": true,
      "id": "42e28608-6c3f-4eee-a3ca-5a0ed44f2d19",
      "retries": 5,
      "preserve_host": false,
      "created_at": 1501065757788,
      "upstream_connect_timeout": 60000,
      "upstream_url": "http://httpbin.org",
      "uris": [
        "/test"
      ],
      "upstream_send_timeout": 60000,
      "https_only": false,
      "upstream_read_timeout": 60000,
      "strip_uri": true,
      "name": "test",
      "hosts": {
        
      }
    },
    {
      "http_if_terminated": true,
      "id": "f813a66b-bac6-4952-831b-f04d53ae0bf0",
      "retries": 5,
      "preserve_host": false,
      "created_at": 1501753576084,
      "upstream_connect_timeout": 60000,
      "upstream_url": "http://httpbin.org",
      "upstream_send_timeout": 60000,
      "https_only": false,
      "upstream_read_timeout": 60000,
      "strip_uri": true,
      "name": "Test_V2_Api_new",
      "hosts": [
        "example.com"
      ]
    }
  ],
  "total": 2
}
```
4. **As you can see in the first api `test`, the `hosts` is `{}`. Shouldn't be `[]`?**

### Additional Details & Logs

- Kong version (`0.10.3`)
- Operating System (`CentOS 6.8`)

**Comment by cyrilgdn** [comment]
Hi,

I have the same problem with the field "uris"

**Comment by thibaultcha** [comment]
Hi,

I believe this has been solved in our most recent releases (especially 0.11.1) sincea missing hosts property simply does not show it. This behavior is due to the specifics of the Lua language and some missing features to the lua-cjson encoding library we use. Features that we since contributed and are starting to use in Kong to handle such empty lists.

In short: we are very much aware of the issue and are slowly working our way down the list of reported places where this has occurred, to use our fix contributed to lua-cjson.

Thank you for the report!
