### ISSUE TITLE
Make active targets the default URI

### ISSUE THREAD

**Issue by thefosk** [Kong/kong#2791]
* Make `/upstreams/:upstream_name_or_id/targets/active/` become the default one.(`/upstreams/:upstream_name_or_id/targets/`)
* Introduce `/upstreams/:upstream_name_or_id/targets/all` to show all the targets.

**Comment by hbagdi** [comment]
@thefosk what do you mean by target here?

**Comment by hbagdi** [comment]
@thefosk @thibaultcha 
Just wanted to make sure if the following sounds correct:

- The current default route `/upstreams/:upstream_name_or_id/targets/`  should instead be `/upstreams/:upstream_name_or_id/targets/all`.
- The `/upstreams/:upstream_name_or_id/targets/active/` remains as is.

Making the current default route as `active` seems incorrect to me.

**Comment by thibaultcha** [comment]
@hbagdi What the @thefosk means here, is that when a user queries `/upstreams/:upstream_name_or_id/targets/`, we think the user should see the currently active Targets or a given Upstream (the physical hosts currently on the balancing wheel). Only when a user queries `/upstreams/:upstream_name_or_id/targets/all`, should they see the entire list of Targets (old and current). The `/.../active` one would disappear.

Today, a request to `/upstreams/:upstream_name_or_id/targets/` returns *all* Targets, even previous ones. As you may know, Targets are immutable. They can only be created, but not modified nor deleted. To update/remove a Target, one must make create a new one with a different `weight` (`0` for disabling it). We think this is confusing, and we wish to hide this underlying implementation details to the user, so that they interact with this endpoint in a more RESTful fashion.

**Comment by hbagdi** [comment]
@thibaultcha thanks for the lucid explanation!
I'll take this up and send you a PR soon.

**Comment by thibaultcha** [comment]
Done with #3049
