### ISSUE TITLE
ngx.ctx.upstream_url = "http://www.otherurl.com" does not work in kong > 0.9

### ISSUE THREAD

**Issue by zamarroz** [Kong/kong#2834]
I`m trying to change ngx.ctx.upstream_url value but in kong versions over than 0.9 does not work. Has this changed in the new versions?

**Comment by zamarroz** [comment]
Ok, after few hours of break my mind I found this:

```
ngx.var.upstream_uri = "https://www.google.com"
```

When I set this value and send a request Kong response with this message:

```
2017/08/23 11:28:51 [error] 22#0: *13 invalid port in upstream "kong_upstreamhttps://www.google.com", client: 192.168.64.1, server: kong, request: "GET /poc HTTP/1.1", host: "localhost:8000"
```

I'm totally blocked....

**Comment by macedogm** [comment]
Hi @zamarroz.
I'm using the variable ngx.ctx.api.upstream_url to change the upstream URL. Maybe you should try using it.
Best regards.

**Comment by costasvassilakis** [comment]
After a few hours of struggling, the situation in Kong 0.11 appears to be as follows:

- ngx.var.upstream_uri can be used, but only to change the path part of the upstream URL, not the host part. This only works in the _access_ context.

-  should you need to change the host part, you may try the solution given in https://stackoverflow.com/questions/45839634/kong-api-gateway-v0-11-0-upstream-url (have not tried it myself)

- of course, the two methods can be combined to change both the upstream URL and the host

**Comment by zamarroz** [comment]
@costasvassilakis the stackoverflow author is a coworker :) Thanks!

**Comment by thibaultcha** [comment]
Hi,

Indeed, following the introduction of load balancing capabilities in Kong 0.10.0, updating the host of an upstream request does not mean updating the `ngx.var.upstream_url` variable anymore. Since this is officially an unsupported feature for plugins (but still possible, heck, our own plugins even do it!), it is a bit hard to get around the codebase and implement those feature yourself (update upstream URL or upstream host/port), I know...

See the `ngx.ctx.balancer_address.host` and `ngx.ctx.balancer_address.port`, as well as `ngx.var.upstream_uri` variable for tweaking these values in Kong 0.11.

In the future, we intend to provide plugins developers with a full-fledged API for manipulating such values from your Lua code, with minimal efforts :)

Thanks!
