### ISSUE TITLE
[events] could not broadcast crud event: nil   AND  insert(): could not propagate CRUD operation: nil

### ISSUE THREAD

**Issue by AveiShriety** [Kong/kong#2872]
**SUMMARY**
Hi! In our test, when we  use  _**SOAPUI**_  to **make a pressure test** on the kong to get token, the error occurs!

### Steps To Reproduce
1.add an api
2.add oauth2 plugins to this api
3.start a pressure test on the uris "/{uris}/oauth2/token" to get the token or refresh token

### Additional Details & Logs

- Kong version (0.11.0)
- Operating System(Centos6.5)
- Kong error logs:
```
2017/09/06 16:30:31 [error] 2753#0: *8555 [lua] handler.lua:128: [events] could not broadcast crud event: nil, client: 192.168.206.104, server: kong, request: "POST /uris/oauth2/token HTTP/1.1", host: "192.168.202.23:8443"
2017/09/06 16:30:31 [error] 2753#0: *8555 [lua] dao.lua:155: insert(): could not propagate CRUD operation: nil, client: 192.168.206.104, server: kong, request: "POST /uris/oauth2/token HTTP/1.1", host: "192.168.202.23:8443"
```

**Comment by thibaultcha** [comment]
Hi,

After some investigation, I can tell you that those logs are harmless, and due to a slight oversight in API design. The fact that the error message is `nil` shows that there is, indeed, no error. I'll be proposing a PR soon which will not print such error messages without a good reason.

Thanks for the report!

**Comment by thibaultcha** [comment]
#3002 took care of this and will be part of our next release. Thank you for reporting this!
