### ISSUE TITLE
Plugin suggestion: Azure Functions

### ISSUE THREAD

**Issue by psmulovics** [Kong/kong#2954]

**Comment by hishamhm** [comment]
Hi! Please note that our Github issue tracker is aimed at tracking bugs only. For suggestions or other kinds of discussion, please consider posting to Gitter or the mailing list as noted here: https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help. Thank you!

**Comment by psmulovics** [comment]
You guys should update https://getkong.org/plugins/ then - it points to this URL to submit plugin suggestions.

**Comment by hishamhm** [comment]
@psmulovics Oh, indeed, sorry! There has been certainly a miscommunication on our side. We are in the process of reorganizing our support channels, so that community feedback like plugin ideas don't get lost in the sea of Github issues.

I tagged this issue so it gets addressed as we reorganize things and we will check the website links. Thank you for the heads up!

**Comment by psmulovics** [comment]
Let me know whether you have considered picking up this idea.

**Comment by Tieske** [comment]
duplicate of #2652
