### ISSUE TITLE
Missing X-Forwarded-Prefix header in 0.10 and 0.11

### ISSUE THREAD

**Issue by bloche** [Kong/kong#2999]
### Summary

I recently upgraded from 0.9.9 to 0.10.3 and it appears the `X-Forwarded-Prefix` header has been dropped.

I've used this header to identify what the actual URL is the client used so the API can function both behind Kong and on it's own. I use path based routing in Kong, having Kong strip the path prefix before proxying to the API. However, now that the `X-Forwarded-Prefix` header has been removed I can no longer accurately reconstruct the full URL clients use to reach the API. I've since upgraded to 0.11.1 hoping the issue may have been solved in the latest version, but it doesn't appear to be.

#### Sample `X-*` headers from Kong 0.9.9:

```
X-Consumer-Groups
X-Consumer-Id
X-Consumer-Username
X-Credential-Username
X-Forwarded-For
X-Forwarded-Port
X-Forwarded-Prefix    <---
X-Forwarded-Proto
```

#### Sample `X-*` headers from Kong 0.10.3 and 0.11.1:

```
X-Consumer-Groups
X-Consumer-Id
X-Consumer-Username
X-Credential-Username
X-Forwarded-For
X-Forwarded-Port
X-Forwarded-Proto
```

### Additional Details
- Running under Kong docker images

**Comment by thibaultcha** [comment]
Hi @bloche,

Yes indeed. Started in 0.10 we decided to drop "non-standard" (I know it sounds redundant) `X-Forwarded-*` headers, and change the meaning of such forwarded headers to carry information that is commonly conveyed by those headers. That means those headers, as of today, carry more meaning about the typical reverse-proxying flow, and less about Kong-specifics, like "which API" was matched, and "how" it was matched. This is very likely to stay like so.

That said, we do understand the value of providing headers to the upstream services about which API Kong detected and how it did so. However, we believe those headers should be configurable, because not every user will rely on them in their upstream services. As of today, such "matching" information is constrained to the core, and available [here](https://github.com/Kong/kong/blob/master/kong/core/handler.lua#L318) for plugins consumption.

If you wish to send such information upstream via HTTP headers, I suggest writing a plugin that adds that information to the upstream HTTP request. It should be extremely straightforward. In the future, we will explore ways of providing this behavior out of the box, possibly in a configurable fashion.

**Comment by thibaultcha** [comment]
> reconstruct the full URL clients use to reach the API

Just curious: how come you don't rely on transparent proxying instead?

**Comment by bloche** [comment]
@thibaultcha Thanks for clarifying that for me, your quick response is much appreciated.

> Just curious: how come you don't rely on transparent proxying instead?

This is the way my colleagues and I started using Kong a while back and haven't had any real problems with it until now. However, we will probably start to move toward a transparent proxy moving forward, as there have been some other minor inconveniences because of it.
