### ISSUE TITLE
Load Balance - route traffic to same Data Center with upsream/target configuration

### ISSUE THREAD

**Issue by java4fun** [Kong/kong#3042]
I have a requirement to set up multi-DC cluster using upstream/targets for dynamic load balance.  If we add targets of multi-DC to the upstream, how can I make Kong to route traffic to target on the same DC, instead of other DCs,  unless the services are all down in the local DC. For example, if traffic comes to Kong in Dallas DC, I prefer kong route the traffic to endpoint located in Dallas too.

**Comment by hishamhm** [comment]
The Kong load balancer implements distributes load among targets based on weights. What you want instead is to prioritize targets differently on each DC. One way to use that is, instead of having the upstream balance multiple targets, to set those targets in one [SRV record](https://en.wikipedia.org/wiki/SRV_record) in DNS and use SRV record priorities. For example, in your Dallas DC, you can set up your DNS so that the Dallas endpoint gets higher priority. Our `lua-resty-dns-client` library used by Kong supports SRV records honoring priority so things should work as you expect. 

(Side note: the Github issue tracker is aimed at reporting bugs, for general support please refer to the [mailing list or Gitter](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#community-edition) — thanks!)
