### ISSUE TITLE
Can't update plugin by name

### ISSUE THREAD

**Issue by AlexKovalevych** [Kong/kong#3044]
### Summary

Can't update plugin by its name

### Steps To Reproduce

1. Create api
2. Add plugin to it
3. Try to update a plugin with PATCH method, e.g.:

```
curl -XPATCH "http://localhost:8001/apis/138575d3-7714-44ea-a1f0-dca02baca397/plugins/response-transformer" --data "config.remove.headers=x-request-id"
{"id":"response-transformer is not a valid uuid"}
```

According to docs, https://getkong.org/docs/0.11.x/admin-api/#update-plugin, i should be able to update plugin by its name. It seems like here https://github.com/Kong/kong/pull/2252 it was fixed only for GET method.

### Additional Details & Logs

- Kong version 0.11.1

**Comment by thefosk** [comment]
That's not possible, you need to use the plugin ID.

**Comment by thibaultcha** [comment]
@AlexKovalevych This is a mistake on our side. It is indeed not possible to retrieve/update/delete a plugin by its name, since several instances of a same plugin can be configured simultaneously. One needs to use the `id` of such plugins to update them.

I have opened https://github.com/Kong/getkong.org/pull/552 on our documentation website, which should take care of fixing that.

In the meantime, I will be closing this issue, and considering it resolved. Sorry for the confusion!

**Comment by AlexKovalevych** [comment]
@thibaultcha thank you for your response. But right now, adding a second instance of the same plugin gives me 409 status code response. That makes me think its not possible to add multiple instances of the same plugin (or i'm doing it wrong).

```
$ curl -XPOST "http://localhost:8001/apis/138575d3-7714-44ea-a1f0-dca02baca397/plugins" --data "name=response-transformer&config.remove.headers=x-request-id" -i
HTTP/1.1 409 Conflict
Date: Wed, 22 Nov 2017 08:36:29 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.11.1

{"name":"already exists with value 'response-transformer'"}
```

Same Kong version (0.11.1)

**Comment by thibaultcha** [comment]
It is possible if they are added to the same API but different Consumers. This is detailed in the revert commit linked in the docs PR.

**Comment by AlexKovalevych** [comment]
got it, thanks
