### ISSUE TITLE
Kong CORS plugin - limitation with hosts

### ISSUE THREAD

**Issue by markgandy** [Kong/kong#3132]
### Summary

I'd like to get some more info on the limitation with the CORS plugin. The documentation states the plugin will not work for APIs configured with `hosts`.

Is there any issue if the CORS plugin is global. All of our APIs are configured using `hosts`, and we have a global CORS plugin which has been working nicely.

But now we need specific CORS config for a single API (that is configured with `hosts`). I thought the specific API CORS plugin would override the global CORS plugin for requests that match that API. But it actually seems to merge the config?

I can see that `Access-Control-Allow-Origin: *` is set from the global plugin, and `Access-Control-Allow-Credentials: true` is set from the specific API plugin.

Do you have any advice on how best to solve? We need a global config with `origins: *`, but need to allow credentials (and restrict origins) for one API

### Steps To Reproduce

1. Create global CORS plugin
2. Create API config (with `hosts` config)
3. Create CORS plugin for API
4. Send requests to API and see the config is merged from global and API

### Additional Details & Logs

- Kong version (`$ kong version`) 0.10.4

**Comment by kikito** [comment]
Hello,

> I thought the specific API CORS plugin would override the global CORS plugin for requests that match that API. But it actually seems to merge the config?

You have configured two plugins: one is global, and the other applies to only one API.

The global plugin does not stop working just because another plugin of the same kind is configured. This is Kong's behaviour by default - you can set up multiple plugins which trigger by different reasons and all work together. It's not that the config is "merging". Is that the two instances of the CORS plugin are run, one after the other.

> Do you have any advice on how best to solve? We need a global config with origins: *, but need to allow credentials (and restrict origins) for one API

There are several problems with this approach.

The first one  is that the two things that you are asking are in opposition to each other: In Kong you can't have a plugin that is at the same time "global" and "not apply to this specific API".

One possible option that you could consider in order to overcome this problem is writing your own CORS plugin, where you would handle the execution conditions as you saw fit.

This brings us to the other problem: your apis are set up using the `hosts` option. The [docs](https://getkong.org/plugins/cors/#cors-limitations) are very clear on this not working with the CORS plugin. The way to solve that will depend on your specific config. The one which comes immediately to mind is using some other means (like a different header).

Finally, please note that our preferred channel for questions like yours is [Kong Nation](https://discuss.konghq.com/). If you want to further discuss this, please create an issue there. In the meantime, I will close down this one.
