### ISSUE TITLE
rewrite cause api match fail

### ISSUE THREAD

**Issue by samwonwyd** [Kong/kong#3140]
### Summary

I write a custom plugin to rewrite uri, the plugin is global, the plugin rewrite function is be called on every request, that's OK. But during the match api phase, something wrong. In router.lua, in function exec, it use ngx.var.request_uri to match api
```
    local method      = ngx.req.get_method()
    local request_uri = ngx.var.request_uri
    local uri         = request_uri

    do
      local idx = find(uri, "?", 2, true)
      if idx then
        uri = sub(uri, 1, idx - 1)
      end
    end

    local req_host = ngx.var.http_host

    local match_t = find_api(method, uri, req_host, ngx)
    if not match_t then
      return nil
    end
```
request_uri is a readonly variable ,can't be changed in rewrite phase.
### Steps To Reproduce

1. write a custom plugin to rewrite a uri
2. enable the plugin globally
3. make a request
4. rewrite is Ok, but can't match api

### Additional Details & Logs

- Kong version (0.11.0)
- CentOS6

**Comment by bungle** [comment]
Yes, this is a known issue, partly because of these:
https://github.com/Kong/kong/pull/2377

and further discussed here:
https://github.com/Kong/kong/issues/2366

It is a bit unfortunate that the `ngx.var.uri` is normalized (with non-standard normalization rules). I think we need to provide our own API to rewrite, and at that point the line:

```
local request_uri = ngx.var.request_uri
```

may be changed to something like:

```
local request_uri = ngx.var.upstream_uri ~= "" and ngx.var.upstream_uri or gx.var.request_uri
```

**Comment by thibaultcha** [comment]
Closing this due to the lack of activity in #3141. The solution proposed there, although welcome, was never contributed.
