### ISSUE TITLE
for your OSX installation page, there is no documentation on what a kong.conf file is?

### ISSUE THREAD

**Issue by aronlmin** [Kong/kong#3151]
For a new user trying to get it installed, your installation instructions mention a migration step, but do not explain what the installer is migrating from, or whether or not that step can be skipped, and for what purpose, nor does it explain what a kong.conf file is -- is this something that was installed that needs to be mapped? what is it?

I installed kong with homebrew for mac, and did a search through my entire computer for the kong.conf file, it was never installed anywhere

**Comment by kikito** [comment]
> For a new user trying to get it installed, your installation instructions mention a migration step, but do not explain what the installer is migrating from, or whether or not that step can be skipped, and for what purpose

Kong uses a database (PostgreSQL or Cassandra) for persistence. In certain occasions the structure of the database needs to be changed; for example when updating from an older version of kong, or because you are installing a new plugin on the existing version. These changes on the database receive the name of "migrations".

Installing Kong for the first time is one of these occasions in which the database structure changes. All the migrations need to be run sequentially.

As we thought migrations it is a [widely used term](https://en.wikipedia.org/wiki/Schema_migration) we didn't think it was necessary to explain it. But we'll take your feedback into account, and if more people have the same problem as you, we'll add more info about migrations.

> kong.conf file [...] what is it?

That is the main configuration file for kong. It is explained in detail on this section of the documentation: https://getkong.org/docs/0.12.x/configuration/

Finally, please note that Kong Github issues are for bug reports only. If you want to discuss this further, please use https://discuss.konghq.com/ . I will close this issue now. If you think this is a bug and not a question, please reopen.
