### ISSUE TITLE
Create of the http-log plugin on an API through /plugins fails to activate it

### ISSUE THREAD

**Issue by mvanholsteijn** [Kong/kong#3226]
### Summary

When I add the http-log plugin on an api via a POST on /plugins while specifying the api_id, it does associate it with the API but it does not work.

When I add the http-log plugin on the api via a POST on /apis/<id>/plugins it does deliver a working plugin

### Steps To Reproduce

1. create an api
2. add the http-log plugin via /plugins
3. call the api (No log records are reported)
4. remove the http-login plugin 
5. add the http-log plugin via /apis/$API_ID/plugins
6. call the api (\0/  log records are reported)

### Additional Details & Logs

- Kong version (`$ kong version`)
0.11.2

**Comment by p0pr0ck5** [comment]
This issue has since been resolved with the release of Kong 1.0 and the refactor of various internal code elements to support a saner and more stable database access layer.

If a similar issues in Kong 1.0 with Service/Route objects is observed, please feel free to re-open this issue and we can examine it. Thanks!
