### ISSUE TITLE
clustering on dc/os

### ISSUE THREAD

**Issue by therzv** [Kong/kong#3230]
i am using DC/OS Mesosphere 1.10 and planning to use Kong as replacement of Marathon/LB, what problem we face is, we didnt find any documentation to implement this.

Indeed on DC/OS has kong already, but when we scale it, it didnt do clustering. how we do this? is there any documentation to put cluster configuration on DC/OS configuration?

Thank you so much

**Comment by kikito** [comment]
You didn't mention which documents have you read, so here are the two relevant ones for your situation:

* [Installing Kong under DC/OS](https://getkong.org/install/dcos/)
* [Kong Clustering](https://getkong.org/docs/0.12.x/clustering/)

>  but when we scale it, it didn't do clustering

If the problem is that traffic is not routed to the nodes, please note that at the moment an instantiated cluster of kong nodes does not do downstream routing by itself; it must be put behind a load balancer, [as indicated on the first paragraph on the clustering docs](https://getkong.org/docs/0.12.x/clustering). The configuration of such load balancer is up to you.

If this answer didn't resolve your issue completely, let's please continue the conversation in https://discuss.konghq.com/ . Github issues are mainly for bug reports.
