### ISSUE TITLE
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused

### ISSUE THREAD

**Issue by sukumarvangala** [Kong/kong#3260]
Software Versions:

CentOS: 7
ember-cli: 2.12.2
node: 7.9.0
Kong: 0.10.2
Postgres: 9.5.2

Project is hosted via docker on AWS EBS.

Synopsis: Ember application is used to run on AWS EBS with the same ember-cli and node versions but kong version as 0.8.3.
Once 0.8.3 version is made unavailable, I upgraded the to kong version 0.10.2 but used the same configuration files. The following error occurs when deployed.

' Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused '

Solutions for this error suggests to upgrade the Postgres version from 9.2 to 9.4.2 or higher, but am already using 9.5.2.

The following other options were tried and still experiencing the same error.
Kong version: 0.11.0, 0.12.2
Changing the ports from 8000 to 8001 and 8443

Elastic Bean stalk says '502 Bad Gateway' when deployed.

Did any one face this kind of error?
Can anyone suggest any solution for the above issue.

Thanks in advance.

**Comment by hishamhm** [comment]
> ' Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused '

The "connection refused" message means that your database configuration is incorrect. Did you follow the [upgrade path procedures](https://github.com/Kong/kong/blob/master/UPGRADE.md)?

**Comment by hishamhm** [comment]
Also, since this looks like a configuration issue (note that the configuration format did change after 0.8.x!), I would like to direct you to our [https://discuss.konghq.com](Kong Nation) forum instead, where you will have a better chance to have your questions addressed by the community. The Github issue tracker in the Kong repo is for bugs only. So, I'm closing this for now. Feel free to reopen if you believe this to be a bug in Kong.
