### ISSUE TITLE
Broken or confusing documentation on API evaluation order

### ISSUE THREAD

**Issue by cogitaria-admin** [Kong/kong#3276]
### Summary

Here is the documentation that discusses API ordering:

https://getkong.org/docs/0.12.x/proxy/#evaluation-order

Assuming URI _prefixes_ (anything without a regular expression) are processed first, the second configuration` /version/\d+/status/\d+` will never work because` /version` always wins.  How to ensure "prefixes' do not interfere with "regular expressions"?

### Steps To Reproduce

N/A

### Additional Details & Logs

N/A

- Operating System

N/A

**Comment by thibaultcha** [comment]
Hi,

regexes are always evaluated, even if a plain prefix already matched a request. This is the behaviour followed by nginx by also by the Kong router, as we believe it allows for the most flexibility. Maybe this is not specified anywhere in this document, in which case, a PR to do so would be most welcome :)

It is also worth noting that this section of the document described the _evaluation_ order, as in: which APIs are evaluated before others when all have `uris`. As such, I am of the opinion that it would make sense to show a counter-example of "what _not_ to do, because evaluation ordering will not be on your side".

A good and a bad example would probably help clarify this section:

- the good one (current) and why it will match both the prefix and the regexes depending on the request path
- an invalid one, showing how a particular regex can shadow another one if it is older

**Note:**, it is worth mentioning that in 0.13.0 (of which one release candidate is already available) introduces a `regex_priority` field to not rely on the creation time as a criteria for regex evaluation order.

**Comment by thibaultcha** [comment]
Moved to the proper repository: https://github.com/Kong/getkong.org/issues/611
