### ISSUE TITLE
documentation: Admin API Swagger Docs

### ISSUE THREAD

**Issue by dmportella** [Kong/kong#3307]
Hello

I like to request if at all possible for Kong to provide as part of their admin api documentation swagger docs so that it easier to work with the API in a adhoc basis including interrupting with other products like postman, api generators etc.

Regards

**Comment by bungle** [comment]
@dmportella Thanks for asking. We recently had a hackathon within Kong, Inc., and I participated with @kikito to build just that! We had a few ideas:

- With our new schema on our new model, let's use that to generate OpenAPI specs for all our Admin APIs (we made half-way through with this in hackathon)
- Have a plugin that verifies requests (based on spec file) and if there are errors with compliance, gives 400 back.
- Have mechanism to analyze proxy traffic and collect information about APIs, so that we can also generate OpenAPI specs to them (for any API) (sort of AI or something) (and the spec can then also be auto correcting)
- Have admin API endpoint where you can upload (or import) a spec file and Kong then autogenerates all the APIs for proxy (and applies the verification plugin as well)

@kikito do you remember if we had other ideas as well?

**Comment by bungle** [comment]
And yes, I hope that we get a change to work on it in future, to make it actually a shippable thing.

**Comment by bungle** [comment]
@dmportella, We don't use Github to discuss about new features (anymore). We'd prefer to have such discussion at Kong Nation Discussion board: https://discuss.konghq.com/. We cannot give estimate of this work, but it is on our backlog. That's why I am closing this. Lets hope we get that prioritized and done (I can say that you weren't the first one to propose this) OR perhaps contributed by community, who knows.

**Comment by dmportella** [comment]
no worries @bungle i am glad you guys though of if and are giving a serious consideration. 

All our ideas sound fun and great I would be just happy to have a swagger or openAPI spec for the admin API. It would make playing with kong with things like post man etc a lot easier and more fun.

I will keep an eye on the discussion board tho  thank for the update

**Comment by dmportella** [comment]
> Note
I created a topic on the discuss.konghq.com: https://discuss.konghq.com/t/documentation-admin-api-swagger-docs/861

**Comment by coopr** [comment]
I posted an update to the Kong Nation discussion forum thread noted above.

**Comment by amenophis** [comment]
Any news on this topic ? It would be nice to get autogenerated openapi client with tools like https://github.com/janephp/janephp
