### ISSUE TITLE
[request] Import Swagger 2.0/OAS

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#334]
To prepopulate APIs, authentication and Endpoints inside Kong - perhaps connect with [Gelato](https://gelato.io).

**Comment by davegolland** [comment]
:+1: for swagger 2.0 support

**Comment by mmwtsn** [comment]
+1

**Comment by t1tcrucible** [comment]
+1

**Comment by zeeshanejaz** [comment]
Is there any details on this feature request? Kong works like a proxy, so details of Endpoints shouldn't even be required. What am I missing?

**Comment by tlivings** [comment]
Going out on a limb and imagining that the request is to consumer Swagger API documents and auto-configure the proxies to them, including consuming and wiring up the security definitions contained in them.

As far as endpoints I think it would simply be consuming `host` and `basePath`.

This is a great idea but should be relatively trivial to push these configurations to Kong's REST api directly rather than require Kong to do any work.

**Comment by thibaultCha** [comment]
I totally agree with that thought. It is very trivial to do it without a plugin.

**Comment by sinzone** [comment]
example of one way of doing it http://docs.aws.amazon.com/apigateway/latest/developerguide/create-api-using-import-export-api.html?

**Comment by yograterol** [comment]
someone working in this feature?

**Comment by apur** [comment]
+1

**Comment by mytototo** [comment]
Any news regarding an open-source Swagger/OpenAPISpec plugin for Kong?

**Comment by tahaiqbalkhan9** [comment]
+1
Any updates regarding this feature?

**Comment by fontanaricardo** [comment]
Would be nice, if the kong, can also generate one swagger json, from the added APIs and microservices, adding information about kong's resources for this API (authentication by example).

**Comment by Marak** [comment]
I've written a basic script in Node.js which can load the petstore Swagger 2.0 document and import it into the Kong Admin API.

Basic parsing / import script is simple. Using plain JavaScript and a separate simple REST client for Kong Admin API. 

Unfortunately, it seems it's not possible to fully import petstore due to lack of regex routing of `request_path` in Kong #677

A possible workaround with the current version of Kong is to omit the regex routes from petstore and use a proxy. Considering this defeats the purpose of setting up granular routes based on Swagger, we had to choose to drop the Swagger import feature ( for now ).

In addition, multiple Swagger imports per single Kong instance is blocked by #369 ( as conflicting `request_path` namespaces in the Swagger will currently prevent APIs from importing )

cc @thibaultcha

**Comment by paiuolo** [comment]
+1

**Comment by koolay** [comment]
+1

**Comment by liu0013** [comment]
+1

**Comment by mward29** [comment]
+1

**Comment by psbateman** [comment]
+1

**Comment by chrisfelix82** [comment]
+1

**Comment by vintuwei** [comment]
+1

**Comment by mwaaas** [comment]
+1

**Comment by phamnamlong** [comment]
+1

**Comment by coopr** [comment]
Hi Everybody - I'm the Product Manager here at Mashape, and I'd love to hear some more details of what you'd like to see in a feature like this! Tell me about your use case, about the problems you are trying to solve, about how you'd like Kong to help you solve them with Swagger / OpenAPI Spec. 

Reply herein, or email me cooper@mashape.com - thanks in advance!

**Comment by mwaaas** [comment]
Onboarding api via swagger file and maybe a flag to turn on when to do request validation before forwarding request to upstream. 

I have actually managed to do this by a node app parsing the swagger file and onboard the api. And a plugin to forward the request and its content to the node service before forwarding the request to upstream servers. 

If I get time I might convert the node app to Lua app then contribute to Kong

**Comment by nhuray** [comment]
@mwaaas Do you have news about migrating your node app to Lua ?

**Comment by gfiehler** [comment]
@coopr I am evaluating API gateways and we have a requirement to be able to upload our swagger api documents to create APIs in the gateway.  We do contract first design with the swagger editor and would like to be able to just import them to create the base api in the gateway.  Any word on tools or new features to support this?

**Comment by coopr** [comment]
@gfiehler it'd be great to move this discussion to Kong Nation https://discuss.konghq.com/c/feature-suggestions thanks.

**Comment by Tieske** [comment]
Just for reference; This feature has been added to Kong Enterprise (from 0.36-x versions)

**Comment by rjshrjndrn** [comment]
will this feature available for kong open source? @Tieske

**Comment by mikaello** [comment]
> will this feature available for kong open source? @Tieske

I think the utility that Tieske is talking about is this: https://www.npmjs.com/package/openapi-2-kong

Original source: https://github.com/Kong/insomnia/tree/develop/packages/openapi-2-kong
Rewrite in TypeScript: https://github.com/mikaello/openapi-2-kong

See also [discussion in Kong nation](https://discuss.konghq.com/t/import-swagger-open-api-document-to-create-api-in-kong/510/18).

**Comment by Tieske** [comment]
@rjshrjndrn It is available in [Insomnia Designer](https://insomnia.rest/), and through the [`inso` commandline utility](https://www.npmjs.com/package/insomnia-inso)
