### ISSUE TITLE
Deprecate Runscope plugin

### ISSUE THREAD

**Issue by johnsheehan** [Kong/kong#3352]
Please deprecate the Runscope plug-in

https://blog.runscope.com/posts/phasing-out-traffic-inspector

**Comment by thibaultcha** [comment]
@johnsheehan Oh, sad, but good to know. Thank you for leaving a note here, appreciated.

**Comment by thibaultcha** [comment]
Done in #3495, Kong 0.14.0 (in a few weeks) will not include the Runscope plugin. If users stumbling upon this issue are annoyed by its disappearance, we can upload the plugin in a legacy repository, in case it is needed for some reason. Otherwise, the code is still in this repository's git history.

Thanks for the notice @johnsheehan.
