### ISSUE TITLE
How to use ngx.req.socket to process chunked request body

### ISSUE THREAD

**Issue by pactera-compositeapi-sunjian** [Kong/kong#3359]

**Comment by bungle** [comment]
lua-resty-upload is a good example, but be aware that its current version doesn't write the body back (there is no merged PR for that), so once the body is consumed, it is not anymore proxied to upstream (though as explained, this can be fixed).

Please use https://discuss.konghq.com/ or OpenResty mailing list for questions like this. That's why I am closing this.
