### ISSUE TITLE
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [cassandra error] Error during migration 2017-01-24-132600_upstream_timeouts_2: [Read timeout] Operation timed out - received only 0 responses.

### ISSUE THREAD

**Issue by kdp117** [Kong/kong#3392]
NOTE: GitHub issues are reserved for bug reports only.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

Getting below error while running kong migrations up for brand new environment.

```
Error:
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [cassandra error] Error during migration 2017-01-24-132600_upstream_timeouts_2: [Read timeout] Operation timed out - received only 0 responses.
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: in function 'cmd_exec'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
        /usr/local/bin/kong:7: in function 'file_gen'
        init_worker_by_lua:41: in function <init_worker_by_lua:39>
        [C]: in function 'xpcall'
        init_worker_by_lua:48: in function <init_worker_by_lua:46>

```

### Additional Details & Logs

- Kong version - 0.11.2
- Operating System - Redhat Linux 7.4

Cassandra Error:

```
java.lang.RuntimeException: Unknown column upstream_read_timeout during deserialization
        at org.apache.cassandra.db.Columns$Serializer.deserialize(Columns.java:445) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.db.filter.ColumnFilter$Serializer.deserialize(ColumnFilter.java:470) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.db.ReadCommand$Serializer.deserialize(ReadCommand.java:722) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.db.ReadCommand$Serializer.deserialize(ReadCommand.java:659) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.io.ForwardingVersionedSerializer.deserialize(ForwardingVersionedSerializer.java:50) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.net.MessageIn.read(MessageIn.java:123) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessage(IncomingTcpConnection.java:192) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.net.IncomingTcpConnection.receiveMessages(IncomingTcpConnection.java:180) ~[apache-cassandra-3.11.1.jar:3.11.1]
        at org.apache.cassandra.net.IncomingTcpConnection.run(IncomingTcpConnection.java:94) ~[apache-cassandra-3.11.1.jar:3.11.1]

```

**Comment by thibaultcha** [comment]
Closing this due to the 15 days delay without replies. Feel free to re-open @kdp117.

**Comment by pamiel** [comment]
Hi all,
Sorry for commenting on a closed issue, but I had the same issue as @kdp117 and I just found the solution for that.
On my side, it happened on a multi-nodes Cassandra Cluster (3 nodes), with a database that if fully empty (so no link with Cassandra loading or with the number of records in the `apis` table).

Indeed, step `2017-01-24-132600_upstream_timeouts_2` starts with a selection of all rows of the `apis` table (https://github.com/Kong/kong/blob/master/kong/dao/migrations/cassandra.lua#L417). However:
- This comes just after step `2017-01-24-132600_upstream_timeouts` that just altered the same `apis` table
- And the selection is done by directly using a raw `SELECT * FROM apis` query, so not using the DAO layer... so not taking benefit on the "retry on read" policy nor of the "wait schema consensus" provided by this DAO layer.

Working on the issue with a Cassandra DBA, the analysis is that:
- As working on a multi-nodes Cassandra cluster, the table alteration might not have been propagated properly on all nodes when the raw `SELECT *` is run, generating a read error (most probably due to an inconsistency on the schema of the queried node)... and unfortunately, no retry is implemented on this read error as this is a raw query that is done.
- Solution is just to use `local rows, err = dao.apis:find_all()` instead of the `local rows, err = dao.db:query([[ SELECT * FROM apis; ]])`: the schema consensus is obtained and even if a read error occurs, a retry is performed by the DAO layer.

I'm about to submit a PR on that.

Note that retrying the migration was a good workaround as the time elapsed between the 2 migrations attempts gives enough time to Cassandra to apply the table alteration to all nodes => the `SELECT *` can run properly during the second migration attempt.
