### ISSUE TITLE
Routes has no 'name' property

### ISSUE THREAD

**Issue by theashwin007** [Kong/kong#3425]
### Summary

The newly introduced route has no name property to uniquely distinguish the route. This is needed.

### Additional Details

- Kong version (`0.13`)

**Comment by bungle** [comment]
But they have id? Yes, I would add it, but so far we didn't have a case for it. Can you explain your use case?

**Comment by thibaultcha** [comment]
The upcoming support for `PUT` on `/routes/:route_id` (thanks to @bungle in #3416) means that you will be able to define Routes in an idempotent fashion given you chose a UUID for them.

Services have a `name` property because they are meant to represent your own upstream services that you, your team, or your company maintains. I am sure they have a name. We do not see Routes under the same angle, but instead somewhat disposable and likely many of them will be similar or map to the same Services with _slightly_ different routing properties. Unless you come up with your own naming scheme, things could easily become unmanageable, since `name` would need to be unique for the `/routes/:route_name` endpoint to exist.

Given its impracticality and the upcoming `PUT` support to the `/route/:route_id` endpoint, why is "this needed"? Please elaborate your use-case.

Thank you

**Comment by bungle** [comment]
I agree with @thibaultcha, the `name` needs to be unique, but most use cases don't want to name `routes`, so at least I think the name should by by default the same as id then to not violate this unique constraint and not force people naming `routes` when they don't want to or have any names for them.

**Comment by bungle** [comment]
@kwahome so the solution for you would be `PUT`:
https://github.com/Kong/kong/pull/3416 (already merged, will come with `0.14.0`.

The another question is harder to answer as that is hard to support with Cassandra without doing a lot of denormalization (which would require a quite bunch of changes).

**Comment by hishamhm** [comment]
I'm closing this one for now since the create & update issue brought up by @kwahome was addressed by @bungle and the feedback on @theashwin007's feature suggestion has been noted. For discussing possible future features, please join the conversation in [Kong Nation](https://discuss.konghq.com/)!
