### ISSUE TITLE
PATCH on routes findings

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#3458]
### Summary
Will let you decide if you think the Admin API should be able to handle this or not, depending on types of json marshallers you use and how you implement depends on what is created.

For now behavior is this:
```
PATCH https://gateway.com/admin-api/routes/fbebe6c8-e5df-4c36-96d4-2866810a48c9 HTTP/1.1
{
  "strip_path": false
}
```
Works

But if you have an empty service container(which could be used to specify the service id and modify where route points) is empty errors will be thrown:

```
PATCH https://gateway.com/admin-api/routes/fbebe6c8-e5df-4c36-96d4-2866810a48c9 HTTP/1.1
{
  "strip_path": false,
  "service": {
  }
}
```
Throws HTTP/1.1 400 Bad Request:
```
{"fields":{"service":{"id":"missing primary key"}},"name":"schema violation","code":2,"message":"schema violation (service.id: missing primary key)"}
```

Why would an empty container service actually break the patch? Essentially thats like saying don't modify where the route points as I have specified no id. I am using java + gson to produce the JSON and do code like so:

```   
public boolean modifyKongRoute(String routeId,
                                   List<String> hosts,
                                   List<String> methods,
                                   List<String> paths,
                                   Boolean preserveHost,
                                   List<String> protocols,
                                   Boolean stripPath,
                                   String serviceId
                                   )
    {
        RoutesData routesData = new RoutesData();
        routesData.setHosts(hosts);
        routesData.setMethods(methods);
        routesData.setPaths(paths);
        routesData.setPreserveHost(preserveHost);
        routesData.setProtocols(protocols);
        RoutesServiceData routesServiceData = new RoutesServiceData();
        routesServiceData.setId(serviceId);
        routesData.setService(routesServiceData);
        routesData.setStripPath(stripPath);

        String test = gson.toJson(routesData);

        body = RequestBody.create(JSON, gson.toJson(routesData));
        request = new Request.Builder()
                .header("Authorization", "Bearer " + jwt_token)
                .url(base_admin_url + "/routes/" + routeId)
                .patch(body)
                .build();
        try
        {
            response = client.newCall(request).execute();
            if(response != null && response.isSuccessful())
            {
                return true;
            }
            else if(response != null && "401".equals(Integer.toString(response.code())))
            {
                renewJwtToken();
                return modifyKongRoute(routeId, hosts, methods, paths, preserveHost, protocols, stripPath, serviceId);
            }
            else
            {
                return false;
            }
        }
        catch(IOException e)
        {
            System.out.println("ModifyKongRoute" + " Error: " + e.getMessage());
            return false;
        }
    }
```
And setting service id to null still produces the services{} container in the json. Of course I can check null and and avoid including services{} entirely and I am honestly not sure what the standard should be for an API in situations like this. Should it ignore an empty "container" like that or throw invalid? Figured it would be worth a brief look.  

### Steps To Reproduce
1. Create route/service.
2. Try patching your route in a few ways

### Additional Details & Logs
- Kong version Kong 13.1

**Comment by zigoodb** [comment]
At first,you must  create  the service of  data interface (e.g.   restful api data interface)
command format like this:
[root@contoso ~]# curl -i -X POST \
--url http://localhost:8001/services/ \
--data 'name=book' \
--data 'url=http://contoso.com/v1/books'

HTTP/1.1 201 Created
Date: Mon, 07 May 2018 13:58:02 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.1

{
    "host": "contoso.com", 
    "created_at": 1525672682, 
    "connect_timeout": 60000, 
    "id": "a5b8bd64-2a69-42d3-aa9f-031a912cc89e",         //  id of the book service
    "protocol": "http", 
    "name": "book", 
    "read_timeout": 60000, 
    "port": 80, 
    "path": "/v1/books", 
    "updated_at": 1525672682, 
    "retries": 5, 
    "write_timeout": 60000
}


The second ,add a route of the book service,(keynote is the value of the paths[] in this route, you must make the value of the paths[]  is consistent with "/v1/books" in the book service url )
There is a one to many relationship between the book service and the route of the book service
[root@contoso ~]# curl -i -X POST \
--url http://localhost:8001/services/book/routes \
--data 'hosts[]=contoso.com' \
--data 'paths[]=/v1/books'

HTTP/1.1 201 Created
Date: Mon, 07 May 2018 13:58:44 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.1

{
    "created_at": 1525672724, 
    "strip_path": true, 
    "hosts": [
        "contoso.com"
    ], 
    "preserve_host": false, 
    "regex_priority": 0, 
    "updated_at": 1525672724, 
    "paths": [
        "/v1/books"
    ], 
    "service": {
        "id": "a5b8bd64-2a69-42d3-aa9f-031a912cc89e"
    }, 
    "methods": null, 
    "protocols": [
        "http", 
        "https"
    ], 
    "id": "63eaa9de-1ae9-4b60-baab-171246406b48"  // {route_id} = id
}

How to edit the route of the book service ?
1.  Query the route list of the book service according to the name of the book service
[root@contoso ~]# curl -i -X GET \
--url http://localhost:8001/services/book/routes

{
    "next": null, 
    "data": [
        {
            "created_at": 1526201262, 
            "strip_path": true, 
            "hosts": null, 
            "preserve_host": false, 
            "regex_priority": 0, 
            "updated_at": 1526201262, 
            "paths": [
                "/v1/books"
            ], 
            "service": {
                "id": "a5b8bd64-2a69-42d3-aa9f-031a912cc89e"
            }, 
            "methods": null, 
            "protocols": [
                "http", 
                "https"
            ], 
            "id": "63eaa9de-1ae9-4b60-baab-171246406b48"    // {route_id} = id
        }
    ]
}

2.  By default, we do not specify methods[] parameters. The routing of book services is allowed for all    Method type requests.
Now let me give you an example of how to modify the methods[] parameter, only allowing users to add new book record to modify book record and get a book/books list to operate.
URL Format:  http://localhost:8001/routes/ {route_id}
[root@contoso ~]# curl -i -X PATCH \
--url http://localhost:8001/routes/63eaa9de-1ae9-4b60-baab-171246406b48 \
--data 'methods[]=GET&methods[]=POST&methods[]=PUT'

{
    "created_at": 1526201262, 
    "strip_path": true, 
    "hosts": null, 
    "preserve_host": false, 
    "regex_priority": 0, 
    "updated_at": 1526232871, 
    "paths": [
        "/v1/books"
    ], 
    "service": {
        "id": "a5b8bd64-2a69-42d3-aa9f-031a912cc89e"
    }, 
    "methods": [
        "GET", 
        "POST", 
        "PUT"
    ], 
    "protocols": [
        "http", 
        "https"
    ], 
    "id": "63eaa9de-1ae9-4b60-baab-171246406b48"
}

Like this set  methods[]=NULL, but  the modified methods[] value is equal to ["NULL"], which is still different from the default key value to methods:null because I'm busy, and I don't have time to continue the experiment terminal command how to set up the null value. If you can't restore the methods:null, first we can delete the  route of the book service and then create a new route of the book service.

My suggestion is that you should first master the Kong Gateway terminal command line management interface and then write the code.

It's the first to create book service and then the route that can create book service can't play like you - -- ID of the book service is the value of null, which is wrong.

I am able to express my English level. I hope you can understand my meaning.

**Comment by zigoodb** [comment]
[root@contoso ~]# curl -i -X PATCH \
--url http://localhost:8001/routes/49b248f1-1646-463e-8e6c-80e8770e2fcc \
--data 'methods[]=NULL'

HTTP/1.1 200 OK
Date: Mon, 14 May 2018 01:53:48 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.1

{
    "created_at": 1526201262, 
    "strip_path": true, 
    "hosts": null, 
    "preserve_host": false, 
    "regex_priority": 0, 
    "updated_at": 1526234028, 
    "paths": [
        "/v1/books"
    ], 
    "service": {
        "id": "a5b8bd64-2a69-42d3-aa9f-031a912cc89e"
    }, 
    // why not is "methods":null ,please all developers of Kong explain this
    "methods": [
        "NULL"
    ], 
    "protocols": [
        "http", 
        "https"
    ], 
    "id": "63eaa9de-1ae9-4b60-baab-171246406b48"
}

**Comment by zigoodb** [comment]
I'm sorry, the command line above is wrong，the right is 
[root@contoso ~]# curl -i -X PATCH
--url http://localhost:8001/routes/63eaa9de-1ae9-4b60-baab-171246406b48 \
--data 'methods[]=NULL'

**Comment by zigoodb** [comment]
At the end of each line of the command, there is a backslash “\”, without leaving spaces or any other invisible characters.

**Comment by zigoodb** [comment]
The browser on the client side of the macOS system can penetrate the Whitelist IP Restriction,
none of all the developers to look at my question because I sent the Chinese blog,
but you don't have to understand Chinese, it doesn't matter.
And you can test out macOS's browsers'  Whitelist IP Restriction is penetrated really 
by submitting the command line in my order.
Kong Gateway - 13 基于网关服务的IP白名单限制访问（Whitelist IP Restriction）
https://blog.csdn.net/zhengzizhi/article/details/80286462

I hope the developers of Kong can notice the question above which I had sent.

**Comment by jeremyjpj0916** [comment]
@zigoodb why are you using my git issue which is simply pointing out a small PATCH question/possible bug to discuss your current problem lol. Probably not the best approach to to get support. Also I am having trouble with the language barrier I believe. And honestly I think security around whitelisting/blacklisting IP's is a terrible approach and should not be used. If you want to protect your gateway from a malicious attacks you need a serious WAF solution embedded in Kong or fronting Kong.

**Comment by bungle** [comment]
Empty container meaning can be debated. It could mean:

1. If require like it is, an error
2. If not required, also error
3. If not required, set null
4. If required, no validation error, try to set null, return foreign key violation error
5. If not required and given empty, ignore
6. If required and given empty, ignore

Also debending on method and endpoint the decision what to do may be different. Also we need to support both JSON and url-encoded that may need to be considered here as well.

**Comment by jeremyjpj0916** [comment]
Right those 6 make sense, but you say its(service? or service.id?) required right now as Case 1? It can't be case 1 right now right since service is not required (or maybe you mean service.id is required if service exists which would then make more sense)? Because the route PATCH lacking the service json block entirely is what works if a service.id is not specified. If you believe it to be as it should I will make sure to implement my code in a way to not pass json with empty references and close this issue. Becomes more of just me clarifying yalls stance here :) .

**Comment by bungle** [comment]
I haven't thought about it a lot. With new model we decided that foreign key relationships are send as object (in json), e.g. `"service": { "id": "<uuid>" }` and with `application/x-www-form-url-encoded` is is passed as `service.id` which will create same object as when passing that JSON. For JSON we don't do any processing anymore.

`service` is pretty much same as `service.id` in admin api, there is no `service´ only these objects. Why objects, is because that's why we can support composite keys as well. Though not sure if going with all entities have `id` (`uuid`) and `name` (`unique index`) would have been better, at least it would have made code a lot easier. Using object also gives possibility to use DAO so that you first e.g. retrieve `service` then you update `route` by passing the whole `service` object to it as `service` attribute.

So when you have a `route` it needs to have `service` where it belongs. So that foreign key relationship is required. Now when you patch, the patch is partial update. You send values and we will update it. If you send empty structure our code thinks that well, you might want to update that (e.g. change the service on which route resides), and so we validate that parameter. Because it does not validate we give you an error. Because your route already has `service` you can skip sending that parameter with `PATCH`. But with `PUT` you need to send it as `PUT` will not use any values from the old one except the identifier.

**Comment by jeremyjpj0916** [comment]
Gotcha! I think we can mark this as closed then. As always thanks for the dialog and input.

**Comment by bungle** [comment]
And the above is just reasoning why it works how it works. I am not sure if it makes it any better to implement `5.` and `6.`. For me it kinda makes exception from other validations, maybe too much magic, especially because the semantics of such is not really something people generally agree. So giving an error is quite clear. If you want to have this discussion going, it is okay to me to reopen, but I think I will consult fellow core team members what they think about, especially @hishamhm who wrote the `schema` for new model.

**Comment by thibaultcha** [comment]
The decision here is deliberate and the behavior/error explicit enough to not warrant a revisit imho.

**Comment by zffocussss** [comment]
hi you can use patch to clean a single conf key.

curl -i -X PATCH \
  --url http://localhost:8001/services/static \
  --data 'host=xxx' \
  --data 'protocol=https' \
  --data 'port=443' \
  --data 'path='

in this case,you can make service named "static" discard the "path" settings
