### ISSUE TITLE
URI matching issue

### ISSUE THREAD

**Issue by Simbafa** [Kong/kong#3483]
Two apis are created as following:
1. api1 ==> uris: /
2. api2 ==> uris: /aa

When "http://host/aaaa/index.html" is browsed, the matched api is api2.

**Comment by thibaultcha** [comment]
Hi,

This is expected behaviour. Defining `uris` like so treats them as prefixes, and `/aa` _is_ a prefix of `/aaaa`.

For more details, see https://getkong.org/docs/latest/proxy/#request-path

> When proxying with path prefixes, the longest paths get evaluated first. This allow you to define two Routes with two paths: /service and /service/resource, and ensure that the former does not "shadow" the latter.

Alternatively, you can use regexes to enforce `/aaaa` does not match:
```
$ curl -i -X POST http://localhost:8001/apis \
    --data-urlencode 'uris=^\/aa\/'
```

By the way, APIs are deprecated since Kong 0.13.0. I am not sure which version of Kong you are using, but you can check the documentation for Services & Routes at: https://getkong.org/docs/0.13.x/admin-api/#service-object

**Comment by Simbafa** [comment]
Thank you very much!
