### ISSUE TITLE
kong 0.13 plugin not loaded

### ISSUE THREAD

**Issue by videni** [Kong/kong#3528]
I try to install [kong-influxdb](https://github.com/videni/kong-influxdb)  as following steps

luarocks install 

luarocks list | grep influxdb

> kong-influxdb

I can see kong-influxdb is installed to luarocks tree.

vim /etc/kong/kong.conf
```
customer_plugins = kong-influxdb
log_level = debug  
```

kong reload -vvv

> 2018/06/11 06:39:02 [verbose] Kong: 0.13.1
> 2018/06/11 06:39:02 [verbose] reading config file at /usr/local/kong/.kong_env
> 2018/06/11 06:39:02 [verbose] prefix in use: /usr/local/kong
> 2018/06/11 06:39:02 [verbose] preparing nginx prefix directory at /usr/local/kong
> 2018/06/11 06:39:02 [info] Kong reloaded

however kong-influxdb is not reloaded.

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

Regarding your query: try `custom_plugins=...` instead of `customer_plugins=...`.

I'll close this issue now. If you think this was closed in error, then please reopen.
