### ISSUE TITLE
[Question] APIs authentication and JWT token validation with KONG

### ISSUE THREAD

**Issue by yakhyadabo** [Kong/kong#3552]
I plan to use Kong in our project. I'm currently working on a POC to see how we can integrate it in our platform as the main API gateway. I also want to use the JWT plugin for authentication and authorization. I know that all the API calls should go through the Kong gateway to be authenticated. Then, if the authentication is validated they can go to the API.

****Clients ---> Kong gateway ----> Apis****

The part that is not very clear in my mind is how the APIs and Kong fit together.

1. Imagine a scenario where a client tries to call directly an API with a token (bypassing the Gateway). How can the API use Kong to validate this token?

2. How does Kong authenticate the APIs (not the Client)? In the examples I have seen so far, only the authentication of the clients is documented, not the authentication of the APIs that are "protected" by Kong.

**Comment by jeremyjpj0916** [comment]
1. API's dont use Kong to validate the JWT, the JWT is validated within Kong and API Providers get extra http headers injected from Kong with the consumer username/id associated to that jwt, API Providers don't have to care about the way the client authenticated(if its oauth2/jwt or whatever, they care about the headers kong sends of who the client is). 

2. API Provider<-> Kong security is not really discussed much in the documentation, out of the box you can use Mutual TLS to a degree see my topic here for a few updates I think Kong needs a few tweaks to get the best configs for Mutual TLS https://github.com/Kong/kong/issues/3047 we went with an alternative for now since nobody likes mutual tls due to cert management pains(biased opinion here). So another way would be something like https://github.com/Optum/kong-upstream-jwt , where you pass back a totally separate JWT (don't confuse with the client->kong jwt authentication) in the headers API Providers can validate to prove the transaction came from gateway and payload was not manipulated.

**Comment by coopr** [comment]
Good feedback @jeremyjpj0916 !

On question #1, I'll add that you would probably want to configure DNS and networking rules so that it is **not possible** for a client to directly call an API service, bypassing the gateway. In this arrangement, Kong is *the* gateway, the gate through which *all* traffic flows. Arranging things in this manner is what gets you many of the benefits of an API gateway. 

I'll close this issue now, as we reserve Github Issues for bug reports only. For further discussion of Kong, please join us at [Kong Nation](https://discuss.konghq.com)
