### ISSUE TITLE
[Admin API] get /consumers/ does not return 'total' field

### ISSUE THREAD

**Issue by liyuntao** [Kong/kong#3602]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

list consumers api does not return `total` field as older version does, also inconsistent with the current document. This may break some dashboard project.

### Additional Details & Logs

- Kong version 0.14.0

**Comment by bungle** [comment]
@liyuntao Total is dropped from new DB for now mainly because it is currently not that easy to count totals with Cassandra. We may get it back in future but won't promise. For some entities it might make sense, but consumer is an example where it can get ugly with Cassandra or we need to store the and maintain counts in other keys).

Thank you for reminding us to fix the docs.

**Comment by gjedeer** [comment]
In 0.14, the "total" field is misleadingly set to 0 when there is data present. Maybe at least the field could be removed, so that tests relying on this field would fail?

**Comment by JoshTheGoldfish** [comment]
I'm working on fixing this here: https://github.com/Kong/docs.konghq.com/pull/852
