### ISSUE TITLE
Kong migrations up fails on 0.14

### ISSUE THREAD

**Issue by jithu21** [Kong/kong#3637]
### Summary
Unable to do migrations up on kong 0.14

### Steps To Reproduce

1. I am on kong 0.10 and I am trying to upgrade to 0.14
2. I installed 0.14
3. Did kong migrations up -c /etc/kong/kong.conf
4. Getting errors .
```
migrating core for database kongdb
Error: bad argument #1 to 'decode' (string expected, got table)

  Run with --v (verbose) or --vv (debug) for more details
```
### Additional Details & Logs

 Kong version 0.10
 Kong debug-level startup logs
 Operating system Ubuntu 16.04

**Comment by hishamhm** [comment]
@jithu21 0.10 was released over a year ago (there have been 14 releases since!). Kong is evolving fast, and migrating from very old releases can be problematic due to internal architectural changes. Your safest bet is to do a step-wise migration through the latest release of each 0.x series. So try migrating to 0.10.4, then 0.11.2, then 0.12.3, then 0.13.1, then 0.14.0.
