### ISSUE TITLE
Migrations error when updating kong from 0.10 to 0.14 using Cassandra as database

### ISSUE THREAD

**Issue by Christophe-Ploujoux** [Kong/kong#3664]
When we launch migrations command on a freshly created cassandra keyspace we see this error :
`/usr/local/share/lua/5.1/kong/cmd/migrations.lua:37: [cassandra error] Error during migration 2018-03-27-002500_drop_old_ssl_tables: [Invalid] Index 'ssl_servers_names_ssl_certificate_id_idx' could not be found in any of the tables of keyspace 'xxxxxxxxx'`

I think we can get rid of this error by changing these lines : 
https://github.com/Kong/kong/blob/0.14.0/kong/dao/migrations/cassandra.lua:L744
`
up = [[
      DROP INDEX ssl_servers_names_ssl_certificate_id_idx;
      DROP TABLE ssl_certificates;
      DROP TABLE ssl_servers_names;
    ]]
`

to

`
up = [[
      DROP INDEX IF EXISTS ssl_servers_names_ssl_certificate_id_idx;
      DROP TABLE IF EXISTS ssl_certificates;
      DROP TABLE IF EXISTS ssl_servers_names;
    ]]
`

### Steps To Reproduce

1. Launch Kong v0.10 (it will launch migrations with command start) on Cassandra Keyspace: kong_v_0_10
2. Launch migrations with a Kong v0.14 on Cassandra Keyspace: kong_v_0_14

**Comment by p0pr0ck5** [comment]
Migrations/upgrade paths are generally meant to be following release-by-release (that is, upgrade from 0.10 -> 0.11, 0.11 -> 0.12, etc). There are breaking changes between each release that are not accounted for at the distance you're considering here, and I suspect such behavior will not be supported in the future either (this discussion has come up here in the past).

**Comment by thibaultcha** [comment]
@Christophe-Ploujoux Hi,

You are welcome to contribute these changes in a PR if you wish to. Please first have a look at our [CONTRIBUTING.md](https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#submitting-a-patch) file :)

In the future, we will try to actively plan and communicate supported upgrade paths between releases with migrations (including jumps in major versions). For now, it really depends on which versions you are upgrading from/to, and deserves careful study of said migrations.

Thanks!

**Comment by pamiel** [comment]
Sorry to re-open the track, but I'm facing some sporadic appearance of the exact same error mentioned by @Christophe-Ploujoux during a migration, either from scratch (new keyspace), or from an existing keyspace corresponding to a Kong 0.12 version (I did not try from another version).

While the correction of @Christophe-Ploujoux might work (not tested, but I guess it should), the reason of my post here is that the faulty dropping of the index is done in the `down` section of the migration, and not in the `up` section, i.e. in a piece of code that should normally _not_ be executed at all when running a `migration up`, isn't it ?
I would be happy to push a PR to solve the issue, but there is something I don't understand here !

**Comment by pamiel** [comment]
Sorry, my bad reading:
- the `up` section of migration `2018-03-27-002500_drop_old_ssl_tables` really contains the `DROP INDEX ssl_servers_names_ssl_certificate_id_idx;` (https://github.com/Kong/kong/blob/0.14.1/kong/dao/migrations/cassandra.lua#L745), but note the end of the index name: `_id_idx`
- this is indeed migration `2016-12-14-172100_move_ssl_certs_to_core` that has a `down` section doing a `DROP INDEX ssl_servers_names_ssl_certificate_idx;` (https://github.com/Kong/kong/blob/0.14.1/kong/dao/migrations/cassandra.lua#L266)... but note the end of the index name here: `_idx` only

I consequently think there is a bug in `2016-12-14-172100_move_ssl_certs_to_core.down` because the name of the index in the `DROP` looks not good... but unfortunately, that does not solve the initial issue that is still present in `2018-03-27-002500_drop_old_ssl_tables.up` :(
