### ISSUE TITLE
Kong+ScyllaDB: could not execute insertion query: [Server error] Not implemented: LWT

### ISSUE THREAD

**Issue by mrusme** [Kong/kong#3695]
### Summary

When trying to add a consumer (`POST http://localhost:8001/consumers`, body `'{"custom_id":"00000000-0000-0000-0000-000000000000","username":"00000000-0000-0000-0000-000000000000"}' }`), Kong responds with a `400 Bad Request` and some additional info:

```
{ message:
      'could not execute insertion query: [Server error] Not implemented: LWT' } }
```

I'm not sure whether @penberg's [statement](https://github.com/scylladb/scylla/issues/2727#issuecomment-324535315) is still valid, but if so, it could be that @scylladb does not support this call that Kong seems to try to make. However, there might be a workout to it, maybe?

### Steps To Reproduce

1. Set up Kong to use ScyllaDB ([here](https://hub.docker.com/r/paperworkco/service-kong/) and [here](https://github.com/twostairs/paperwork/blob/master/docker-compose.yml#L62))
2. Run the following curl against Kong:

```bash
curl -X "POST" "http://localhost:8001/consumers" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "custom_id": "00000000-0000-0000-0000-000000000000",
  "username": "00000000-0000-0000-0000-000000000000"
}'
```

### Additional Details & Logs

- Kong version: 0.14.0

**Comment by thibaultcha** [comment]
@mrusme Thanks for bringing this to the attention of #754. It seems like ScyllaDB does not yet support lightweight transactions (https://github.com/scylladb/scylla/issues/2727), a feature that Kong uses since 0.13.0 (for Services and Routes), and 0.14.0 for Consumers. More such entities, including our upcoming new migrations mechanism, will use lightweight transactions in the future.

This does seem like an issue for the ScyllaDB team to tackle, not Kong, unfortunately.

**Comment by thibaultcha** [comment]
Closing this and keeping the discussion in #754; since this isn't an actionable item for us.
