### ISSUE TITLE
Keepalive to Kubernetes Edge Routes causing Incorrect Routing

### ISSUE THREAD

**Issue by rsbrisci** [Kong/kong#3788]
### Summary
Our Kong has several separate services that route to a RedHat kubernetes re-skin called Openshift Origin (OSO).

The way OSO works, is that edge routes are defined for the separate services hosted on it - that all resolve to the same IP (OSO Router). The way the router determines which pod to send traffic to, is via the HTTP HOST Header.

So:
```
curl https://myapp.oso.company.com - routes to myapp pod
curl https://theirapp.oso.company.com - routes to theirapp pod
```

But
```
nslookup myapp.oso.company.com = 10.0.0.1
nslookup theirapp.oso.company.com = 10.0.0.1
```

so if I wanted to use the IP to make the call, I’d do this:
```
curl https://10.0.0.1/ -H "Host: myapp.oso.company.com"
curl https://10.0.0.1/ -H "Host: theirapp.oso.company.com"
```

The problem is this: **When the proxy for myapp.oso has >5tps, Kong will sometimes send traffic for the theirapp proxy to the myapp.oso upstream**. When we disable ngx upstream keepalives, the issue is resolved.

My theory, is that because Keepalives are maintained as a IP:PORT pair, and we are sending to the same IP:PORT for both myapp and theirapp - Kong is re-using the socket for myapp which was for theirapp's traffic.

There is nothing in the logs, even at the most detailed - when this occurs.

### Steps To Reproduce

1. Create two services on Kubernetes with SSL edge routes and create proxies for them on Kong
2. Send >5tps traffic to one of them
3. Test calls against the other, from the same kong cluster

### Additional Details & Logs

- Kong version: 0.14.1
- Kong debug-level startup logs (`$ kong start --vv`) - DEBUG LOGS DO NOT SHOW ANYTHING
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) - ERROR LOGS DO NOT SHOW ANYTHING
- Kong configuration (the output of a GET request to Kong's Admin 
```json
{
  "plugins": {
    "enabled_in_cluster": [
      "acl",
      "request-size-limiting",
      "oauth2",
      "kong-path-based-routing",
      "cors",
      "kong-oidc-auth",
      "rate-limiting",
      "kong-upstream-jwt",
      "kong-oidc-multi-idp",
      "kong-spec-expose",
      "jwt",
      "request-termination",
      "kong-cluster-drain",
      "statsd",
      "correlation-id",
      "kong-splunk-log"
    ],
    "available_on_server": {
      "kong-path-based-routing": true,
      "kong-spec-expose": true,
      "kong-cluster-drain": true,
      "correlation-id": true,
      "kong-splunk-log": true,
      "jwt": true,
      "cors": true,
      "rate-limiting": true,
      "kong-oidc-auth": true,
      "kong-upstream-jwt": true,
      "request-size-limiting": true,
      "request-termination": true,
      "kong-oidc-multi-idp": true,
      "kong-service-virtualization": true,
      "request-transformer": true,
      "acl": true,
      "statsd": true,
      "oauth2": true
    }
  },
  "tagline": "Welcome to kong",
  "configuration": {
    "plugins": [
      "request-transformer",
      "kong-service-virtualization",
      "kong-cluster-drain",
      "kong-upstream-jwt",
      "kong-splunk-log",
      "kong-spec-expose",
      "kong-oidc-auth",
      "kong-path-based-routing",
      "kong-oidc-multi-idp",
      "correlation-id",
      "oauth2",
      "statsd",
      "jwt",
      "rate-limiting",
      "acl",
      "request-size-limiting",
      "request-termination",
      "cors"
    ],
    "admin_ssl_enabled": false,
    "lua_ssl_verify_depth": 3,
    "trusted_ips": {
      
    },
    "lua_ssl_trusted_certificate": "\/usr\/local\/kong\/ssl\/kongcert.pem",
    "loaded_plugins": {
      "kong-path-based-routing": true,
      "kong-spec-expose": true,
      "kong-cluster-drain": true,
      "correlation-id": true,
      "kong-splunk-log": true,
      "jwt": true,
      "cors": true,
      "kong-oidc-multi-idp": true,
      "kong-oidc-auth": true,
      "kong-upstream-jwt": true,
      "acl": true,
      "oauth2": true,
      "statsd": true,
      "kong-service-virtualization": true,
      "request-transformer": true,
      "request-size-limiting": true,
      "rate-limiting": true,
      "request-termination": true
    },
    "cassandra_username": "xxx",
    "admin_ssl_cert_csr_default": "\/usr\/local\/kong\/ssl\/admin-kong-default.csr",
    "ssl_cert_key": "\/usr\/local\/kong\/ssl\/kongprivatekey.key",
    "dns_resolver": {
      
    },
    "pg_user": "kong",
    "mem_cache_size": "1024m",
    "cassandra_data_centers": [
      "dc1:2",
      "dc2:3"
    ],
    "nginx_admin_directives": {
      
    },
    "cassandra_password": "******",
    "custom_plugins": {
      
    },
    "pg_host": "127.0.0.1",
    "nginx_acc_logs": "\/usr\/local\/kong\/logs\/access.log",
    "proxy_listen": [
      "0.0.0.0:8000",
      "0.0.0.0:8443 ssl http2"
    ],
    "client_ssl_cert_default": "\/usr\/local\/kong\/ssl\/kong-default.crt",
    "ssl_cert_key_default": "\/usr\/local\/kong\/ssl\/kong-default.key",
    "dns_no_sync": false,
    "db_update_propagation": 5,
    "nginx_err_logs": "\/usr\/local\/kong\/logs\/error.log",
    "cassandra_port": 9042,
    "dns_order": [
      "LAST",
      "SRV",
      "A",
      "CNAME"
    ],
    "dns_error_ttl": 1,
    "headers": [
      "latency_tokens"
    ],
    "dns_stale_ttl": 4,
    "nginx_optimizations": true,
    "database": "cassandra",
    "pg_database": "kong",
    "nginx_worker_processes": "auto",
    "lua_package_cpath": "",
    "admin_acc_logs": "\/usr\/local\/kong\/logs\/admin_access.log",
    "lua_package_path": ".\/?.lua;.\/?\/init.lua;",
    "nginx_pid": "\/usr\/local\/kong\/pids\/nginx.pid",
    "upstream_keepalive": 120,
    "cassandra_contact_points": [
      "xxx",
      "xxx",
      "xxx",
      "xxx",
      "xxx",
      "xxx"
    ],
    "admin_access_log": "off",
    "client_ssl_cert_csr_default": "\/usr\/local\/kong\/ssl\/kong-default.csr",
    "proxy_listeners": [
      {
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8000,
        "http2": false,
        "listener": "0.0.0.0:8000"
      },
      {
        "ssl": true,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8443,
        "http2": true,
        "listener": "0.0.0.0:8443 ssl http2"
      }
    ],
    "proxy_ssl_enabled": true,
    "proxy_access_log": "off",
    "ssl_cert_csr_default": "\/usr\/local\/kong\/ssl\/kong-default.csr",
    "enabled_headers": {
      "latency_tokens": true,
      "X-Upstream-Status": false,
      "X-Proxy-Latency": true,
      "server_tokens": false,
      "Server": false,
      "Via": false,
      "X-Upstream-Latency": true
    },
    "cassandra_ssl": true,
    "cassandra_local_datacenter": "ELR",
    "db_resurrect_ttl": 30,
    "db_update_frequency": 5,
    "cassandra_consistency": "LOCAL_QUORUM",
    "client_max_body_size": "1000m",
    "admin_error_log": "\/dev\/stderr",
    "pg_ssl_verify": false,
    "dns_not_found_ttl": 30,
    "pg_ssl": false,
    "cassandra_repl_factor": 1,
    "cassandra_lb_policy": "RequestDCAwareRoundRobin",
    "cassandra_repl_strategy": "SimpleStrategy",
    "nginx_kong_conf": "\/usr\/local\/kong\/nginx-kong.conf",
    "error_default_type": "text\/plain",
    "nginx_http_directives": {
      
    },
    "real_ip_header": "X-Real-IP",
    "kong_env": "\/usr\/local\/kong\/.kong_env",
    "cassandra_schema_consensus_timeout": 10000,
    "dns_hostsfile": "\/etc\/hosts",
    "admin_listeners": [
      {
        "ssl": false,
        "ip": "0.0.0.0",
        "proxy_protocol": false,
        "port": 8001,
        "http2": false,
        "listener": "0.0.0.0:8001"
      }
    ],
    "ssl_ciphers": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",
    "ssl_cert": "\/usr\/local\/kong\/ssl\/kongcert.crt",
    "prefix": "\/usr\/local\/kong",
    "admin_ssl_cert_key_default": "\/usr\/local\/kong\/ssl\/admin-kong-default.key",
    "cassandra_ssl_verify": true,
    "db_cache_ttl": 0,
    "ssl_cipher_suite": "modern",
    "real_ip_recursive": "off",
    "proxy_error_log": "\/dev\/stderr",
    "client_ssl_cert_key_default": "\/usr\/local\/kong\/ssl\/kong-default.key",
    "nginx_daemon": "off",
    "anonymous_reports": false,
    "cassandra_timeout": 5000,
    "nginx_proxy_directives": {
      
    },
    "pg_port": 5432,
    "log_level": "notice",
    "client_body_buffer_size": "20m",
    "client_ssl": false,
    "lua_socket_pool_size": 30,
    "admin_ssl_cert_default": "\/usr\/local\/kong\/ssl\/admin-kong-default.crt",
    "cassandra_keyspace": "kong_stage",
    "ssl_cert_default": "\/usr\/local\/kong\/ssl\/kong-default.crt",
    "nginx_conf": "\/usr\/local\/kong\/nginx.conf",
    "admin_listen": [
      "0.0.0.0:8001"
    ]
  },
  "version": "0.14.1",
  "node_id": "3a7824e4-2971-4daa-9351-c05293b26f04",
  "lua_version": "LuaJIT 2.1.0-beta3",
  "prng_seeds": {
    "pid: 30": 121842322351,
    "pid: 37": 205914716415,
    "pid: 36": 619910823160,
    "pid: 35": 158818822910,
    "pid: 33": 106581771972,
    "pid: 34": 119182521233,
    "pid: 31": 230127232253,
    "pid: 32": 194211052318
  },
  "timers": {
    "pending": 4,
    "running": 0
  },
  "hostname": "kong-186-txzsv"
}
```
- Operating system: Alpine Linux kong-186-txzsv 3.10.0-693.el7.x86_64

**Comment by jeremyjpj0916** [comment]
Update around some of this since it also impacts 1.0+ and I think I have a better understanding of whats happening:

So the real problem here is NGINX not granular enough with its directives to allow things to allow more customization. I believe this can be fixed at the lua level though and Kong team may know the best place for these changes to live:

Based on discussions around:
https://discuss.konghq.com/t/routing-issues-when-sending-to-multiple-kubernetes-pods/1880/10 
And here:
https://github.com/ledgetech/lua-resty-http/issues/170#issuecomment-455995266 

I think the conclusion is that NGINX with the upstream directive and keepalive directive is managing which tcp connection to reuse based on just IP:PORT, when with a little granularity in lua  land we may be able to produce better keepalive settings in Kong API Gateway that what default NGINX gives.

My question to Kong experts would be as such, knowing that there is a tcp socket option "pool":
"
pool specify a custom name for the connection pool being used. If omitted, then the connection pool name will be generated from the string template "<host>:<port>" or "<unix-socket-path>".
"

```
upstream kong_upstream {
    server 0.0.0.1;
    balancer_by_lua_block {
        Kong.balancer()
    }
> if upstream_keepalive > 0 then
    keepalive ${{UPSTREAM_KEEPALIVE}};
> end
}
```

And we have the hostname in question within the Kong balancer ctx in the "balancer_by_lua_block", is there a way to use and set keepalive on an upstream based on hostname:port where different hostnames resolve to the same IP(In case of routing to a LB fronting a cloud)? This will make Kong keepalives function safely for all use cases as opposed to only use cases where upstreams all have different IPs.

Its very easy to produce the problem internally proxying to our private cloud with 1 ip that relies on hostname routing(where keepalives occur on private cloud ingress so that reused tcp connection with Kong goes to the wrong application pods).

I am thinking something like this in sudo code(its dead wrong because I am not exactly sure how to do this specifically) as a dirty test just so I can confirm to Kong this indeed does fix it:
```
upstream kong_upstream {
    server 0.0.0.1;   #is this just instantiating a server directive so Kong.balancer() can manipulate it and adjust settings properly or is it required to exist in the upstream directive as a dummy value?
    balancer_by_lua_block {
        Kong.balancer()
        #custom keepalive lua logic here
       --Initialize and do the tcp socket connection settings here with "pool" potentially equal to the kong service iduuid, or hostname set in service:port???
        -- Set keepalive on the tcp socket here in lua set to the ${{UPSTREAM_KEEPALIVE}}
    }
> if upstream_keepalive > 0 then
    #keepalive ${{UPSTREAM_KEEPALIVE}}; Disable nginx keepalive directive since done in lua land
> end
}
```

Maybe its not that easy @thibaultcha , but I figure you of all people would have some ideas, is the upstreams directive the location where the tcp socket connection can be established and is that the ideal location we could tweak how keepalive to the upstreams will work in Kong? Besides the dynamic configuration changes at scale under load that bungle has attempted to remedy as best he can under current architecture, this keepalive behavior Kong has shown has proven problematic. With both fixed this in my mind becomes the ideal flexible gateway.

Maybe this isn't something Kong would want as it represents a slight change away from the nginx offerings to trusting in lua land, but I would think its a common use case to have Kong front a private cloud offering(that the cloud itself uses a LB as single IP too) to then route through some HA proxies(kubernetes ingress) to application pods. And when there is keepalive going around from LB to ingress and ingress to its servers, and the way routing works is through different hostnames on that initial tcp connection, then Kong as a client has to pickout the correct active tcp connection for keepalive reuse or simultaneous load to multiple applications on that cloud will route incorrectly picking the wrong tcp connection for reuse.

My hope is that maybe the tweak I am describing is actually more knowing the 1-5 lines of lua code tewaks to make in the upstream section to manage the contexts tcp socket connection and not a bunch of code. If proxy_pass is where the socket management comes in then that would mean Kong can't remedy this without moving away from proxy_pass(which would be very risky change, I hope this is not the case!).

**Comment by jeremyjpj0916** [comment]
Very specifically this should be updated to "Keepalive to Kubernetes Passthrough Routes causing Incorrect Routing"
