### ISSUE TITLE
/cache API Can't use

### ISSUE THREAD

**Issue by maxiaoxian** [Kong/kong#3810]
Why `/cache` Admin API Can't use ? 
```
[root@local12 ~]# curl -i -X GET --url http://127.0.0.1:8001/cache/
HTTP/1.1 405 Not Allowed
Date: Thu, 27 Sep 2018 16:53:46 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.13.1

{"message":"Method not allowed"}
```

[Cache Reference](https://docs.konghq.com/0.13.x/clustering/#interacting-with-the-cache-via-the-admin-api)

**Comment by thibaultcha** [comment]
Hi @maxiaoxian,

As documented in the page you linked to, `GET /cache` is not a valid request. The supported endpoints are:

```
GET/cache/:key
DELETE /cache/:key
DELETE /cache
``` 

Because `DELETE` is the only method supported on the `/cache` endpoint, you are getting this HTTP 405 status code. Kong does not (yet) provide a "high-level overview" of the state of the database cache as you might think when seeing the `/cache` endpoint. Hence, `GET` is not supported on this endpoint. You must query a particular cache key (and you must know how such keys are built before requesting any, which relegates this endpoint to debugging purposes only).

**Comment by maxiaoxian** [comment]
think you so much ,but how to know those keys ?
