### ISSUE TITLE
OAuth2 Token endpoint timing out

### ISSUE THREAD

**Issue by pavanvamsi3** [Kong/kong#3856]
### Summary

/oauth2/token endpoint is throwing `The upstream server is timing out`

### Steps To Reproduce

1. POST a curl request to https://localhost:8443/oauth2/token with 
```
'{"grant_type":"password", "client_id":"sddsdaa", "client_secret":"asfsdasd", "provision_key":"nasda", "authenticated_userid": "1"}'
```

### Additional Details & Logs

- Kong version: 0.13.1
- Ubuntu

**Comment by pavanvamsi3** [comment]
@bungle ping

**Comment by bungle** [comment]
@pavanvamsi3,

Can you please provide a bit more information. It seems like you are sending a HTTP `POST` to `OAuth 2 Plugin`  `Token Endpoint`. In that case it shouldn't be proxying to `upstream`. That's why I feel like there might be something wrong with your routes/services/plugins.

Can you show us how did you endup with this situation?

**Comment by pavanvamsi3** [comment]
@bungle Hey, thanks for pointing out. There was an issue with one of my routes.
