### ISSUE TITLE
Service Disappearance

### ISSUE THREAD

**Issue by JJMEI** [Kong/kong#3954]
### Summary
HI, everyone! 
   I use Admin API to create a service and route,  and  i can find them on Kong Dashboard. But The service and route disappear in a minute. 

### Steps To Reproduce

1. create service use Admin API 
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=example-service' \
  --data 'url=http://mockbin.org'
2. create route use Admin API
 curl -i -X POST \
  --url http://localhost:8001/services/example-service/routes \
  --data 'hosts[]=example.com'
3. Then get it 
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: example.com'
4. In a minute again get it 
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: example.com'

Here maybe some error infos
{"message":"no route and no API found with those values"}

### Additional Details & Logs
Kong version 0.14.1

- Operating system

**Comment by jeremyjpj0916** [comment]
I know the Kong K8 ingress may have that behavior if you tried using the admin API directly as opposed to using custom resources, see here:
https://discuss.konghq.com/t/expose-admin-api-in-kong-k8-ingress/2196

If you are using standalone Kong as an API gateway that would be truly perplexing because I run Kong 0.14.1 and have not seen such behavior. I am sure Kong team will need additional debug logs to see if any funny business is going on with your Kong. I recommend to run kong in DEBUG mode and drop those logs in here.

**Comment by p0pr0ck5** [comment]
@JJMEI can you enable debug logging on Kong nodes that are observing this behavior and post that here?

**Comment by p0pr0ck5** [comment]
Closing as stale. If you have more data for us we’ll be happy to take a look and we can reopen this. Thanks!
