### ISSUE TITLE
Query string parameters alphabetically sorted

### ISSUE THREAD

**Issue by avp-101** [Kong/kong#3963]
### Summary

When processing a request, the query string parameters of the request are sorted alphabetically.

### Steps To Reproduce

1. Create a service with a route - example route: "/v1/users"
2. Send request to Kong with some string parameters - example url: http://kong_host/v1/users?b=1&a=2
3. The upstream will get the request as /v1/users?a=2&b=1

###  Additional Details & Logs

- Kong version - 0.14.0

**Comment by avp-101** [comment]
I have the key-auth and acl plugins running on the service.
The issue seems to be caused by the "hide credentials" option on the key-auth plugin.

**Comment by bungle** [comment]
I think the `key-auth` should skip modifying query if the `key` was not in query, but in headers.

**Comment by kikito** [comment]
I confirm that the situation is due to the usage of `hide_credentials` in key-auth. When that option is used, the plugin is expected to clear the credentials from both the query string and the headers, if it exists there.

Headers can be cleared individually, but not query string attributes: when an element needs to be changed, the whole query string must be changed. Hence the alphabetic sorting.

I must ask: Is this really an issue? Query string parameter order is rarely relevant. The only case where I think it can be an issue is when there are repeated arguments.

**Comment by p0pr0ck5** [comment]
From https://tools.ietf.org/html/rfc3986#section-1.2.3:

>  The URI syntax is organized hierarchically, with components listed in order of decreasing significance from left to right.

and

> The generic syntax uses the slash ("/"), question mark ("?"), and number sign ("#") characters to delimit components that are significant to the generic parser's hierarchical interpretation of an identifier.

I can find no reference in any established or accepted RFC that indicates that the order of query params is semantically relevant. It might be worth an adjustment to the plugin which would result in more cost and not deliver a semantically-meaningful result, though I'm not sure.

Also worth noting this has been reported upstream a few times (e.g., https://github.com/openresty/lua-nginx-module/issues/794, though the proposed solution has never been implemented.

**Comment by aehlke** [comment]
> I must ask: Is this really an issue? Query string parameter order is rarely relevant. The only case where I think it can be an issue is when there are repeated arguments.

Sometimes it's not a design decision that Kong users have control over - some 3rd-party APIs for webhooks require order to be preserved.

**Comment by ignacio-ifm** [comment]
Hi @kikito, this can be an issue when the upstream requires hmac authentication with the pseudo header `(request-target)` as in the [draft-cavage-http-signatures-12](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures). Since the order is not preserved, the signature does not match.

The situation would be this: you want to restrict the clients that can call the upstream, hence you use the `key-auth` plugin and `hide_credentials` to not leak the keys to the upstream. If in this case the upstream implements hmac authentication the signature would not be correct because the order of the parameters matter.
