### ISSUE TITLE
can not create Oauth2.0 plugin on a consumer?

### ISSUE THREAD

**Issue by wangxiaotao00** [Kong/kong#4016]
NOTE: GitHub issues are reserved for **bug reports only**. For anything else,
please join the conversation in Kong Nation https://discuss.konghq.com/.

Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version  0.14.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by Tieske** [comment]
We appreciate you took the time to open an issue for this. However, kong github issues are for bug reports only. I'd like to ask you to post this on the [Kong Nation forum](https://discuss.konghq.com/)

That said; authentication plugins cannot be added to consumers. Since we'd need the auth to run to identify the consumer. Catch 22 there.
