### ISSUE TITLE
get home page normal , but other css ang png return 404

### ISSUE THREAD

**Issue by hmtiannan** [Kong/kong#4088]
![image](https://user-images.githubusercontent.com/20086500/49989311-c5a63380-ffb4-11e8-9f43-507e0a4eedc8.png)

![image](https://user-images.githubusercontent.com/20086500/49989332-df477b00-ffb4-11e8-9e55-7cf9d051b71c.png)

![image](https://user-images.githubusercontent.com/20086500/49989356-eff7f100-ffb4-11e8-95e7-005693d7eb4d.png)

waitting online !

**Comment by kidd** [comment]
Hello @hmtiannan,

It looks you created the api with `uris=/api`. then only the calls with those paths will belong to this api (and be proxied).

Also, note that the API entity was deprecated in Kong 0.13.0 and the recommended way is to use [Routes](https://docs.konghq.com/0.14.x/admin-api/#route-object) & [Services](https://docs.konghq.com/0.14.x/admin-api/#service-object).

**Comment by p0pr0ck5** [comment]
Closing this out, thanks to @kidd's answer. If you want Kong to proxy _all_ requests, it would help to create a catch-all Route (e.g., https://docs.konghq.com/1.0.x/proxy/#configuring-a-fallback-route). Otherwise, requests will be handled according to the configured Routes in Kong (the behavior of which is detailed in the previous link).
