### ISSUE TITLE
[request] Edge Caching

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#412]
Supports the local caching of requests to closest geographical location, to improve response times for the client.

example:

Kong machine is in Paris and NY. Client is in Paris. Kong will route and cache the request/response from Kong Paris only, to minimize network latency.

**Comment by thefosk** [comment]
Related to #411

**Comment by monster910** [comment]
Can you clarify what you are requesting?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching

A shared cache inside of Kong or ability to set Cache-Control headers by API to enable private browser cache?

**Comment by Tieske** [comment]
Since edge-caching is available in the enterprise edition, and this issue deals with where the request comes from (which Kong doesn't deal with, but the infrastructure in front of Kong does) I think there is nothing more we can do here.

Can we close this?

**Comment by rishianand06** [comment]
Do we have any update on Edge Caching support in Kong?

Since cache plugins will take care of retrieving the data, but How it will take care of getting responses from the nearest kong node as per the client location, to minimize the latency.

As of now We use static website hosting on S3 for my Single Page Application (SPA Web App), so I can use CloudFront as well to serve the static files on time. 

So the same thing, how I can achieve w.r.t Kong?

**Comment by Tieske** [comment]
unless you do something very specialized, it is not really possible. Usually when a Kong node is hit, you're already in a datacenter somewhere. Kong sits close to the backends. For geo/ip based routing you'd typically use a CDN in front of Kong

**Comment by hbagdi** [comment]
This can be safely closed. `proxy-cache` plugin is OSS and users can do caching using it.
Re inter-node communication for caching, that is unlikely to happen right now. You can share the cache somehow between regions (it is a terrible idea) and then it would be possible out of the box.
