### ISSUE TITLE
How   to combine kong and spring boot security oauth2？

### ISSUE THREAD

**Issue by AI-PaaS** [Kong/kong#4246]
Hello:
    I am using kong as service gateway and the backend services are springboot with spring security oauth2.0(jwt). I browsed the document and found that kong support oauth2.0 too.  I just want to know how to combine the two frame? or i must use one only? thx.

**Comment by p0pr0ck5** [comment]
Hi,

Kong is an API gateway, meaning it proxies request in front of your service and can JWT/OAuth authorization before passing the request to your Spring service. Because GitHub issues are reserved for bug reports and feature requests, I'm going to close this issue; please feel free to open a community discussion at discuss.konghq.com. Thank you!
