### ISSUE TITLE
Kong dbless mode returns 500 Internal server error when using Postman or Curl

### ISSUE THREAD

**Issue by hchoi** [Kong/kong#4497]
Please read the CONTRIBUTING.md guidelines to learn on which channels you can
seek for help and ask general questions:

https://github.com/Kong/kong/blob/master/CONTRIBUTING.md#where-to-seek-for-help

### Summary

When I configure kong with 'dbless-mode', it works find with Chrome/IE browser,
However, when I tried to test the API using 'Postman' or 'curl', it returns 500 Internal Server Error, with Error Message

* DB mode
curl -X GET https://my-service-host/api/v1/auth
unauthenticated request --> expected output

* DB-less mode
curl -X GET https://my-service-host/api/v1/auth
An unexpected error occurred --> ??

### Steps To Reproduce

1. Configure Kong with db-less mode
2. Call API with Chrome browser : works fine
3. Call same API with curl or Postman : 500 Internal Server Error

### Additional Details & Logs
- Kong version (`1,1,1`)
- Kong error logs 
...
- using Chorme 
<IP ADDR> - - [10/Apr/2019:09:09:30 +0000] "GET /api/v1/auth HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"

- Using curl
2019/04/10 09:08:46 [error] 78#0: *13873 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/mesh.lua:219: missing X-Forwarded-Host
stack traceback:
coroutine 0:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/kong/runloop/mesh.lua:219: in function 'rewrite'
        /usr/local/share/lua/5.1/kong/runloop/handler.lua:577: in function 'before'
        /usr/local/share/lua/5.1/kong/init.lua:676: in function 'rewrite'
        rewrite_by_lua(nginx-kong.conf:97):2: in function <rewrite_by_lua(nginx-kong.conf:97):1>, client: 10.60.46.149, server: kong, request: "GET /api/v1/auth HTTP/1.1", host: "my-service-domain"
<IP ADDR> - - [10/Apr/2019:09:08:46 +0000] "GET /api/v1/auth HTTP/1.1" 500 40 "-" "curl/7.37.0"

- Operating system
Official Kong docker container (1.1.1-alpine) on SLES12
* /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

**Comment by pamiel** [comment]
Hi @hchoi,

I Have the same issue, as mentioned here: https://discuss.konghq.com/t/why-my-request-is-considered-as-a-mesh-request/3226.
Up to me, the root cause is that your request (that is a regular API Gateway request) is considered as a Mesh request (but unfortunately I don't know why...) => it is trying to get the `X-Forwarded-Host` header that is usually set by the calling entity in this mode.

On my side, I receive a HTTP 500 error code when curling (as you do, because curl is not setting this Header by default), but not through a Web Browser because I have another reverse proxy in between, and this RP is adding the `X-Forwarded-Host` header...
But still, as the request is considered as a Mesh request, then the plugins deployed on the corresponding Route/Service are not executed => this a blocking issue for me to adopt the 1.1 version :(

**Comment by hchoi** [comment]
Thanks for the immediate reply!
I look forward to use 1.1.2 with DB-less mode :)

Regards,
Hyundeok.
