### ISSUE TITLE
(Request Size Limiting Plugin)Kong 1.x series breaking change from 0.14.x and below behavior

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#4515]
### Summary

https://discuss.konghq.com/t/request-size-limiting-plugin/67

Essentially, the plugin used to let decimal values like .5 mean block requests 1/2 a MB, now the plugin only accepts whole numbers at the moment on > 0.14.x versions. Losing this granularity in the plugin makes it a bit less valuable as many API requests are in the KB range and should be able to be limited as such, 1MB limit is pretty large by many API standards from what I have seen in industry.

### Steps To Reproduce

1. Attempt enabling the request size limiting plugin with a decimal size, say .5
2. Watch it throw error saying expecting an integer now.

### Additional Details & Logs
- Kong version 1.0.3

**Comment by hishamhm** [comment]
I'm pretty sure this was an accidental breakage. We can be conservative about 1.x-series compatibility and restore this functionality in Kong 1.2.0 as a "new feature" in Kong 1.x, or we can interpret that not supporting decimals is really a bug in 1.x (since we did not announce the breaking change in the changelog for 1.0.0) and restore the functionality in Kong 1.1.2. I lean towards the latter.

**Comment by jeremyjpj0916** [comment]
@hishamhm do we want to label this as bug or something? Fear without a 🐛  label or something of the sort, this loss of good functionality for users will be forgotten(less than 1 MB size restrictions).

**Comment by jeremyjpj0916** [comment]
@hishamhm closing this issue, seems yalls commit: https://github.com/Kong/kong/commit/52232f9d59473fd44c15093d8df0553db0e9a258 here added back logic to take control of the payload sizes with granularity, with megabyte being the default as to not breaking change us from earlier Kong 1.x versions where the plugin lost granularity for a bit, good stuff.
