### ISSUE TITLE
Being able to optionally disable logging of "GET /status" in the access logs

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#4531]
Kong provides a `GET /status` endpoint to check for the status of Kong, which should be optionally disabled since it creates lots of noise in the access logs when a client is making frequent requests to it.

**Comment by sudoapt-getclean** [comment]
We have Kong running in kubernetes with datadog and an ALB load-balancing(multi-region so effectively three). All 5 are hitting this endpoint to generate 50 requests per minute per kong instance (we have 2)
50 × 2(hosts) × 60(minutes) × 24(hours) × 30(days) = 4_320_000 
so that's 4 million log lines that we would like to turn off.
