### ISSUE TITLE
HomeBrew Installation Issue

### ISSUE THREAD

**Issue by shrhawk-entertainer** [Kong/kong#4602]
### Summary

Kong command failed to run on mac os

### Steps To Reproduce

1. Follow the steps using https://docs.konghq.com/install/macos/
2. run the command `kong`

### Additional Details & Logs

- brew info kong
kong/kong/kong: stable 1.1.2, HEAD
Open source Microservices and API Gateway
https://docs.konghq.com
/usr/local/Cellar/kong/1.1.2 (1,019 files, 8MB)
- Kong `env: resty: No such file or directory`

**Comment by shrhawk-entertainer** [comment]
<img width="660" alt="Screen Shot 2019-05-12 at 23 13 22" src="https://user-images.githubusercontent.com/30106364/57586179-9bc54e80-750b-11e9-95c7-c1491682350e.png">

**Comment by bungle** [comment]
You should perhaps add `/usr/local/openresty/bin` and `/usr/local/openresty/nginx/sbin` to your `PATH`.

**Comment by muratbagsiz** [comment]
Same problem here with macOs Mojave.

I've updated my PATH with recommended, still same error.

**Comment by i-hardy** [comment]
Same issue here on Mojave 10.14.4, have modfied my PATH as suggested above, no joy.

**Comment by muratbagsiz** [comment]
I found my issue by `kong start --vv` and the issue was;

> OpenResty found at /usr/local/openresty/nginx/sbin/nginx. Kong requires version 1.13.6.2, got 1.15.8.1


I've solved this issue by uninstalling first openrestry then kong, then installing kong again.

After that we should make 
`brew link --overwrite openresty` to override default nginx setting.

@shrhawk-entertainer @i-hardy

**Comment by shrhawk-entertainer** [comment]
this solves the problem @muratbagsiz thanks

**Comment by heliodor** [comment]
@shrhawk-entertainer or someone else, please re-open this issue. It should not have been closed just because a workaround was found. Issue needs to be fixed.

The installation docs or the installer need to be fixed so that this issue never arises while a user is following the instructions.

Consider the perception this issue leaves:

User:
1) "Kong sounds great! Let me try it."
2) Pull up installation instructions for OSX.
3) "Wow, this is really simple to get started!"
4) `brew install kong`
5) `kong config init`
6) Output: `resty: No such file or directory`
7) User scratches head.

**Comment by nithyanatarajan** [comment]
The issue is still present. `brew link --overwrite openresty` proposed by @bagsiz worked for me.

**Comment by fooevr** [comment]
I've solved this issue by this steps:
1. ```find / -name "openresty"```  got openresty path /usr/local/Cellar/openresty@1.15.8.3/1.15.8.3/openresty
2. ```ln /usr/local/Cellar/openresty@1.15.8.3/1.15.8.3/openresty/bin/resty /usr/local/bin/resty```

**Comment by gogomarine** [comment]
So issue still exists.

**Comment by notxcain** [comment]
It's still there in 2021 :)
