### ISSUE TITLE
Kong nextServer

### ISSUE THREAD

**Issue by codingman1990** [Kong/kong#4721]
Is there any configuration about nextSever or proxy-next-upstream in NGNIX that can reload request to next node upstream?

**Comment by Tieske** [comment]
I guess you mean "retry" (not "reload") a request to the next upstream?

see docs here: https://docs.konghq.com/1.2.x/proxy/#4-errors--retries

the directives can be added by injecting them in the generated configuration, see https://docs.konghq.com/1.2.x/configuration/#injecting-individual-nginx-directives

In this case by setting the enviornment variables like this for example:

```shell
export KONG_NGINX_PROXY_PROXY_NEXT_UPSTREAM=“error timeout”
```

**Comment by codingman1990** [comment]
> I guess you mean "retry" (not "reload") a request to the next upstream?
> 
> see docs here: https://docs.konghq.com/1.2.x/proxy/#4-errors--retries
> 
> the directives can be added by injecting them in the generated configuration, see https://docs.konghq.com/1.2.x/configuration/#injecting-individual-nginx-directives
> 
> In this case by setting the enviornment variables like this for example:
> 
> ```shell
> export KONG_NGINX_PROXY_PROXY_NEXT_UPSTREAM=“error timeout”
> ```

@Tieske Thanks for your answer.But when i restart anyone of upstream, it still fail with 5% error,if i imcrease the value of retries to 10, then the percentage will decrease to 1%.That confused me!

**Comment by Tieske** [comment]
That primarily seems like an issue with the upstream service.

Are there any errors in the logs?

**Comment by p0pr0ck5** [comment]
@codingman1990 do you have health checks enabled on your upstream? If you don’t, kong will not remove unhealthy upstream entries from the balancer, so the behavior you’re seeing is expected.

**Comment by codingman1990** [comment]
> re there any errors in the logs?

I found that if kong actually retried less than retries that we configured,it's ok.But once retried greater than retries,kong's status will be 502.

**Comment by codingman1990** [comment]
> @codingman1990 do you have health checks enabled on your upstream? If you don’t, kong will not remove unhealthy upstream entries from the balancer, so the behavior you’re seeing is expected.

I just graceful shutdown my tomcat,it will waiting for received requests to be completed,but reject  any new request.

**Comment by p0pr0ck5** [comment]
I mean, have you configured health checks in Kong: https://docs.konghq.com/1.2.x/health-checks-circuit-breakers/

**Comment by codingman1990** [comment]
> I mean, have you configured health checks in Kong: https://docs.konghq.com/1.2.x/health-checks-circuit-breakers/

Yes.What it really want is upstream has two nodes(called node1,node2),if node1 return http failture,kong retry node2 immediately,now request should be 100% success.But depend on health-check, it's period,so request won't be 100% success.Is it right? Thanks!

**Comment by Tieske** [comment]
There are 2 things at play here:

1. a failure that is "retry-able", and the consecutive retries (configured on the `service` object)
2. healthchecks

Just a reminder: To use healthchecks, you MUST configure and use an `upstream` object.

### So how does this work (assume we do not use healthchecks):

- The balancer has a number of slots (1000), they get randomly assigned to your 2 upstream services.
- The balancer will simply round-robin along this list.
- When it fails, it will retry the next one in the list.
- Since the list is distributed randomly across the 2 upstreams you have, the retry might actually hit the same (faulty) upstream again.
- Even if retries is set to 10, you might run into a situation that the balancer will have 10 the same upstreams in a row (probability is low, but can happen)

### So what if we add a PASSIVE healthcheck:

- now when an upstream fails, the failure counter is increased
- a retry will still just round-robin along the list
- when the failurecount hits the failure threshold, the upstream will be marked as unhealthy
- from now on, the balancer while doing its round-robin thing, will skip the unhealthy entries


### Essence of making this work:

- configure a PASSIVE healthcheck
- make sure retries is configured to be greater than the failure threshold in the healthcheck

**Comment by codingman1990** [comment]
> There are 2 things at play here:
> 
> 1. a failure that is "retry-able", and the consecutive retries (configured on the `service` object)
> 2. healthchecks
> 
> Just a reminder: To use healthchecks, you MUST configure and use an `upstream` object.
> 
> ### So how does this work (assume we do not use healthchecks):
> * The balancer has a number of slots (1000), they get randomly assigned to your 2 upstream services.
> * The balancer will simply round-robin along this list.
> * When it fails, it will retry the next one in the list.
> * Since the list is distributed randomly across the 2 upstreams you have, the retry might actually hit the same (faulty) upstream again.
> * Even if retries is set to 10, you might run into a situation that the balancer will have 10 the same upstreams in a row (probability is low, but can happen)
> 
> ### So what if we add a PASSIVE healthcheck:
> * now when an upstream fails, the failure counter is increased
> * a retry will still just round-robin along the list
> * when the failurecount hits the failure threshold, the upstream will be marked as unhealthy
> * from now on, the balancer while doing its round-robin thing, will skip the unhealthy entries
> 
> ### Essence of making this work:
> * configure a PASSIVE healthcheck
> * make sure retries is configured to be greater than the failure threshold in the healthcheck

Thank you very much.This's what i really want.

**Comment by Tieske** [comment]
k, let's close this then.
