### ISSUE TITLE
Kong 1.2.1 returns 502 when Postgres is unreachable

### ISSUE THREAD

**Issue by zeeshen** [Kong/kong#4807]
### Summary

I'm running chaos test on Kong V1.2.1 with a Postgres server.
When I make the Postgres server unreachable by modifying iptables, some request return 502(`$status` in `access.log` is `000`)
Here is a suspicious error log:
```
2019/07/17 07:07:10 [error] 21424#0: *12422286 [lua] plugins_iterator.lua:97: load_configuration(): failed to get from node cache: [postgres] timeout, client: 222.72.156.190, server: kong, request: "GET / HTTP/1.1", ...."
```

I looked into the code base, and found that this error happens when the related plugin cache is not ready. Maybe it's introduced by this [commit](https://github.com/Kong/kong/commit/e1ad79dbe8ceef3da91783296ccb3f8d451632c2). Is that okay to skip plugin loading when db is unreachable?

### Steps To Reproduce

1. Prepare a Kong server with 3 routes `route-a`, `route-b`, `route-c`.  Enable a plugin of `route-a`
```
curl -i -X POST \
  --url http://localhost:8001/services/ \
  --data 'name=example-service' \
  --data 'url=http://mockbin.org'

curl -i -X POST \
  --url http://localhost:8001/services/example-service/routes \
  --data 'hosts[]=routea.com' \
  --data 'name=routea'

curl -i -X POST \
  --url http://localhost:8001/routes/routea/plugins \
  --data 'name=prometheus'

curl -i -X POST \
  --url http://localhost:8001/services/example-service/routes \
  --data 'hosts[]=routeb.com'

curl -i -X POST \
  --url http://localhost:8001/services/example-service/routes \
  --data 'hosts[]=routec.com'
```
2. Restart Kong maybe.
3. Access `route-a` to warm up plugin cache
```
curl localhost:8000 -H 'Host: routea.com' -I
curl localhost:8000 -H 'Host: routeb.com' -I
```
4. Make the Postgres unreachable by `sudo iptables -A OUTPUT -j DROP -d $pg_ip -p tcp --dport 5432`
5. Request `route-a`, `route-b` and `route-c`. The response of `route-c` should have error. And similar error log can be found.
```
curl localhost:8000 -H 'Host: routec.com' -I
curl: (52) Empty reply from server
```
### Additional Details & Logs

- Kong version 1.2.1
- Operating system
```Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
- Kong configuration
```
db_update_frequency = 60
dns_stale_ttl = 300
-- other configurations are just default values
```

**Comment by kikito** [comment]
Thanks for running these tests, we will investigate this issue.

**Comment by bungle** [comment]
On logs you will get:
```
2019/08/13 13:24:30 [error] 17740#0: *200 lua entry thread aborted: runtime error: ./kong/db/strategies/postgres/connector.lua:343: attempt to perform arithmetic on local 'num_queries' (a nil value)
stack traceback:
coroutine 0:
	./kong/db/strategies/postgres/connector.lua: in function <./kong/db/strategies/postgres/connector.lua:336>, context: ngx.timer
2019/08/13 13:24:44 [error] 17740#0: *249 [lua] plugins_iterator.lua:107: load_configuration(): failed to get from node cache: [postgres] connection refused, client: 127.0.0.1, server: kong, request: "HEAD / HTTP/1.1", host: "routec.com"
```

**Comment by bungle** [comment]
It is interesting, I even tried this:
```
KONG_DB_CACHE_WARMUP_ENTITIES=services,routes,plugins KONG_DB_UPDATE_FREQUENCY=60 KONG_DNS_STALE_TTL=300 ./bin/kong restart
```

And log said it warmed up all these, still it doesn't work.

**Comment by bungle** [comment]
I don't think Kong is returning anything, e.g. not even `502`. It just ends up here: 
https://github.com/Kong/kong/blob/next/kong/runloop/plugins_iterator.lua#L108

Which means Nginx will just close the connection with the client, so nothing is returned (which is a thing to discuss as well).

Now, why this does not work? It is because on prewarm we don't negative cache the plugins. E.g. routec + prometheus plugin. We don't have information that this combination does not exists. So when you try to hit routec we check if it exits and that leads to database call, because cache in not negatively warmed, then db return nothing and we negatively cache.

This thing makes it really hard for Kong to run without active database connection. We once had PR that included caching of plugins, but because of feature that plugins can be added to consumers (so potentially a lot of different combinations) we could not make the decision to cache plugins in memory (which would otherwise have been great). Perhaps we could find a middle ground to cache `route`/ `service` combinations, and just skip caching the `consumers` combinations.

**Comment by bungle** [comment]
The PR #4903 was merged, so this can now be closed. It still does not solve this 100%, e.g. if you have authentication plugin that sets `consumer` we may still need to make db call. We can later of decide if caching consumer ids is the way to correct rest of this. And of course any plugin may make their own dao calls that are not necessarily prewarmed, especially the negative cache, so in this sense it cannot be fixed easily 100%. But at least the issue described here is not fixed.
