### ISSUE TITLE
Kong community analystics

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4857]
### Summary
HI everyone i hope y'all have a day
so I'm new to kong.
can anyone tell me if kong community edition has a analystics plugin or something?
like i wanna know which service has how many request and which client made which requests?
thanks for your helps!

### Additional Details & Logs

- Kong version (`$ 0.14.1`)
- ubuntu

**Comment by kikito** [comment]
Here's the list of Analytics plugins in the Kong hub:

https://docs.konghq.com/hub/#analytics-monitoring

Given your needs, you might want to consider using a simpler logging plugin instead of an analytics one:

https://docs.konghq.com/hub/#logging

I'm closing down this issue because we tend to reserve Github issues for bug reports. Requests for help and questions are better suited to https://discuss.konghq.com/ . If you want to continue this conversation, please open a thread there. Thanks!
