### ISSUE TITLE
localhost:8000 on browser doesn't work

### ISSUE THREAD

**Issue by AliShelby** [Kong/kong#4890]
### Summary

SUMMARY_GOES_HERE
I'm using kong for my api management and I've created service and consumer and route successfully with this link: https://docs.konghq.com/hub/kong-inc/key-auth/
so when I make a request with terminal suing this command:
curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: example.com' \
  -H apivalue:'gVYDLqG8es2zkpV5cut49TOQ5xOpkVj0'

it works perfectly fine!
but i want to make a request in firefox browser and not just in terminal!
so when i open this page:
http://localhost:8000/ or this page : http://localhost:8000/example.com?apivalue=gVYDLqG8es2zkpV5cut49TOQ5xOpkVj0

it gave me this: 
no route and no API found with those values

what should i do to make a request to my service via firefox or any other else browsers?

- Kong version (`0.14.1)

- Ubuntu

**Comment by Tieske** [comment]
that is expected.

You enter the url in the browser, and from that the browser will set header `Host: localhost` because it is in the url. You (generally) cannot override the host header when testing from the browser, it will always match the host in the url.

You can set up Kong though, to not route based on the `Host`, but solely on the uri-path. Then it will work.
