### ISSUE TITLE
Request_time > upstream_response_time ,difference between 2 seconds sometimes, same most of the time 

### ISSUE THREAD

**Issue by taotao2014** [Kong/kong#4910]
kong :0.14.1

$request_time>$upstream_response_time ,difference between 2 seconds sometimes, same most of the time，return data is small (19k)

$request_time: request processing time in seconds with a milliseconds resolution; time elapsed between the first bytes were read from the client and the log write after the last bytes were sent to the client。

$upstream_response_time ： keeps time spent on receiving the response from the upstream server; the time is kept in seconds with millisecond resolution.

**Comment by bungle** [comment]
@taotao2014,

I am not sure what you are asking. Is your question about why Kong may add 2 seconds to latency and usually 0 ms latency? Perhaps it is because Kong needs to load something from database? 2 seconds sure is a lot, perhaps DNS resolution, perhaps you have some plugins running there? With this little information it is hard to give exact answer.

**Comment by taotao2014** [comment]
log_format json '{"dt":"$time_iso8601","ra":"$remote_addr","ip":"$http_x_forwarded_for","c":"$status","m":"$request_method","up":"$upstream_addr","rt":"$request_time","urt":"$upstream_response_time","h":"$http_host","qs":"$query_string","uri":"$uri","rs":"$body_bytes_sent","ref":"$http_referer","ua":"$http_user_agent","ssl":"$ssl_protocol"}';

$equest_time > $upstream_response_time

**Comment by bungle** [comment]
These are `nginx` variables, nothing to do with `Kong`. @taotao2014 perhaps you understand their meaning wrong? I will close this.
