### ISSUE TITLE
Kong latency increased when routes updated

### ISSUE THREAD

**Issue by zeeshen** [Kong/kong#4974]
We observed that when routes updated, we'll get a latency spike in `kong_latency_xxx{type="request"}`. And we found that it's caused by a `coroutine_mutex` in rebuild_router. 

Setting `router_consistency` to `eventual`  may be a resolution to this problem. But we still have some questions, hope you guys can help:

### Why this `get_updated_router` latency is not included in kong proxy time? 

We noticed that `ctx.KONG_ACCESS_START` is set after get_updated_router. 
The gap between `kong_latency_xxx{type="request"}` and the sum of `kong_latency_xxx{type="kong"}` and `kong_latency_xxx{type="upstream"}` is a little confusing.

### Is it necessary that every worker fetch updated routers directly from database?

Is it feasible that one worker fetch routers from database and store them in shared memory, then broadcast the router version changed worker event?

### Additional Details & Logs

- Kong version 1.3.0

**Comment by bungle** [comment]
@zeeshen,

#### About Router Rebuilds

That is normal. When you update router with `router_concistency=strict` it may be background timer (runs every second — `next` branch has that configurable) or a request that starts building a new router. That build process will acquire a `mutex` and it will basically halt processing all the requests on that worker (similarly if request ends up in another worker same will happen). Mutex is acquired so that only one request in same worker will bombard the database. So every request waits for new router to be available or the mutex will timeout (less likely) on single worker. But because of `timer` we try to proactively build new one (on all workers). Though on heavy traffic proxying, it is likely that request will start building a new one (but same applies, mutex is hold by worker, so light threads on same worker will need to wait for new router to become available).

Now you can set `router_consistency` to `eventual` which means that on requests we don't even check the router version, we just use what is available, and leave the router rebuilding to background timer (only one rebuild process per worker will run concurrently).

Personally I would always run with `eventual` consistency on production. If you have multinode cluster of Kong, you are already bit `eventual` between nodes, so why not be eventual on single node too between the workers. Of course we did not want to set this as default as it would break backward compatibility. Perhaps we can consider it default for `2.0`.

#### Latency

I am currently working on refactoring the latency counters. It should be done today, and available for review.

#### Every worker to fetch updates?

Well every worker does not fetch everything, e.g. we cache the services on shared memory. We don't cache collections currently. Broadcasting has it's own issues. I btw. did try this, but after trying it, I did not find it all that good. We could perhaps revisit later. What we endup building is quite complex router object that I am not sure how it could be serialized in shared memory nicely, probably benefits are less than problems it causes. In general I think `router_consistency=eventual` and `router_update_frequency=<secs>` is quite good already).

Similar to router we do for plugins (bit differently though as consumer plugins may have high cardinality so we don't cache everything in memory).

**Comment by zeeshen** [comment]
Thanks for your explanations. We'll try `router_consistency= eventual` later because actually we're running a 1.0.x Kong on production :). 

As one of those that don't use consumers that much, we really want Kong can run with the control plane and the data plane separated. Hope you guys make this happen. And thanks for all the nice work.
