### ISSUE TITLE
 How to use kong for tcp forwarding

### ISSUE THREAD

**Issue by xiaojin525** [Kong/kong#5078]
I created a service and router for mysql, bug  can not use.
curl -X PUT \
       -d url=tcp://10.248.230.19:3306 \
       http://127.0.0.1:8001/services/mysql

curl -X POST \
       -d name=mysql2\
       -d protocols=tcp \
       -d destinations[1].ip=10.248.230.19 \
       -d destinations[1].port=3306 \
       http://127.0.0.1:8001/services/mysql/routes

How can I use this router ?

**Comment by kikito** [comment]
Hi, assuming that you have [the `stream_listen` config option](https://docs.konghq.com/1.3.x/configuration/#stream_listen) set in your config file, you should be able to use kong "as if it was your database". In other words, instead of connecting to `10.248.230.19:3306` for accessing mysql, you should be able to connect to `http://127.0.0.1:7000` (assuming that `7000` is the selected port for streaming TCP) and use the database from there.

**Comment by xiaojin525** [comment]
ok, thinks
