### ISSUE TITLE
What's the problem?

### ISSUE THREAD

**Issue by someon2** [Kong/kong#5157]
951#0: *29825814 [kong] handler.lua:25 reporter flush failed to request: connection refused, context: ngx.timer, client: 125.70.16.103, server: 0.0.0.0:8443

kong 1.3.0

**Comment by jayce** [comment]
I also had the same question, and I found the source. please open https://github.com/Kong/kong-plugin-zipkin/blob/master/kong/plugins/zipkin/reporter.lua#L121.

In my kong, it is just a little mistake that I wrong the "http endpoint".

Hope useful for u

**Comment by p0pr0ck5** [comment]
`connection refused` implies that the remote host rejected the connection, likely because it didn't have an open socket listening on the given host and port. You should double check your configuration and ensure the remote end is listening on the IP and port you've configured.

Given this, I will close this issue now; please let us know if you have any other questions. Thanks!

**Comment by prafultamrakar** [comment]
I have a same issue , can you help me here
