### ISSUE TITLE
Kong 1.4.1 kong_nginx_http_current_connections keep growing

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/kong#5328]
### Summary

It seems **kong_nginx_http_current_connections** will keep growing and never reduce when I try to make changes to kong with **multiple admin api requests**. 

Kong becomes **high cpu load ( 20 - 80 ) and high memory  ( 300M free )**, and creates **much pid of prng_seeds ( 20+ )**. 

I try to reload kong, but connections still not reduce.

**- Service Info**
1. Admin api service, route /admin-api/xxx request to localhost 8001 ( admin_listen ). Basic auth plugin is added to this service.
2. Metrics api service, route /metric-api/metrics to localhost:8011 ( status_listen ).
3. Business api servers, route to other servers.

**- Runtime Info**
1. Run in docker ( DockerCE 18.09.1 ), in vm with 4 cores, 8G memory and swap off.
2. No requests other than admin api during testing.

![nginx_http_current_connections](https://user-images.githubusercontent.com/27359184/70708020-7eac6480-1d14-11ea-916c-d32343a9c895.png)

### Steps To Reproduce

1. Set admin_listen to 127.0.0.1:8001.
2. Create a service with basic auth plugin to route admin api request.
3. Request to admin api several times.
4. Check kong_nginx_http_current_connections and find it keep growing.

### Additional Details & Logs

- Kong version 1.4.1

**Comment by hishamhm** [comment]
@JoyZhang66 I wonder if this is related to lifting the limit of connections — what is the value of `ulimit -n` in that machine?

**Comment by bungle** [comment]
This old issue also reported about prng_seeds:
https://github.com/Kong/kong/issues/4351

**Comment by hugoShaka** [comment]
If somebody ever encounters issue this happens because of memory pressure and OOM Killer:

* nginx/kong runs in a container/cgroup with a memory limit
* nginx tries to allocate more memory than available in the cgroup
* the OOM Killer wakes up and looks for something to kill (in the cgroup) to allow nginx's allocation
* OOM Killer terminates one of nginx's workers
* the active, writing, reading, keep_alive gauges are not updated to remove the connections lost when the worker was killed
* nginx restarts a worker
* the metric will never get back to normal without an nginx restart

One can avoid this behaviour by avoiding OOMKills. From my understanding this is an nginx bug.

**Comment by dndx** [comment]
Seems that the issue has been answered so closing this for now. Let us know if the problem persists.
