### ISSUE TITLE
Function kong.request.get_body("application/json") doesn't support null value

### ISSUE THREAD

**Issue by cheriL** [Kong/kong#5349]
Hi, I have one question about calling kong.request.get_body("application/json")  with request body like this:
_{
    code : null,
    msg : "failed"
}_
and I got the table:
_{
    ["code"]:"userdata: NULL",
    ["msg"]:"failed"
}_
table I expected:
_{
    ["msg"]:"failed"
}_

Is there some way to get what I want?

**Comment by bungle** [comment]
@cheriL, it means that we especially _do_ support `null`. Lua `nil` on value in `table` is not a valua at all, but hole. Thus `ngx.null` which equals to `cjson.null` is used for meaning of JSON `null`, e.g. a value explicitly specified in JSON, not just key or value missing from JSON. That's why I am closing this.
