### ISSUE TITLE
consul uses consul dns address and other uses another dns address. feasible?

### ISSUE THREAD

**Issue by fusi0011** [Kong/kong#5379]
i buy pgsql server on aliyun , it address is domain name and `dns_resolver` is consul dns address, but an anomaly of 'dns server error: 3 name error' was found  
currently, the solutions: 
1. uses consul configuration options `-recursor` =  upstream DNS servers
2. DNS forwarding using 'bind'  

Do you guys have a better solution?

**Comment by p0pr0ck5** [comment]
Either one is appropriate, though in general I prefer the latter. This is because an unavailability in the Consul cluster would prevent _all_ dns recursion. Best to point Kong’s DNS resolver at an intermediary proxy like bind or unbound, and forward traffic to a stub zone for consul records appropriately

**Comment by fusi0011** [comment]
> Either one is appropriate, though in general I prefer the latter. This is because an unavailability in the Consul cluster would prevent _all_ dns recursion. Best to point Kong’s DNS resolver at an intermediary proxy like bind or unbound, and forward traffic to a stub zone for consul records appropriately

tks
