### ISSUE TITLE
[KONG 1.4.2] FATAL: sorry, too many clients already

### ISSUE THREAD

**Issue by namirsab** [Kong/kong#5447]
### Summary
Opening a new issue after this one was closed #5439

During the last days, we've been having issues with KONG and PostgreSQL. KONG creates too many connections to the database that are not cleaned, eventually reaching the limit and getting the error:
```
Fatal: sorry, too many clients already
```
We are using the `pg_max_concurrent_queries` property (set it to 5 first, and then to 1). We have only one node with 8 workers, so according to the documentation we should have a maximum of 40 connections, but we are still having connections that are never closed.

I'll give more information if we figure out ourselves what the problem is, but wanted to raise the issue because this problem can also happen with 1.4.2 

Here you can see the variety of errors we get also from KONG. 

We get a variety of errors in KONG:

```
2020/01/14 14:40:36 [error] 36#0: *80 recv() failed (104: Connection reset by peer), context: ngx.timer

2020/01/14 14:48:49 [error] 36#0: *1833 recv() failed (104: Connection reset by peer), client: 10.0.1.8, server: kong_admin, request: "GET /consumers?custom_id=x3yKmEAcWNcFyXvga HTTP/1.1", host: "kong:8001"

2020/01/14 14:48:49 [error] 36#0: *1833 [kong] api_helpers.lua:310 receive_message: failed to get type: connection reset by peer, client: 10.0.1.8, server: kong_admin, request: "GET /consumers?custom_id=x3yKmEAcWNcFyXvga HTTP/1.1", host: "kong:8001"

2020/01/14 14:50:06 [warn] 36#0: *1677 [lua] mlcache.lua:763: get(): callback returned an error ([postgres] connection refused) but stale value found in shm will be resurrected for 30s (resurrect_ttl), client: 10.0.0.171, server: kong, request: ""

2020/01/14 14:50:09 [error] 36#0: *2123 [kong] api_helpers.lua:310 connection refused, client: 10.0.1.247, server: kong_admin, request: "GET /consumers?custom_id=hv2WviZbgEKt2ZqGu HTTP/1.1", host: "kong:8001"

2020/01/14 14:50:18 [error] 36#0: *2155 [kong] api_helpers.lua:310 [key-auth] host is unreachable, client: 10.0.1.8, server: kong_admin, request: "GET /services/uca-editor HTTP/1.1", host: "kong:8001"

2020/01/14 14:52:25 [error] 36#0: *2154 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.0.0.145, server: kong, request: "GET ", upstream: "
```

Maybe someone understands those errors.

**Comment by bungle** [comment]
With Cassandra you surely can have more connections. I will label this for investigation.

**Comment by bungle** [comment]
@namirsab, what does you postgres answer to:
```
SHOW max_connections;
```

**Comment by namirsab** [comment]
@bungle unfortunately we are not using this anymore so I can't answer your question, but the max_connections was set to the default (100).
We didn't change that

**Comment by onematchfox** [comment]
@bungle Also ran into this issue when load testing. `max_connections` is set to 200 and I am running 3 containers each with `nginx_worker_processes = 1` and no changes to the default `lua_socket_pool_size` (i.e. 30). Due to some admittedly shocking code which was hitting the DB on every request (rather than using cache), I noticed Kong attempting to open 300+ connections resulting in a plethora of errors like: 

```
[postgres] FATAL: remaining connection slots are reserved for non-replication superuser connections
[postgres] FATAL: sorry, too many clients already
```

Searching led me here and to https://groups.google.com/forum/#!topic/konglayer/_OuqXxHe7og which didn't seem to come to a satisfying conclusion either. Namely the outstanding question "Is there some condition that might cause the number of connections to exceed the socket pool limit?" doesn't seem to have been answered. I don't suppose you may know the answer here?
