### ISSUE TITLE
configuring CRD's in helm

### ISSUE THREAD

**Issue by eilonk** [Kong/kong#5470]
Greetings,
I'm trying to create a helm configuration for kong, and I'm having trouble understanding some values concept-wise.
If kong comes with CRD's built in (Kong Ingress,plugin, consumer and credential) - where do these fit inside the internal yaml file?
I can't seem to find any example for configuring these resources through this type of file (only shorter examples)
for context, i am using the files supplied by kong and am obviously missing something..
would love to see an example and understand it better.
Thanks in advance for any help!

**Comment by hbagdi** [comment]
Hi @eilonk,

Thank you for the question.
I'm going to assume that by 'internal YAML file', you mean providing configuration to DB-less Kong nodes via declarative configuration file.
If that's the case, then you are confusing between two different methods of configuring Kong. You can use one of those methods at once only.

So, either you use Kong's declarative format to configure Kong or you used CRDs to configure Kong.

**Comment by derba** [comment]
If I understand @eilonk correctly then the issue is that the syntax of KongIngress and other CRDs one describes in a Helm chart (yaml) is unclear.

When I first looked at Kong Ingress Controller's repo I read its readme. That leads you to [CRD concept](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/concepts/custom-resources.md). But that doc, especially the charts with arrows are somewhat misleading. It is not clear that standard K8s Ingress definition is used, defining Services and Routes. Just some annotations are added referring to extra Kong parameters. You need to reach [KongIngress guide](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md) to get that detail. And then [the reference](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/custom-resources.md) for more details.

**Comment by hbagdi** [comment]
That's correct  @derba.

Closing this issue because of no response from OP.
Please post on Kong Nation in future for questions. Thanks!
