### ISSUE TITLE
Basic-auth plugin does not work in hybrid mode

### ISSUE THREAD

**Issue by mdostal-hci** [Kong/kong#5649]
### Summary
Basic-auth plugin does not work in hybrid mode - when I try to create consumer credentials, changes on control plane are not propagated to data plane. According to [this post](https://discuss.konghq.com/t/kong-2-hybrid-mode-and-plugins-compatibility/5565) it should work for auth plugins, and for key-auth it actually works fine. Details has been [described here](https://discuss.konghq.com/t/basic-auth-plugin-in-hybrid-mode/5689).

### Steps To Reproduce

1. Install Kong in hybrid mode (1 control plane, 1 data plane)
2. Create a consumer on control plane
3. Create a basic-auth credentials for that consumer
4. Try to use the credentials on data plane

### Additional Details & Logs
Config_hash checksum (`curl -X GET localhost:8001/clustering/status`) changes when creating a consumer or key-auth credentials, but it does not change when creating basic-auth credentials.

- Kong version (`2.0.1`)
- Kong error logs - no errors
- Operating system - Docker

**Comment by kikito** [comment]
Hello, we recently merged #5835 which should solve this issue on the next version of Kong (2.1.0).
The short version of the change is: there will be a new declarative config header called `_transform` (default to `true`) which can be used to deactivate transformations. The control plane will need to set this parameter to `false` when the schema transformations (for example, encryption or hashing of passwords) isn't necessary.

Since we added this new feature to the declarative config, we have bumped the version number of the declarative config syntax to 1.2.
