### ISSUE TITLE
We use Kong dbless  and declarative configuration to deploy kong, how to update the incremental configuration file? Not the whole config file (kong.yml).

### ISSUE THREAD

**Issue by chenhuandong8010** [Kong/kong#5677]
### Summary

We use Kong dbless  and declarative configuration to deploy kong, how to update the incremental configuration file? Not the whole config file (kong.yml).

For example, I want to add a microservice. The routing configuration and plug-in configuration used by the microservice are placed in a separate configuration file. How can I update the configuration file incrementally instead of modifying the kong.yml file

docker run -d -u root --name kong --net=host  -v "kong-vol:/usr/local/kong/declarative" -e "KONG_DATABASE=off" -e "KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:2.0.1

**Comment by bungle** [comment]
Currently we do not have that capability, but it has become evident we need it especially now that we introduced a cp/dp separation, a hybrid mode. So it is on our backlog.

**Comment by dndx** [comment]
Declarative config does not have capability to update part of the config in memory. You must update the entire config via the `/config` endpoint. See: https://docs.konghq.com/2.0.x/db-less-and-declarative-config/ for an example. Furthermore, there is currently no plan to support splitting the YAML file into multiple parts inside as of now.

**Comment by hishamhm** [comment]
Also, as a side note it's worth mentioning that the point of configuration being _declarative_ is that it represents the entire configuration and there is no intermediate states. If you're doing incremental updates, you are effectively doing it _imperatively_ ("do this then that"), which would, as @dndx correctly explained, "incrementally updating Kong config using a yaml file", and not really declarative configuration.

I know this sounds a bit like a terminology nitpick, but it has management implications: a lot of the "gitops" management philosophy centers around keeping things truly declarative so that each past state remains fully documented (incremental changes being done as commits to the git-managed declarative config).

**Comment by chenhuandong8010** [comment]
Got it, tks ：）
