### ISSUE TITLE
Does the kong support stateful request route?

### ISSUE THREAD

**Issue by zxgm** [Kong/kong#5704]
If the request is stateful,how to route the request to the back-end service?The stateful infos how to save?

**Comment by bungle** [comment]
@zxgm what do you mean by `stateful`?

**Comment by bungle** [comment]
Do you mean something like `hash_on_cookie` here:
https://docs.konghq.com/2.0.x/admin-api/#request-body-21

**Comment by zxgm** [comment]
The stateful request like http session operation,the two requests are related,the second request is based on first request result.

**Comment by bungle** [comment]
@zxgm, with `http` all requests are stateless. The way to introduce `state` in `stateless` http protocol is to use `Cookies`. In general when your upstream or kong plugin sends client a cookie as a response, the client should send them back on each subsequent request. At least this is what browsers in general do. There are basically two different type of cookies, persistent and session (in-memory), and then there are different flags on Cookie such as `Secure`, `HttpOnly`, `SameSite=None|Lax|Strict`, `Path`, `Domain`, `Max-Age`, `Expires` (last two only with persistent cookies or when deleting a cookie).

Kong of course has no problem on proxying `Set-Cookie` headers back to your client OR `Cookie` headers from your client to upstream. We even have a plugin that maintains session for our authentication plugins (that rely Kong as a identity provider): https://docs.konghq.com/hub/kong-inc/session/

**Comment by zxgm** [comment]
Thanks a lot.

**Comment by Tieske** [comment]
@zxgm the other approach @bungle mentioned, using `hash_on` uses the consistent hashing method of loadbalancing. This is typically used if the state is being retained on the backend server. As a consequence this means that every follow up request must end up on the same backend, because otherwise the required "state" would not be available to deal with the follow up request.

Though Kong supports [consistent hashing](https://docs.konghq.com/2.0.x/loadbalancing/#balancing-algorithms) (hash-based loadbalancing), the proper way to handle state, is as @bungle explained by keeping the requests stateless, and pass all required data along with the request (where cookies are a common way of achieving that).

Consistent hashing balancing can be used with legacy applications that still require state on the backend, or in modern applications to optimize the backend cache-hit ratio's.
