### ISSUE TITLE
upstream rejected request with error 2 while reading response header from upstream

### ISSUE THREAD

**Issue by gdonlyathw** [Kong/kong#5733]
grpcurl response from target service:

Resolved method descriptor:
rpc transform ( .me.brightliao.pipeline.Features ) returns ( .me.brightliao.pipeline.Features );

Request metadata to send:
(empty)

Response headers received:
content-type: application/grpc
grpc-accept-encoding: gzip

Response contents:
{
  "fields": [
    "a",
    "s",
    "c"
  ],
  "rows": [
    {
      "value": [
        {
          "int": 1
        },
        {
          "long": "1"
        },
        {
          "string": "1"
        }
      ]
    },
    {
      "value": [
        {
          "int": 1
        },
        {
          "long": "1"
        },
        {
          "string": "1"
        }
      ]
    }
  ]
}

Response trailers received:
(empty)
Sent 1 request and received 1 response

**Comment by kikito** [comment]
Hi, we think this could be one of two things:

* Either the upstream is failing, or
* Kong is failing

You should be able to discard the first option by calling the upstream directly (without Kong proxying the request). If you get the same error, the problem is in the upstream server.

If the problem is in Kong, please look at the error logs, they will probably have more information about the issue.
