### ISSUE TITLE
Backport Issue #5551 to Kong 1.5.x

### ISSUE THREAD

**Issue by ivanRylach** [Kong/kong#5814]
### Summary

We are using Kong `v1.5.1`. with Ingress Controller `v0.7.x` and we see the same issue as in #5551 , but we can not upgrade to `2.x` yet. Is it possible to back port the fix to `1.5.x`?

### Steps To Reproduce
Request
```
curl -k -XPATCH https://$ADMIN_URL/plugins/$AUTH_PLUGIN_ID --data "config.anonymous=$USERNAME"
```
Response
```
{"message":"schema violation (config.anonymous: expected a valid UUID)","name":"schema violation","fields":{"config":{"anonymous":"expected a valid UUID"}},"code":2}
```

### Additional Details & Logs
- Kong version - `1.5.1`
- Kong K8s Ingress Controller - `0.7.x`

**Comment by hishamhm** [comment]
There are no plans to make further releases in the open source 1.x series. Kong 1.5.1 was released because it contained a fix for the migrations, precisely to help people move out of 1.x. Please consider upgrading to Kong 2.x at your earliest convenience, we made every effort to provide a smooth upgrade path.

**Comment by ivanRylach** [comment]
Thank you for a quick answer @hishamhm !
