### ISSUE TITLE
how to modify response body on the fly?

### ISSUE THREAD

**Issue by zffocussss** [Kong/kong#5918]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1.a plugin which implement body_filter
2.I can not replace the content,because the value
 of ngx.arg[1] is not string.

this is what is the out put of log :

IHDR szz�sRGB���gAMA��
                      �a	pHYs���o�d�IDATXG���M�0�;#t^��<�DA$U_��AQ&`���:BF`̝?�+���i*���C���}�ow6���
DA�����C�%o�%"��R{o���W��/�y����E�ܜ�6�
                          {&1����KաO�j,!2��6�pL%����${t�8��&%2C����%�
GM���~g������߫����E������S���(1�X"�c,�?h1���x�����;b�z��[�mq��ybK� � �N
                                                         ��Dư��=��'8��j�8��2?��כ��

��WP8'2$��m-�\p��
                 ��������	,

### Additional Details & Logs

- Kong version (`$ kong version`)
2.0.4
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
```
function plugin:body_filter(config)
   if string.match(ngx.arg[1],"</html>") then
      ngx.arg[1] = ngx.re.sub(ngx.arg[1],"</head>",abcd)
      kong.log.notice("ngx arg------>",ngx.arg[1])
    end
end
```
- Operating system
docker kong alpine

**Comment by kikito** [comment]
Hello @zffocussss,

The interface for handling bodies in openresty is complicated, because you are forced to deal with them in "chunks".

Here's an example of how do do what you want with a simple plugin which just converts the body to uppercase:

https://github.com/Kong/kong-plugin-uppercase-response/blob/master/kong/plugins/uppercase-response/handler.lua#L10-L26

Another thing that you have to take into account is that the upstream server might be returning compressed bodies. You might want to modify the request header to request plain responses.

**Comment by zffocussss** [comment]
> Hello @zffocussss,
> 
> The interface for handling bodies in openresty is complicated, because you are forced to deal with them in "chunks".
> 
> Here's an example of how do do what you want with a simple plugin which just converts the body to uppercase:
> 
> https://github.com/Kong/kong-plugin-uppercase-response/blob/master/kong/plugins/uppercase-response/handler.lua#L10-L26
> 
> Another thing that you have to take into account is that the upstream server might be returning compressed bodies. You might want to modify the request header to request plain responses.

it is true
