### ISSUE TITLE
bug: kong allows empty array for methods property in routes

### ISSUE THREAD

**Issue by hbagdi** [Kong/kong#5967]
### Summary

Kong allows for empty array in methods property.
This is a problem because an empty JSON array value and a null JSON value of a key have slightly different meanings and result in https://github.com/hbagdi/deck/issues/142 in decK.

### Steps To Reproduce
```
http post :8001/services name=service.name.local host=service.host.local -f
http post :8001/services/service.name.local/routes name=route.name.local hosts=route.hosts.local -f
http patch :8001/routes/route.name.local methods:='[]' --json
```

### Additional Details & Logs

- Kong version (`$ kong version`) 2.0.3

**Comment by bungle** [comment]
I am not sure if this is bug. Do you mean to change it everywhere? E.g. everywhere we have array the array should not be empty, or automatically converted to `null` if it is? I think we had some discussion about whether to allow empty arrays or not a long long time ago, and decided to have it. Thus we do have `null` and `{}` that of course are not the same. I ran those commands, and they worked as expected. Where do you see that inconsistency?

**Comment by hbagdi** [comment]
What I intended with the bug was that Kong should not allow `[]` as a valid input. We don't necessarily need to convert `[]` to `null` or (`nil` in Lua land).

**Comment by bungle** [comment]
@hishamhm do you happen to remember reasoning why empty arrays were allowed? We disallowed empty strings at some point because there is explicit validation `len_min=1`. But with arrays or sets we don't have one.

So as an input of array field we can have:
1. `nil` -> missing field, might lead to `default` to be used
2. `null` -> explicit null that can be set on `non-required` fields
3. `[]`-> empty array

The question is:
1. should we keep it like
2. should we go and adjust fields (like field-by-field)
3. should we generally not accept empty array as input
4. should we generally not accept null as input for array field

**Comment by hishamhm** [comment]
> What I intended with the bug was that Kong should not allow [] as a valid input.

@hbagdi how does Kong disallowing that fixes your deck issue? I read through the issue and tried to make sense of it but couldn't.

I think we should keep the behavior of arrays as it is now. 

@bungle we kept support for empty arrays because the schema library is general-purpose and empty arrays can make sense in different contexts. The empty string restriction was odd IMO but I was a minority opinion there, and even that, as you said, is supported with `len_min=1`, so you could say that both allowing and disallowing empty strings and arrays are both supported, it's just that the defaults are different for each data type.

I  think we should in general go with option 1, keep it like it is. _If_ there is a compelling reason for `routes.methods`, then it would be a special case to be adjusted with `len_min`, but so far I'm not seeing it.

**Comment by javierguerragiraldez** [comment]
closing because it's consistent behaviour.  it seems decK doesn't produce these empty array values itself, it just gets into a bad state if the user does it.
