### ISSUE TITLE
grpc compatible plugins

### ISSUE THREAD

**Issue by jideel** [Kong/kong#5972]
Hello,
According to this documentation : https://konghq.com/blog/manage-grpc-services-kong/ (maybe outdated ?), it seems the only grpc-compatible Kong plugins are the logging and observability ones.
However, i tried the key-auth plugin with grpc clients and servers (C# .Net Core implementation) connected through Kong (2.0), and the key authentication works correctly, as long as it's passed as a header and not appended to the "query string".
The following C# code : "new Metadata.Entry("api_key_parameter_defined_in_Kong", "api_key_value") is enough to add the header in the clients.
Without the key, Kong returns a quite explicit message : "Invalid authentication credentials", so far, so good.
Can you confirm the key-auth plugin is more or less grpc-compatible ?
Does some up-to-date compatible plugins list exists ?
Regards.

**Comment by gszr** [comment]
Hi @jideel,

Thanks for opening this issue, and welcome to the Kong community.

We've documented grpc support for only logging and observability plugins because those are the ones that were extensively tested with grpc. That does not mean, however, that other plugins won't work with grpc out of the box or with minimal changes -- only that we have not yet tested those with grpc. That said, we are currently working on this and you can expect news in the coming releases!

See [this](https://discuss.konghq.com/t/ip-restriction-for-grpc/5895) for a similar question.

**Comment by jideel** [comment]
Glad to know that :)
Thank you.
