### ISSUE TITLE
QUESTION Request and response body logs

### ISSUE THREAD

**Issue by zkenstein** [Kong/kong#6032]
### Summary

Is it possible to view the logs for Request body sent over Kong API? I tried to view it in syslog but nothing recorded about body request and response.

Thanks,

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by kikito** [comment]
It is true that Kong (and the underlying NGINX) are very careful not to require the complete bodies of requests or responses in order to work.

This is because bodies they have unbounded in size, and some of them tend to be fairly large. A 2GB video response could clog a worker trying to write it to the logs. Big bodies also require writing files on the host server, which is antithetical to the asyncrhonous treatment of I/O.

That said, it is perfectly possible to get the complete request/response body on a plugin, and then log it. It is just not done by default in order to avoid the efficienty problems I mentioned above.

If you are interested in building such a plugin, you could use [kong.request.get_raw_body](https://docs.konghq.com/2.2.x/pdk/kong.request/#kongrequestget_raw_body) to get the request body, and [kong.service.response:get_raw_body](https://docs.konghq.com/2.2.x/pdk/kong.service.response/#kongserviceresponseget_raw_body) to get the response body, and then log them with [kong.log](https://docs.konghq.com/2.2.x/pdk/kong.log/)

**Comment by Tieske** [comment]
see #5968
