### ISSUE TITLE
Support Operation in DB Less mode

### ISSUE THREAD

**Issue by JuniorCtba** [Kong/kong#6099]
Will be very nice if was possible to run operation in the API as Insert,Delete and Update using DB Less mode.

Br
Junior

**Comment by hishamhm** [comment]
Hi,

DB-less mode does not support these operations because it would make the memory representation of entities "stateful" (and that would essentially become reimplementing a database inside of Kong).

Instead, the goal of DB-less is to provide _declarative configuration_, which is characterized by a complete representation of the entire configuration at once, that you can then maintain GitOps-style, instead of a series of incremental steps (which would be a more "imperative" configuration, to trace a parallel with declarative vs. imperative programming language styles).

Hope that clarifies the reason why these operations are not supported!
