### ISSUE TITLE
HTTP 499s and logging results delivered

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#6180]
### Summary

Those familiar with NGINX know that an HTTP 499 means the client severed the connection prior to allowing the NGINX Webserver(Kong) to respond on a given request, usually when NGINX is just waiting for the backend API service to reply. 

Note BackendLatency being -1, which is from this field:
https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L58
```
ctx.KONG_WAITING_TIME or -1,
```

When the client cuts the connection short, why is the time window already spent waiting on the backend totally lost in Kong? Very specifically I would expect the ```ctx.KONG_WAITING_TIME``` to have a value close to 4003 (4007 - 4ms(from access/rewrite time)). Which ultimately looks like a 4 second client read timeout to Kong/Nginx judging by the TotalLatency field. I can see how some folks would misinterpret the log below to be that Kong had trouble reverse proxying to the backend API. 

```
{ [-]
   BackendLatency: -1
   CID: 7869c6c2-6f07-4597-a138-63936e618bca#558349
   ClientIP: 65.xxx.x.xx
   Consumer: consumer1
   GatewayHost: gateway.company.com
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 499
   KongLatency: { [-]
     AccessTime: 3
     BalancerTime: 0
     ReceiveTime: 0
     RewriteTime: 1
   }
   RequestSize: 2519
   ResponseSize: 0
   RoutingURL: my-api:443/R4/Bundle/$service
   ServiceName: my.api.service.v1
   TotalLatency: 4007
   Tries: [ [+]
   ]
   URI: /api/test/api/fhir/v1/R4/Bundle/$service
}
Show as raw text
```

### Steps To Reproduce

1. Force a 499, look at the latency reported on the communication with the backend service.

### Additional Details & Logs

- Kong version 2.1.0 (or any version for that matter)

**Comment by hishamhm** [comment]
@jeremyjpj0916 If the client cuts the connection before allowing Kong to even respond, I wonder if those stats are even exposed to us at the Lua level. I haven't investigated, but I truly wonder whether it's even doable. :thinking:

**Comment by jjustus2** [comment]
@hishamhm Yeah I am not sure if NGINX is doing some kinda funky internal reset on some of the existing values storing things like the time elapsed communicating with the backend in a scenario like this causing the Kong tracking context to lose results. Nonetheless I did think to bring it up because on an ops discussion call the question came up why when client closed the connection and the total elapsed time definitely went 4-5+ seconds spent talking with the backend it was odd that Kong loses that insight in the ctx.KONG_WAITING_TIME.

I notice the ```error_page``` directive of ```/kong_error_handler``` does not get called on 499's either:
```
    error_page 400 404 408 411 412 413 414 417 494 /kong_error_handler;
    error_page 500 502 503 504                     /kong_error_handler;
```

I wonder if using 499 w error_page would potentially let Kong capture that elapsed backend communication. Oh wait, no nginx disallows it it seems 😄  https://trac.nginx.org/nginx/ticket/1374 .

Kong has just about fixed all the major flaws I have seen with it for the time being besides major version changes getting a bug here and there that we will continue to report, so here I am being nit picky just pointing out tiny things as I see em such as this. One of those "not a big deal" issue since we understand internally what happens on a 499 tx, but still something that caught my eye enough to raise the issue to ponder.
