### ISSUE TITLE
/docker-entrypoint.sh: exec: migrations: not found

### ISSUE THREAD

**Issue by dinesh-kamal** [Kong/kong#6265]
### Summary

Not able to install Kong due to docker-entrypoint.sh execute migrations not found.

### Steps To Reproduce

1. Follow the steps mentioned in this page : https://docs.konghq.com/enterprise/0.35-x/deployment/installation/docker/
2. Running  docker run --rm --network=kong-ee-net \
-e "KONG_DATABASE=postgres" \
-e "KONG_PG_HOST=kong-ee-database" \
-e "KONG_CASSANDRA_CONTACT_POINTS=kong-ee-database" \
-e "KONG_LICENSE_DATA=$KONG_LICENSE_DATA" \
-e "KONG_PASSWORD=kongxx" \
kong-ee kong migrations bootstrap 
3. throw error : /docker-entrypoint.sh: line 50: exec: migrations: not found

### Additional Details & Logs

- Kong version (`$ kong version`) 2.1.0 
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system. Mac os 10.15.6

**Comment by guanlan** [comment]
@dinesh-kamal  Can you follow the last docs for our OSS version? (https://docs.konghq.com/install/docker/)

The link you posted here is from an old version of the enterprise version.  You can also open a support ticket if you are an enterprise customer.

**Comment by Zeeeeta** [comment]
![image](https://user-images.githubusercontent.com/26813698/145528177-085f8b79-9dd3-4d42-a03d-026ffca357ff.png)
https://docs.konghq.com/gateway/2.6.x/install-and-run/docker/

These instructions are confusing, step 2 looks like I can freely choose my value of {DATABASE_USER} and {DATABASE_NAME} as they are variables, but then I would not be able to run step 3.
The {DATABASE_USER} and {DATABASE_NAME} in step 2 must both be "kong" in order to match with step 3, and the last variable {DATABASE_NAME} should in fact be "kong" (which is the kong command).

**Comment by MiguelAngelVega** [comment]
I agree with the comment made by @Zeeeeta. It worked for me, documentation needs to be fixed, today the problem persists
