### ISSUE TITLE
Immutable properties in plugins

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong#630]
We need to review all the plugins, their schemas and DAOs, because certain fields should be `immutable`.

Last time when we did this we encountered many problems.

**Comment by ahmadnassri** [comment]
are we sure we're bringing value by making certain fields `immutable`? can you expand on what this accomplishes?

from #321 discussion, seems like you're aiming for credentials to be immutable?

how is that beneficial to the system administrator / API owner? seems like its just adding more steps to the same eventual result ...

**Comment by Nijikokun** [comment]
> how is that beneficial to the system administrator / API owner? seems like its just adding more steps to the same eventual result ...

:+1: From what I read in #321 it appears you will have to issue a `DELETE` (remember previous details, especially in the case of `OAuth`) and then a `POST` where a single `PATCH` would do the trick.

For OAuth in general, many security firms advocate every few months changing your keys, so this would just introduce more hurdles for everyone involved.

**Comment by thibaultCha** [comment]
There are other factors involved. For example, some fields need to be immutable because they are foreign keys to other entities...

**Comment by ahmadnassri** [comment]
> There are other factors involved. For example, some fields need to be immutable because they are foreign keys to other entities...

I'm sure some would make sense for making immutable, as you mentioned that's a good reason, the convo from #321 started with authentication/credential specific fields, so wanted to address those in particular, making sure we don't add additional work where its not needed.

**Comment by thibaultCha** [comment]
https://github.com/Mashape/kong/pull/434/files

**Comment by Nijikokun** [comment]
Foreign keys would be the identifiers, not the credentials.

**Comment by thibaultCha** [comment]
Not against that. I don't remember why those were marked immutable. @thefosk was here when we did those changes.

**Comment by thefosk** [comment]
It seems cleaner to delete the credential and re-issue a new credential instead of keep updating an existing one. Credential may also be linked to other tokens (for example OAuth 2.0 has both an `access_token` and a `refresh_token`) that we want to re-generate with a new credential (so that just updating the `access_token` doesn't create any security issue).

Just seems cleaner and less prone to errors or security mistakes.

**Comment by Nijikokun** [comment]
Security wise has same level of assurance as update, because with this you still have same level of access.

`access_token` and `refresh_token` are related to a consumer and those shouldn't have any relation to changing your applications `client_id` and `client_secret`. Because, what it sounds like is that when you want to change you will do additional actions (behind the scenes) which makes assumptions and can have unintended side effects.

**Comment by thefosk** [comment]
`access_token` and `refresh_token` are OAuth 2.0 credentials in our system. OAuth 2.0 has applications, as you mentioned (with `client_id` and `client_secret`, then authorization codes, and access tokens.

**Comment by Nijikokun** [comment]
Yes, and those are on two separate entities for a reason, changing your `client_id` and `secret` has nothing to do with re-issuing access tokens or refresh tokens. Unless the owner of the application expressly *chooses* to do that.

**Comment by thefosk** [comment]
This issue is about reviewing the plugins and the schemas to mark as `immutable` those fields that should be immutable, so it's related to something specific.

> changing your client_id and secret has nothing to do with re-issuing access tokens or refresh tokens.

Even in this case one could argue that allowing `PATCH` requests would create a security issue when, for example, the user only updates the `client_id` and doesn't update the `client_secret`. 

Also, tokens and authorization codes are [bound](https://github.com/Mashape/kong/blob/master/kong/plugins/oauth2/daos.lua#L48) to a specific credential (tokens and authorization codes belong to a credential). Deleting a credential also deletes all the tokens associated with it, while updating the credential won't do that. 

If the user wants to change the credential, the action shouldn't be "updating an existing credential", but "issuing a new credential" and revoking (aka deleting) the old one.

**Comment by Nijikokun** [comment]
They are bound to the `consumer_id` correct?

> Even in this case one could argue that allowing PATCH requests would create a security issue when, for example, the user only updates the client_id and doesn't update the client_secret.

If your major concern is that they update one but not the other, that's their concern not yours. If it bothers you that much, the implementation of the API could simply say it requires both at the same time if one is present, but then again, you shouldn't even care about it. It's not a security issue.

> Also, tokens and authorization codes are bound to a specific credential (tokens and authorization codes belong to a credential). Deleting a credential also deletes all the tokens associated with it, while updating the credential won't do that.

That's how it should be, you don't want to delete them every time you update your `client_id` and `client_secret` these are two *separate* actions.

> If the user wants to change the credential, the action shouldn't be "updating an existing credential", but "issuing a new credential" and revoking (aka deleting) the old one.

Why? There is no reason for this, even your words they want to *change* not do some round-about way of it, those are two completely different actions.

**Comment by thefosk** [comment]
> They are bound to the consumer_id correct?

Bound to the `credential_id`, since a token is being generated from a specific set of `client_id` and `client_secret`.

> If your major concern is that they update one but not the other, that's their concern not yours.

Well I think we should enforce best practices that avoid errors.

> That's how it should be, you don't want to delete them every time you update your client_id and client_secret these are two separate actions.

Updating the `client_id` and `client_secret` means changing the credential that generated that token in the first place. If a user feels like updating the credential because it was stolen, we want him to delete the credential and all the associated tokens. Not doing so creates a security issue.

> Why? There is no reason for this
For all the reasons above.

**Comment by Nijikokun** [comment]
> Well I think we should enforce best practices that avoid errors.

But this isn't a best practice, it adds nothing but gotchas.

> Updating the client_id and client_secret means changing the credential that generated that token in the first place. If a user feels like updating the credential because it was stolen, we want him to delete the credential and all the associated tokens. Not doing so creates a security issue.

No, sometimes you do it to *prevent* that from happening, not because that has happened. It sounds like you are in the mindset that something bad has *already* happened, and not thinking about *prevention* as well.

- In the case of something bad *happening* you would want to re-generate the `client_id` and `client_secret`, then revoke existing authorization / refresh tokens.

- In the case of *prevention* you simply re-generate the `client_id` and `client_secret` with no need to revoke existing tokens.

> Bound to the credential_id, since a token is being generated from a specific set of client_id and client_secret.

It shouldn't be bound to a `client_id` and `client_secret` but as an identifier of its own, like an `application_id` of the sorts.

**Comment by thefosk** [comment]
> No, sometimes you do it to prevent that from happening, not because that has happened. It sounds like you are in the mindset that something bad has already happened, and not thinking about prevention as well.

A user may want to change the credentials for many reasons. It's Kong's job to make sure that for whatever reason the user wants to do so, it will not create an security concerns, with a clear recommended practice for changing/replacing credentials.

If the user changes the credential and that creates a security issue, it's Kong to blame for not having a clear and secure way of doing that, not the user (answering to your "that's their concern not yours" line in the previous comment).

As a matter of fact, any system on the Internet allows you to replace the `client_id` and `client_secret`, but only to regenerate the application/credential.

> It shouldn't be bound to a client_id and client_secret but as an identifier of its own, like an application_id of the sorts.

The credential is the application, you can consider `application_id` and `credential_id` to be the same thing.

**Comment by Nijikokun** [comment]
> A user may want to change the credentials for many reasons. It's Kong's job to make sure that for whatever reason the user wants to do so, it will not create an security concerns, with a clear recommended practice for changing/replacing credentials.

It is Kong to ensure a *way* to do it, not *handle* it for you. A `PATCH` is the appropriate and best practice.

> If the user changes the credential and that creates a security issue, it's Kong to blame for not having a clear and secure way of doing that, not the user (answering to your "that's their concern not yours" line in the previous comment).

It is not up to Kong to ensure that you are doing everything correctly that would be absurd, sure you can take into consideration most of the cases, as I described above both *prevention* and *security breach* and give means to ensure the best line of defense against both and reaction to them, as I outlined are two separate courses of action.

> As a matter of fact, any system on the Internet allows you to replace the client_id and client_secret, but only to regenerate the application/credential.

No. In fact on Github, I can replace my credentials *and* revoke existing ones. If we want to get into examples.

![http://dump.nexua.org/Screen_Shot_2015-10-28_at_2.25.55_PM.png](http://dump.nexua.org/Screen_Shot_2015-10-28_at_2.25.55_PM.png)

> The credential is the application, you can consider application_id and credential_id to be the same thing.

Then there should be zero issue with a `PATCH`

**Comment by thefosk** [comment]
Then what GitHub does is very wrong. Resetting credentials should also automatically delete authorization codes and tokens, like Google does. LinkedIn doesn't allow resetting credentials but only generating new ones, and it seems like the best approach.

If the `client_secret` is compromised, then the `client_id` is too, including every authorization code and token generated and bound to that specific pair of `client_id` + `client_secret`.

**Comment by Nijikokun** [comment]
The `client_id` doesn't matter, you can use this in public spaces.

The `secret` is what actually matters.

Github is doing it **correctly**.

**Comment by Nijikokun** [comment]
I'm not sure what you don't understand about this. This is not beneficial and only brings drawbacks when concerning credentials.

**Comment by ahmadnassri** [comment]
security concerns are usually applied the "user"/"client" side of things, I'm not seeing anything in this conversation that relates to that. 

these are all properties are accessed through the Admin API, which in turn is considered "secure" since only the Admins should ever be allowed access.

if an "Admin" wants to expose a method in which the "user" can re-set their credentials / or in the case of oAuth `client_id` / `client_secret` then they would do so through *their own* application logic, which would have their own requirements for security beyond Kong, once all those requirements are satisfied, at that point the call to the Kong admin API is made and using PATCH is the simplest for that flow.

**Comment by ahmadnassri** [comment]
> Then what GitHub does is very wrong. Resetting credentials should also automatically delete authorization codes and tokens, like Google does. LinkedIn doesn't allow resetting credentials but only generating new ones, and it seems like the best approach.

in this scenario if Github uses Kong, then they can go ahead and do that flow as you described by issuing a DELETE, then creating new credentials ... 

and if they don't want to do that, then its also up to them.

the point here is, Kong shouldn't be opinionated.

**Comment by Nijikokun** [comment]
> the point here is, Kong shouldn't be opinionated.

Well said.

**Comment by DMarby** [comment]
An application shouldn't be made less flexible in order to try to idiot-proof something, it's a futile effort, and just makes it unusable for people who need more fine grained control. You should probably assume that the people using the API has enough knowledge in what they are doing to do it correctly, and if not try to educate them in proper ways to do it in your documentation or similar, not by enforcing arbitrary limits in your api.

**Comment by ahmadnassri** [comment]
> You should probably assume that the people using the API has enough knowledge in what they are doing to do it correctly

:clap: 

> and if not try to educate them in proper ways to do it in your documentation or similar, not by enforcing arbitrary limits in your api.

:+1:

**Comment by bungle** [comment]
I close this as #4381 implements it.
