### ISSUE TITLE
QUESTION: kong with rabbitmq

### ISSUE THREAD

**Issue by sptGabriel** [Kong/kong#6301]
Hello
i'm new to kong and i would like to know if it is possible to make an "api manager"

where I have 2 services
service A and service B

and my kong would work as the api manager with messaging to go to my service A and my service B

using rabbitmq, I don't know if this is the right place, but I didn't find anything about it.

If anyone can help me I am grateful

**Comment by fairyqb** [comment]
The KAFKA is the best choice.

https://github.com/doujiang24/lua-resty-kafka

**Comment by kikito** [comment]
I am very familiar with rabbitmq. Giving a cursory look at its [protocols page](https://www.rabbitmq.com/connections.html), it seems they use TCP underneath. Kong has been able to route TCP traffic (also called *stream* traffic in the docs) since Kong 1.0. Here's the announcement: 

https://konghq.com/blog/tcp-stream-support-kong/

If your intention is just sending rabbitmq commands directly to Service A and B, Kong should be able to route traffic to both of them.

The setup steps needed for stream routing in Kong has not changed significantly in Kong 2.0 so you should still be able to adapt the steps from the link above. Set 1 or 2 Kong services, and then add a Route for Service A and another for Service B. To use TCP, the Routes will need `protocols`=`["tcp"]` and the `destinations` property pointing to the IP:port of each Service. If you need TLS, then the `protocols` property should be `["tls"]` and you might need to set the `destinations` or `snis` property.

See the [Route Object Admin API page](https://docs.konghq.com/2.2.x/admin-api/#route-object) for more information about what every field does.

**Comment by kikito** [comment]
> The KAFKA is the best choice.
>
> doujiang24/lua-resty-kafka

I'm afraid I am not knowledgeable about how rabbitmq interacts with Kafka, exactly. However, I must point out that the link you provided is a Lua library. Using it inside Kong would require some programming (a custom plugin of some sort).

While that's an option, it will require work. Kong Enterprise offers a more [turn-key solution](https://docs.konghq.com/hub/kong-inc/kafka-upstream/) which allows transforming plain HTTP requests into topics on a Kafka topic, and [another one](https://docs.konghq.com/hub/kong-inc/kafka-log/) which allows using a Kafka topic as a log service.

**Comment by javierguerragiraldez** [comment]
closing for lack of author feedback.   feel free to reopen if there's something new on this subject
