### ISSUE TITLE
Redact JWT Tokens from logs

### ISSUE THREAD

**Issue by nafpliot** [Kong/kong#6312]
### Summary

Hey. It seems that when Kong logs the requests the `request.headers.authorization` is logged revealing the bearer token. Is there a way for this to be redacted? It might not be that bad but for security and privacy reasons it would be a good idea to have the option to disable token logging.

There are some thoughts on how to do it, eg. reroute logs to syslog in the container, and then use syslog's manipulation capabilities. But I would like to hear of other ideas, or if there is a planned feature to come. We currently use the file-log plugin btw.

**Comment by jeremyjpj0916** [comment]
Community member here,

Yep, by default Kong logs http headers I believe, we took the approach with one of our logging plugins to just log API Tx metadata and never headers/bodies directly: https://github.com/Optum/kong-splunk-log . Other ideas we are playing with internally are:
1. Start logging a sha or hash of the tokens (oauth2.0 or jwt)

This we think could be helpful because while capturing the tokens in logs might be a security concern, if you could have a sha, then you could still look into the timings of token utilization, how a customer is doing token reuse over time or leveraging a token that you know would have had an expired TTL based on 200 successes vs 401(due to expiry). Or if the hash was missing from your logs you know they forgot to pass a token value. 

Undecided on if I think vanilla Kong should be offering these configs, but an optional variable in plugins or generalized config(to apply to all logging plugins) to hide security headers(authorization being one of them) may be a PR they would consider.

**Comment by hishamhm** [comment]
Unless I'm missing something, this feature is already available since Kong 2.1 :)

https://github.com/Kong/kong/commit/46bf8b8a0b37d4f4cf2e1ce3850372489ff3599a

Logging plugins that use the PDK function `kong.log.serialize` to build the logging output auto-redact `authorization` and `proxy-authorization` headers.
