### ISSUE TITLE
Kong proxy cache increase day by day

### ISSUE THREAD

**Issue by ehdieunguyen** [Kong/kong#6343]
### Summary
We are using Kong as a gateway and running four instances to serve the request. We are monitoring, exposing, collecting the proxy's metrics by Prometheus, and showing them in Grafana. We are perceiving that the proxy cache size per instance increases day by day, not have any pieces of evidence to stop or decrease. We have many deployments per day. However, the total number of instances in our system does not change. Therefore, I think that the proxy cache size is weird. 
So, it is better for anyone help me explain why that is and give a fix. Thank you so much.

![Screen Shot 2020-09-15 at 10 44 17 PM](https://user-images.githubusercontent.com/39895269/93236977-afd92a00-f7a9-11ea-8791-f4e57451fd6f.png)

![Screen Shot 2020-09-15 at 10 39 06 PM](https://user-images.githubusercontent.com/39895269/93236943-a2bc3b00-f7a9-11ea-9de8-2a8ddca1ef1c.png)

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`2.0.3`)
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (the output of a GET request to Kong's Admin port - see
  https://docs.konghq.com/latest/admin-api/#retrieve-node-information)
- Operating system

**Comment by kikito** [comment]
Hello, the issue you are experiencing could be due to a lot of factors. It would help us immensely if you could help us narrow them down - any information that you can help us replicate your issue would be really appreciated.

* Could you give us more details about your setup (number of Kong instances, operative system, etc)?
* Do you use a database, or are you using Kong in db-less mode?
* Are you running any other plugins besides Prometheus? Which ones?
* I've noticed that your memory increases seem to happen at certain discrete points in time (the top graph has "steps"). Do the increases align with any particular events (i.e. periods of high traffic, usage of any plugin?

**Comment by ehdieunguyen** [comment]
@kikito thank you for your reply. Let me narrow them down

> Could you give us more details about your setup (number of Kong instances, operative system, etc)?
- Kubernetes version `v1.16.7`
- Kong version `2.0.3`, based on `kong:2.0.3-ubuntu` docker image
- Deploy kong and kong ingress controller `0.8.1` via kong helm chart version `1.5.0` 

> Do you use a database, or are you using Kong in db-less mode?
Yes, we use the PostgreSQL database.

> Are you running any other plugins besides Prometheus? Which ones?
Yes, there are some plugins: 
- the builtin plugins: cors(use for all services), rate-limit(use for only one service), prometheus as a global plugin
- 3 custom plugins, however, those plugins are to handle logic only, do not use cache anywhere.

All of the used plugins are managed by Kong ingress controller

> I've noticed that your memory increases seem to happen at certain discrete points in time (the top graph has "steps"). Do the increases align with any particular events (i.e. periods of high traffic, usage of any plugin?

This below image shows the incoming requests pattern to our system. 

![Screen Shot 2020-09-17 at 8 34 46 PM](https://user-images.githubusercontent.com/39895269/93477465-3e25eb00-f925-11ea-908b-ae36ebb7ef48.png)

**Comment by kikito** [comment]
Possibly related with #6362

**Comment by ehdieunguyen** [comment]
@kikito Yeah, I hope that. It is because I do not get any clues on the relation between the two issues, this one and #6362  Therefore, I report that as another issue.

**Comment by ehdieunguyen** [comment]
@kikito, have any updates on this issue?

**Comment by Am1NuL** [comment]
@ehdieunguyen Hello, I just stumbled upon this issue while researching more about nginx shared memory and remembered that I read something that may be exactly why you are experiencing this behaviour which could be 'Fake Memory Leak'. You can check more about this topic here -> https://blog.openresty.com/en/how-nginx-shm-consume-ram/#fake-memory-leaks .
Hope this is helpful xD

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
