### ISSUE TITLE
How to build Kong in FIPS mode

### ISSUE THREAD

**Issue by sumantfordev** [Kong/kong#6355]
Looking for FIPS compliant mode of Kong. Is openssl the only piece that can make kong run with FIPS certified libraries. Are there any modules that shouldn't be used in FIPS Mode.?

**Comment by kikito** [comment]
Kong does not have a built-in "FIPS compliant mode" or flag that you can set during build time or runtime in order to make it FIPS-compliant. Given that Kong is open source you might be able to code that feature yourself. You might need to build other underlying dependencies with FIP in addition to OpenSSL, for example OpenResty, PostgreSQL and/or Cassandra.
