### ISSUE TITLE
I have a question about grpc

### ISSUE THREAD

**Issue by AP0rPi7uQ9** [Kong/kong#6530]
Please forgive me for asking questions here, because I cannot find other places to ask questions

My question:
I know that kong can add grpc microservices,
Therefore, Kong can convert http into rpc and pass it to microservices.
However, my microservice returns rpc,
How does kong pass the rpc returned by the microservice to the http client?

Drawing:

Request:
HTTP Client    ==(http)==>     Kong     ==(rpc)==>     Grpc Microservices

Response:
Grpc Microservices    ==(rpc)==>     Kong     == ??( I do not know what to do, kong support??  )??==>     HTTP Client

**Comment by javierguerragiraldez** [comment]
hi @AP0rPi7uQ9 

Yes, Kong can bridge between HTTP and gRPC systems, but to do that you have to specify exactly how to translate.  Remember that gRPC is a procedure call protocol and HTTP is a data transfer protocol.  Even if you use REST to manage services, you'll find that most REST "gurus" will emphatically tell that "REST is not RPC"

So, in order to interoperate, you need a full description of the protocol and API on both sides.  For gPRC, you need the ".proto" file that describes the structures and methods of your services.   For the HTTP side there's a lot more variation.  We have two main solutions:

- Encapsulate the gRPC protocol inside HTTP requests.  That's how gRPC-Web works to allow Javascript browser apps to access gRPC services.   Take a look at [the gRPC-Web plugin](https://docs.konghq.com/hub/kong-inc/grpc-web/).  You'll proabably need the JS [gRPC-Web library](https://github.com/grpc/grpc-web).

- Add "annotations" to the ".proto" file to describe REST-like URLs for each gRPC method.  This approach is used by Google, and we support it via the [gRPC-gateway plugin](https://docs.konghq.com/hub/kong-inc/grpc-gateway/)

**Comment by AP0rPi7uQ9** [comment]
thank you very much! You made me understand kong better
