### ISSUE TITLE
plugin update is not real-time

### ISSUE THREAD

**Issue by TXYH1** [Kong/kong#6531]
### Summary

Hello,I implemented a simple go custom plugin to filter some URLs, For example, URL requests with a Prefix suffix are prohibited. But when I update the prefix and suffix fields of the plugin through Konga, it takes a long time to take effect.

Even if I remove the plug-in and reset it, Kong still uses the old configuration. Although the fields in plug-in information obtained through curl have been updated, the data printed by Kong's log is still the old configuration information.

### Steps To Reproduce

1. Create a custom go plugin 
2. Add it to the active plugins list KONG_PLUGINS=bundled,filter
3. Run kong
4. Modifying plug-in information from Konga
I also try to operate the plug-in through the rest API, but there are the same problems

Kong version: kong:2.0.4-alpine - Running in docker.

I didn't find the reason for this problem. I don't know if I didn't operate correctly. Could you help me, thank you

**Comment by javierguerragiraldez** [comment]
Hi  @TXYH1  are you running Kong in dbless mode?  (i'm not familiar with konga but seems to be just a frontend to the admin API)

**Comment by javierguerragiraldez** [comment]
I can't reproduce this issue.  if you still have this problem please reopen with more details.

**Comment by TXYH1** [comment]
I'm sorry I didn't notice your reply.
My Kong has a database, and I use postgre，And the migration command provided by Kong is executed.
and the version of pluginserver is 0.5.1

**Comment by TXYH1** [comment]
When the plug-in will be updated is very uncertain. Sometimes it takes more than ten minutes, sometimes it takes several hours. It seems that only by restarting the Kong plug-in can it be updated faster

**Comment by TXYH1** [comment]
@javierguerragiraldez  
And I found that when I update the plugin, the database and kong cache are updated, but the log output by the plug-in is still the old field value

**Comment by TXYH1** [comment]
@javierguerragiraldez Hello, how can I reopen this issue? I didn't find the relevant button

**Comment by javierguerragiraldez** [comment]
Hi, @TXYH1 

To recap the issue, as I understand it:

- you're using Kong 2.0.5 and go-pluginserver 0.5.1  in an Alpine Linux Docker image with PosgreSQL config.
- your "filter" plugin seems to work well.
- when you change the configuration, either with the REST API or via Konga, your plugin doesn't get the update until some undefined time later.

did I miss anything?

A bit of explaining: 

the Kong configuration, either declarative (in a YAML file) or DB-based, allows you to specify more than one configurations for a single plugin.  In Go, they're managed by different instances of your `Config` structure.

Creating those instances requires a bit of extra traffic between Kong and to go-pluginserver, so they're kept and reused.  If there's no DB changes, they're only recycled after some period of inactivity.

When there's a change in the configuration, the next request after the DB commit should notice the change and create a new instance of the Go plugin.  This part of the code has some changes since 2.0.5; mostly related to the multiple-instances case but the fixed issue could also affect other cases (especially with multiple Kong workers).

My guess is that the update event is lost somehow, and the new configuration is only loaded after they're recycled because of inactivity.

Can you update your Kong version?   the whole non-Lua plugins is still young and we get stability improvements with every version.

**Comment by TXYH1** [comment]
OK, I'll try to see if the higher version of Kong can solve this problem. thank you

There is also a small problem. Will the migration commands of Kong images of different Linux distributions differ greatly? If they are used differently before and after the migration, will there be any problems

**Comment by TXYH1** [comment]
In the higher version of Kong, an error has been reported that plugin is enabled but not installed. The same configuration can be run in 2.0.4 Kong. But in 2.3 Kong, I tried to use 0.5.0 go pluginserver and old style configuration, or 0.6.0 go pluginserver and new style configuration, but they didn't work. It may take time to study and see why

**Comment by javierguerragiraldez** [comment]
> In the higher version of Kong, an error has been reported that plugin is enabled but not installed

Yes, we've seen a regression on the "old style" configuration.  fixed by #6981
