### ISSUE TITLE
Question: Why OpenResty as a base instead of Envoy?

### ISSUE THREAD

**Issue by APIs4All** [Kong/kong#6658]
OpenResty is a great platform for a Gateway, but Envoy is being widely adopted by the industry as a Proxy and Gateway as well with great success. What made kong choose to go with/stick with OpenResty compared to Envoy? In addition, Kuma Mesh is built on top of Envoy, so has there been any thought to consolidating the stack around Envoy for the N-S traffic as well, or are there reasons that OpenResty is still preferred for the N-S Gateway?

**Comment by subnetmarco** [comment]
OpenResty is quite a solid and performant networking primitive for Kong (built on top of Nginx) that has served us well in pretty much every environment and with every load, in certain instances even faster than Envoy itself, and especially resilient when used at the edge. As a matter of fact Kong has full ownership of the entire stack - including the OpenResty/Nginx core - that we regularly expand/modify with obsession and dedication to build the best API gateway the world has ever seen (to do this, we are also official OpenResty maintainers).

And in order to build the best API gateway, what matters really is what sits above and beyond the underlying core networking proxy: the plugins, the API, the native Kubernetes resources and all the features that Kong provides. So a better question to ask is: what would Envoy proxy be doing that OpenResty cannot currently do in a performant and reliable way with its current core?

Ultimately, regardless of what proxy technology it is being used, the philosophy of Kong is to provide a nice user experience above it, in a way that end user should never worry about the low level primitives of the overall solution. With that said we are also strong believers in Envoy as well, as its use in Kuma demonstrates, and we provide a flawless integration and a good user experience that allows to integrate both of them together without exposing the complexity of the underlying commoditized networking primitives. Even in Kuma, like in Kong GW, the underlying Envoy proxy runtime is abstracted away so that we can focus on delivering high-value service mesh features in a capable - yet easy to use - product.

Hope this answers your question :)
