### ISSUE TITLE
Questions about how to use rate-limiting-advanced plugin

### ISSUE THREAD

**Issue by xuyang1996** [Kong/kong#6723]
```
config.sync_rate

How often to sync counter data to the central data store.
A value of 0 results in synchronous behavior; 
a value of -1 ignores sync behavior entirely and only stores counters in node memory. 
A value greater than 0 will sync the counters in the specified number of seconds.
```

I have deployed kong in the k8s and i wanna set config.window_size = 60 and config.limit = 10. (1min / 60request)

My question is here:

If i have 3 kong pods, kong can accept 1min / 180request with config.sync_rate = -1 and can accept 1min / 60 request with config.sync_rate >= 0

Is my understanding correct???

**Comment by locao** [comment]
Hi @xuyang1996! 

When using `config.sync_rate = -1 `, if the requests are perfectly distributed among the Kong pods, yes, you might get up to 180 requests per minute in total. 

When you use `config.sync_rate` with a value greater than `0` it depends on how large is the value configured. It's a balance between how much resources you are willing to spend syncing data among pods and how strict you require the limit to be. For instance, if you set `config.sync_rate = 10`, pods will get synced every 10 seconds, if your pods receive a burst of requests during this 10 seconds interval, they might answer up to 180 requests too. That's why you have to choose between spending time consulting the counters or having a less strict limit.

I'm closing this issue now, please feel free to open a new one if you find any problems with this configuration. You may use [Kong Nation](https://discuss.konghq.com/) to ask questions as there several experienced users there who may have good insights on how to get the most from your environment.
