### ISSUE TITLE
Using Nginx ingress controller for Kong Gateway

### ISSUE THREAD

**Issue by RagunathInGIT** [Kong/kong#7067]
Hi,

Is there a way that I can use Nginx ingress controller for my Kong gateway to proxy the traffic instead of using Kong Ingress controller.

I see this option in the values CR file.

**# Kong proxy ingress settings.
    # Note: You need this only if you are using another Ingress Controller
    # to expose Kong outside the k8s cluster.**
    ingress:
      # Enable/disable exposure using ingress.
      enabled: false
      hosts: []
      # TLS section. Unlike other ingresses, this follows the format at
      # https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
      # tls:
      # - hosts:
      #   - 1.example.com
      #   secretName: example1-com-tls-secret
      # - hosts:
      #   - 2.example.net
      #   secretName: example2-net-tls-secret
      # Map of ingress annotations.
      annotations: {}
      # Ingress path.
      path: /

    externalIPs: []

In our case, we have nginx controller running in different namespace and Kong Gateway running in another one. Will that work if I make any changes to the CR?

**Comment by shereef-adekunle** [comment]
I would like to do the same here. I have kong proxy, kong admin , and kong-manager deployed within Google Kubernetes Engine and when I try to secure the endpoints I get a 400 Bad Request error, The plain HTTP request was sent to HTTPS port. My assumption is this has to do with the Kong ingress controller. No matter what configs I place in the yaml file I'm getting that same 400 Bad Request Error. So I want to use nginx ingress class instead of kong's. I believe nginx will finally allow http to https redirect and I can reach kong-admin and kong-manager securely.
