### ISSUE TITLE
[Feature-Request] Request tracing support for Kong's log pdk

### ISSUE THREAD

**Issue by rishabh-gupta2** [Kong/kong#7130]
### Summary
Kong provides functionality for distributed request tracing with the use of plugin `correlation-id`.
While it supports sending headers to upstream and downstream, Kong's log pdk does not make use of the correlation-id. Would it make sense to have request tracing functionality within Kong's logging pdk?

If the plugin is enabled, the logging pdk can use the trace id set in shared ctx. If not enabled, the pdk can function the same way. This would definitely require some changes in the plugin itself like changing the priority order (moving it up the execution order) and setting its trace id as part of shared request ctx.

What are your thoughts on this?

**Comment by bungle** [comment]
@rishabh-gupta2, AFAIK we added extensible log serializer, so I guess best option would be to make `correlation-id` plugin to add that field to serializer?

**Comment by rishabh-gupta2** [comment]
The requirement is to add request tracing support to usages such as `kong.log.info('sample', 'log')`, `kong.log.err('error', 'log')`. Extending the log serializer won't really work as it is only valid for usages of `kong.log.serialize()`.  Moreover `kong.log.serialize()` IMO is a heavier operation as compared to `kong.log.info`, `kong.log.err`

**Comment by kikito** [comment]
@rishabh-gupta2 Kong currently supports changing the log format through Nginx variables (see the `log_format` option described here: https://docs.konghq.com/gateway-oss/2.4.x/logging/#removing-certain-elements-from-your-kong-logs).

If I understand correctly what you would need is an extra nginx variable set by the correlation_id plugin so that it can then be included in the `log_format` option. Is that correct?
