### ISSUE TITLE
DomainMapping with Knative

### ISSUE THREAD

**Issue by mt35-rs** [Kong/kong#7450]
### Summary
- Kong version: 2.1.0 (according to Helm chart)
- Bad request when using `DomainMapping`

### Steps To Reproduce

1. Install [Knative Operator](https://knative.dev/docs/install/knative-with-operators/)
2. Install Knative [`DomainMapping` extension](https://knative.dev/docs/install/install-extensions/#install-optional-serving-extensions)
3. Install Kong (via Helm chart)
4. Create a `KnativeServing` resource
5. Create a  `serving.knative.dev/v1` `Service` resource
6. Confirm Kong properly handles requests for the Knative `Service` (it does, returns "200 OK").
7. Confirm custom domain gives "no Route matched with these values" response before domain mapping
7. Create a `DomainMapping` resource to the existing Knative `Service`
8. Requests for custom domain now give "400 Bad Request".

### Additional Details & Logs

When making the direct response using the domain template to construct the URL, I see the following in the `proxy` container logs:

```
10.240.0.4 - - [12/Jun/2021:12:46:12 +0000] "GET /?bustCache=0.9222607357396713 HTTP/1.1" 200 20 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
20
```

So that part is great.  However, when I put the `DomainMapping` instance in place and I make a request to the custom domain, I see this:

```
10.244.1.1 - - [12/Jun/2021:12:53:39 +0000] "GET /?bustCache=0.8193610545267835 HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
10.244.1.1 - - [12/Jun/2021:12:53:39 +0000] "GET /?bustCache=0.8193610545267835 HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
10.244.1.1 - - [12/Jun/2021:12:53:39 +0000] "GET /?bustCache=0.8193610545267835 HTTP/1.1" 400 12 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
... // probably repeated at least 100 times
```

You can see from the `bustCache` query parameters, there is just one request (because that is randomly generated on each request) but it is getting "bounced around" or retried or something.

My `DomainMapping`  instance is very simple and it is placed in the same `test-functions` namespace as the `Service` resource:

```
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  # Not the actual hostname, but representative...
  name: www.example.org
  namespace: test-functions
spec:
  ref:
    name: test
    kind: Service
    apiVersion: serving.knative.dev/v1
```

After adding this, I see now issues in the logs for the `domain-mapping` deployment pods or its associated webhook pod.

The `DomainMapping` resource is shown as `Ready` a few seconds after I add it.  I also see an `Ingress` created in `networking.intenal.knative.dev` as well.

Does Kong support `DomainMapping`?  The fact that Kong's response changes from "no Route" to "Bad Request" seems to imply _something_ is happening here (_i.e.,_ it isn't totally ignoring the `DomainMapping`).

At the end of the day, all I want is to map a custom domain to a Knative `Service`.  I suspect there is some Kong-specific way to achieve this but I've tried a few things and haven't been successful.  So if anybody can point me to some specific documentation on how to route requests for a specific (custom) virtual host to a Knative `Service`, I'm all ears.

Thanks.

**Comment by rainest** [comment]
Not sure offhand. I don't know whether Knative implements DomainMapping support independently of the controllers (e.g. KIC) that then add routing configuration for the Ingress resources Knative creates on your behalf. Between my knowledge of how Knative handles Ingress configuration without DomainMapping and the observed change from a 404/no route response to a 400 here, I suspect that we don't need to implement anything additional for DomainMapping to work.

Without DomainMapping, you set up a [default domain](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/using-kong-with-knative/#setup-knative-domain) and Knative creates Ingresses for each Service it handles as subdomains on that domain. I suspect it handles DomainMapping by just overriding that default domain on a per-Service basis, and as such the upstream controller that consumes the generated Ingress configuration doesn't need to be aware of DomainMapping itself.

What's in the body of the 400 response? Since you're not seeing a 400 already when you have no route, I suspect this isn't something inherently wrong with your request, but rather some transformation applied by the Kong proxy that the upstream service doesn't like. Errors from that service's logs and/or the response body should hopefully clarify what that problem transformation is.
