### ISSUE TITLE
Custom authorization in Kong

### ISSUE THREAD

**Issue by reetik-raj** [Kong/kong#7518]
We wanted to move our company's custom authorisation to Kong. Currently we have an internal table which maps URLs to scopes and using the request URL and consumer details we are able to authorise the request. We want to move all this to Kong.
 
We need to maintain a table on Kong level which has the different scopes associated with the different URLs. Calling another service to get the scope is also one solution for this. Any suggestions or recommended methods for this?

**Comment by kikito** [comment]
Good morning, you should be able to accomplish what you need by creating a _Custom Plugin_.

The Custom Plugin Development Guide is here:

https://docs.konghq.com/gateway-oss/2.4.x/plugin-development/

Plugins can have migrations (on db mode) and custom entities (both on db and db-less modes) which could be used to map your scopes and how they map to each consumer.

Since you are doing an auth plugin, it will probably be a good idea to give a look at the [Basic Auth Plugin](https://github.com/Kong/kong/tree/master/kong/plugins/basic-auth) source code, or even use it as a base for your own plugin.
