### ISSUE TITLE
Proxy container lose its config when oom killed inside the kong pod with an ingress controller setup

### ISSUE THREAD

**Issue by dje4om** [Kong/kong#7541]
### Summary
- Kong version `2.4.1`
- Ingress Controller `1.3.1`

As the proxy container could have limits (ram), it could be oom killed by kubernetes. When this occurs, only the proxy container is restarted inside the kong pod (as expected), and ingress controller is still alive. At this state, the proxy lose its configuration but accept the traffic. (at least with default readiness configuration in values.yaml from helm charts)
If the entire pod is deleted and recreated, everything works fine, the ingress controller POST the ingress configuration to the proxy.

We encounter the issue when we defined default "proposed" limits from the helm charts (256Mi), and this is very low according to the sizing guide, a small load test revealed the behaviour.
Of course, we resized this, but it could still happen if we define a memory limit.

Not sure if it's proxy or ingress controller role to ensure this when proxy container is restarted but it seems while debugging that it could be improved in this kind of setup.

Thx for your help

### Steps To Reproduce
It's easy to reproduce as killing the proxy container intentionnaly

1.Deploy kong proxy with ingress controller with at least one ingress with the kong class
2.Kill the proxy container of at least 1 pod, if you have N replicas of kong, you should see the config lost by alternance due to load balancing on kong proxy `kubectl exec <kong-pod> -c proxy -n <namespace> -- killall nginx`

### Additional Details & Logs
- Kubernetes `1.19.3`

Setup is simple : ingress controller + proxy in kubernetes native mode (dbless), 1 ingress for 1 route, no plugins or advanced configurations.
status is enabled with liveness/readiness configured like the example : https://github.com/Kong/charts/blob/main/charts/kong/values.yaml

**Comment by bungle** [comment]
I think dbless nodes do keep the previous config they received, but I am not sure why it fails in this case.

**Comment by dje4om** [comment]
after reproducing the steps, you should be able to see like this : 

_* targeted pod below is pod where you killed the proxy container to reproduce the behaviour_
- at least 1 restart count on the proxy container  `kubectl describe <kong-pod> -n <namespace>`
- port-forwarding on the pod  `kubectl port-forward <kong-pod> -n <namespace> 8444:8444`
- `curl -ks https://localhost:8444/config | jq .`

and so, after this occurs, proxy "config" is empty while we expect to see ingress configuration "posted" by the ingress controller

it's coherent in the sense that the container is ephemeral and so, the config of the proxy disappears, but maybe a mechanism could allow to avoid that by making sure that the proxy container is able to recover its configuration that the ingress controller has provided it or should not go in traffic in this state.

by example, in this state of the proxy, if you edit the concerned ingress kubernetes object and make a change `kubectl edit ing <ingress>` , everything come back to normal, ingress controller see the ingress change, and push it to the proxy

**Comment by rainest** [comment]
> I think dbless nodes do keep the previous config they received, but I am not sure why it fails in this case.

Through what mechanism? AFAIK we don't store it anywhere on disk, so if PID 1 goes all its memory goes along with it.

In hybrid mode DP nodes do store a `config.cache.json.gz` under KONG_PREFIX, and I believe they load this at start while awaiting their first CP contact. Standalone DB-less nodes don't have the same, however. If we could enable the same cache mechanism for them, it should solve this issue, as the temporary volume we use to hold KONG_PREFIX is bound to the Pod, not the containers: if a container does restart, its replacement will see files its predecessor left behind, and would be able to load the previous cached config.

Adding a more meangingful readiness endpoint (i.e. some endpoint to indicate if an instance has successfully loaded configuration for DB-less) to the status listen could also help here, though it'd be less useful. Kubernetes would take some time to recognize this state and the instance wouldn't recover on its own, so that's probably only of interest as an add-on to loading from disk cache, to disable instances that, for whatever reason, cannot load config cache.

**Comment by HansK-p** [comment]
This bug report was very useful for us and we have what seems to be the same issue. This issue is extremely problematic as it means that once in a while our applications with a Kong Ingress controller in front "suddenly" stops working - and we have to restart the Kong Ingress controller manually.

I believe that detecting this problem in a health check can be a correct first approach. It is a valid (and wanted) design to not accept traffic to pods that doesn't work (readiness) and kill them if they don't recover (liveness).

I'd say that finding a way to solve this problem ought to get priority as the Kong Ingress Controller (helm chart) isn't really production ready until this problem has been solved.

**Comment by HansK-p** [comment]
It looks like it is an option to use the reverse sync flag to make sure the Kong config is updated after a Kong restart. I assume the challenge with this workaround is that the config will be pushed frequently also when there is no need to do so. Taking a performance hit might still be better than running the proxy with a broken/missing configuration.

<pre>
	// disable optimization if reverse sync is enabled
	if !reverseSync {
		// use the previous SHA to determine whether or not to perform an update
		if equalSHA(oldSHA, newSHA) {
			if !hasSHAUpdateAlreadyBeenReported(newSHA) {
				log.Debugf("sha %s has been reported", hex.EncodeToString(newSHA))
			}
			log.Debug("no configuration change, skipping sync to kong")
			return oldSHA, nil
		}
	}
</pre>

**Comment by HansK-p** [comment]
I didn't see this one until now. This issue was also reported as a problem https://github.com/Kong/kubernetes-ingress-controller/issues/861 in September 2020.
The suggested solution is to set CONTROLLER_ENABLE_REVERSE_SYNC to true (as we've done). But I also see that this generates some error logs that I don't like. It has still bee working for us, so might be those errors can be ignored.

What we get is:
<pre>
2022/03/30 16:50:25 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/counter.lua:33: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:26 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/counter.lua:33: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:27 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/counter.lua:33: 4096 lua_max_running_timers are not enough
127.0.0.1 - - [30/Mar/2022:16:50:27 +0000] "POST /config?check_hash=1 HTTP/1.1" 429 54 "-" "Go-http-client/1.1"
2022/03/30 16:50:28 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/counter.lua:33: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:29 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/counter.lua:33: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
2022/03/30 16:50:30 [alert] 1117#0: lua failed to run timer with function defined at @/usr/local/share/lua/5.1/resty/timer.lua:59: 4096 lua_max_running_timers are not enough
</pre>

**Comment by HansK-p** [comment]
It seems this problem has been solved by the latest Kong Ingress Controller release, ref. https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#230. I've applied and slightly tested the updated Kong Ingress Controller in one cluster, and it seems the problem has been solved.

There is a problem with a livenessprobe with the new Helm chart, but that problem is luckily easy to work around - https://github.com/Kong/kubernetes-ingress-controller/issues/2435.
