### ISSUE TITLE
How to get response body in post-function plugin? like get JWT or rate-limiting plugin return response body.

### ISSUE THREAD

**Issue by XJShane** [Kong/kong#7573]
when i call kong.service.request.enable_buffering() on `rewrite`,  call local body = kong.service.response.get_body() in body_filter() phase，it's cause a error: 
```
2021/07/19 16:48:10 [error] 7903#0: *2305 failed to run log_by_lua*: [string "local body = kong.service.response.get_body()"]:1: service body is only available with buffered proxying (see: kong.service.request.enable_buffering function)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/pdk/service/response.lua:308: in function 'get_body'
	[string "local body = kong.service.response.get_body()"]:1: in function 'func'
	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:26: in function 'f'
	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:59: in function 'log'
	...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:124: in function <...cal/share/lua/5.1/kong/plugins/pre-function/_handler.lua:123>
	/usr/local/share/lua/5.1/kong/init.lua:249: in function 'execute_plugins_iterator'
	/usr/local/share/lua/5.1/kong/init.lua:1240: in function 'log'
	log_by_lua(nginx-kong.conf:96):2: in main chunk while logging request, client: xxxx, server: kong, request: "GET /demo HTTP/1.1", host: "xxxxxx:8000"
```

Kong Version: 2.2.0

it's there wrong for the `kong.service.request.enable_buffering()` use or it's ther have other API can get the response body? 
Hope anybody can answer my question, thanks~

**Comment by kikito** [comment]
Hello @XJShane, there's two things you need to know.
* First one is that the place to get the full buffered body when `buffered proxying` is active is inside the `response` phase (not on the `body_filter` phase).
* At the same time, the post-function plugin is still not capable of fully using this feature, since it has no `response` phase. A plugin can not have both `response` and `header_filter` or `body_filter` active at the same time. The reasons are very implementation-dependent. We are aware about this limitation and currently working on providing alternatives for this.

In the meantime, if you really want to get the body of a response in the post-function plugin, you have to use the `body_filter` phase, without activating proxied buffering. On that mode, the response body is divided into chunks, and put into `ngx.arg`. `body_filter` gets invoked once per chunk (several times per request). Using `ngx.arg` you can aggregate the whole body once the last chunk gets passed around, and then use it.

Here's an example of a custom plugin which aggregates the chunks and when the last one is received, it concatenates them, uppercases them and sends them over.

https://github.com/Kong/kong-plugin-uppercase-response/blob/master/kong/plugins/uppercase-response/handler.lua#L10

**Comment by XJShane** [comment]
@kikito Thanks for you feeback, since JWT or Rate-limiting plugin return 401&429, then the access phase don't excute in post-function plugin.  If i have a custom plugin and PRIORITY = -900, it's possible that my custom plugin excute the access or response phase? then i can get the response body in response phase.
