### ISSUE TITLE
Incorrect interpretation in NGINX state

### ISSUE THREAD

**Issue by RyanSiu1995** [Kong/kong#7680]
kong_nginx_http_current_connections{state="total"} is not representing the "total connections". Instead, it represents the total request handled by the NGINX. Within one accepted connection, there may be more than one request. 
The wording total is misleading to most of the developer. They may think it is a total connection instead of total request.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
