### ISSUE TITLE
Enhance Metrics to filter based on verbs and URI(s)

### ISSUE THREAD

**Issue by sumantfordev** [Kong/kong#7681]
Enhance Metrics to filter based on verbs and URI(s)
Currently the http codes counter metrics, bandwidth and latency metrics are generated per service, and route.
Can this be enhanced to generate metrics per http method( POST/GET etc) and per URI. Like if the route has uri like /users/[*] , then it will create metrics report for all api(s) /users/all or /users/<some user id>
Expectation:
kong_http_status{code="200",service="api-1",route="api-users", verb="GET" Uri="/users?emailid=someemail@domain.com"} 16

**Comment by esatterwhite** [comment]
I very much want this too. Its particularly useful around latency. A particular service may have many endpoints and understanding which is causing a service to yield high latency, or memory usage would be amazing. I wouldn't call this logging. its request time/latency grouped by (method, uri). 

The thing we have to do now create start + end timestamps around endpoint handlers, log them, and create dashboard graphs from that, Which is really what metrics are for. Kong has all of this information when its recording the metrics. 

In fact we've started pulling it out of logs and implementing it as manually tracked metrics to Prometheus. It would save a ton duplicated efforts across a service oriented architecture to have that handled by our api gateway.

**Comment by esatterwhite** [comment]
![image](https://user-images.githubusercontent.com/148561/132414578-5a3e1012-dda0-4c6e-8a11-14cc898e1521.png)

**Comment by esatterwhite** [comment]
> HTTP verbs/methods are open-ended. There are standard methods but there is nothing in the HTTP spec stopping you to define your own `FOO` method.
> 

Why would that make a difference? kong doesn't really need to care what they are to add it as a label

**Comment by sichvoge** [comment]
@esatterwhite Do you have a more concrete example on how your Prometheus metric looks like? That would help us better understand what others have done in that space. Also, how is your cardinality using all these labels (e.g. you could look at the TSDB Stats page)?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Comment by jrapipana** [comment]
Is there any chance of reopening this ticket?

I understand that there is concern about unbounded labels, but perhaps this can be managed somehow?


For example, we could configure a list of supported HTTP verbs (defaulting to a list of standard ones - GET, POST, PUT, DELETE... etc).

The URI label could be enabled optionally too, and could perhaps only contain details path matcher that the request matched, rather than a real URL path. 

Taking the example in the OP's message, we could have something like this (stripping out the the parameters from the URI):

`kong_http_status{code="200",service="api-1",route="api-users", verb="GET" uri="/users"}` 


In a worst case scenario, this would limit the maximum number of metrics being exported to: 

`Number of supported HTTP verbs * Number of configured Kong Routes.` 

However, in a real scenario it would likely be much lower
