### ISSUE TITLE
Service retries counter

### ISSUE THREAD

**Issue by atikhono** [Kong/kong#7682]
Hello, thanks for the great plugin! We would like to monitor service retries as well. Looks like it's not possible with the current version.

**Comment by rodrigo-garcia-edo** [comment]
any news on this?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
