### ISSUE TITLE
failed posting event "upstreams" by "balancer"; no memory

### ISSUE THREAD

**Issue by qiuyuetao** [Kong/kong#7907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong-gateway2.4.0    kong-kong-ingress-controller 1.0.0

### Current Behavior

Yesterday, it was found that the upstream targets of the Kong gateway could not be updated. There are multiple back-end nodes, including those that have failed. Check the Kong log and find the following contents (see the picture)

### Expected Behavior

I want to handle the error reporting problem and ensure that the back-end service node is dynamically updated by the Kong      gateway

### Anything else?

![api-status](https://user-images.githubusercontent.com/32032648/135231601-29ed7a69-63b3-4ea2-b763-9404f4c87427.png)
![kong-gateway-error](https://user-images.githubusercontent.com/32032648/135231635-568f1569-516f-4db0-b5ec-0f4de8de7a82.png)

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Comment by qiuyuetao** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
