### ISSUE TITLE
GET for target_id returns 404 when weight is set to 0

### ISSUE THREAD

**Issue by locao** [Kong/kong#7920]
it works now with the default set to 0 !!!

The only thing to point out is that  a GET for http://adminapi:8001/upstreams/<upstream>/targets/<target_id> returns {"message":"Not found"} when weight is set to 0. Not sure if this is expected.

_Originally posted by @osnm91 in https://github.com/Kong/deck/issues/364#issuecomment-926743090_

**Comment by snehaa1989** [comment]
@locao I would like to work on this issue, what file needs to be changed? and what message should target_id return when weight is 0?

**Comment by bungle** [comment]
@locao, I could not reproduce this with latest `master`.

**Comment by bungle** [comment]
The `http://adminapi:8001/upstreams//targets/<target_id>` is wrong URI, right would be: `http://adminapi:8001/upstreams/<upstream_id>/targets/<target_id>`?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
