### ISSUE TITLE
rename plugin `schema.lua` file to `config.lua`

### ISSUE THREAD

**Issue by Tieske** [Kong/kong#804]
The current name is a technical one, I think it would be clearer to rename it to a functional one. Similar for the `dao.lua` file; `data.lua` would be more describing for its function.

I think this can be easily changed in a backward compatible manner, by first trying the new name, and on failure the old name.

**Comment by thibaultCha** [comment]
I am ok to rename it. However, people might think the actual configuration of a plugin comes from this file, but it is actually the "configuration's schema". hence, I am more in favor of something like `config-schema.lua`.

BTW, It has been on my mind for quite some time, and I think it is a step ahead: why forcing people to create X different files? What if each plugin only had to export **one** file, say, `main.lua`. This file is a table that returns the necessary properties, and those can be named and implemented more freely. Something like:

```lua
-- key-auth/main.lua
return {
  config_schema = require "whatever.path.I.want.my_schema",
  dao = require "whatever.path.I.want.dao", -- ideally, this disappears in the future as discussed
  handlers = require "whatever.path.I.want.handler"
  --- etc
}
```

**Comment by Tieske** [comment]
I see what you mean. But then everyone will do his own naming. I like that the current set of files forces a consistency across the plugins, because it makes it easy to understand (at least that's what I found going through them lately).

Though I don't understand the reasoning of the `handler` and `access` files, that should just be a single file.

**Comment by thibaultCha** [comment]
> Though I don't understand the reasoning of the handler and access files, that should just be a single file.

I have been advocating for this for a long time (I mentioned it in the development guide, but some plugins were implemented this way (`access.lua`, `log.lua` end co. called in `handler.lua`), but sadly nobody really cared about learning ngx_lua and most plugins were copied/pasted from one to another without anybody really caring and this is the result.

---

> it makes it easy to understand

Yes, consistency is also nice... I guess we could stick to this. What about `config_schema`, or something that does not suggest to a user that is is this file that will handle the plugin's configuration, simply the schema?

**Comment by Tieske** [comment]
the `dao` is bound to dissapear then, but the schema is still required no?

I'd propose the following then;

- `api.lua` (unchanged)
- `handler.lua` (unchanged)
- `data-schema.lua`  (currently `daos.lua`)
- `config-schema.lua` (currently `schema.lua`)

implemented as files, and implemented with fallbacks to the old names.

**Comment by thibaultCha** [comment]
> data-schema.lua (currently daos.lua)

The purpose of `daos.lua` is to return a table of DAOs (because a plugin might be handling multiple entities, like OAuth2). Since each DAO needs a schema, currently, all schemas are defined in daos.lua too. But once we have multiple databases, either we abstract the DAO creation, either we export the schemas. What I am worried about is the `data-` part. I feel it is too abstract. The purpose of this file is to implement any new entity type, and it must be clear it is different from `schema.lua` (see my next point)

> config-schema.lua (currently schema.lua)

This file holds the plugin's configuration. So, it must also be clear it is a different thing than the schemas defined in the other (`daos.lua`) file. This is for `plugins` rows, which each of them holds a particular configuration.

- I think `config-schema.lua` is fine as a name
- I am not convinced that `data-schema.lua` converys what we want. The idea is just that any entity can be defined in there (hence, `daos` for now). Maybe `custom-entities.lua`?

**Comment by thibaultcha** [comment]
Closing this as outdated for now.
