### ISSUE TITLE
How to transform multi-level body？

### ISSUE THREAD

**Issue by LincWong** [Kong/kong#8058]
i have body like this
```json
{
	"body": {
		"configId": "abc"
	}
}
```

i want to transform into this:
```
{
     "configId": "abc"
}
```

Can anyone tell me how to make it work??

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Comment by LincWong** [comment]
你好，我已经收到你的邮件了。
