### ISSUE TITLE
Set headers return empty string & not null

### ISSUE THREAD

**Issue by ramarahmanda** [Kong/kong#8059]
When set headers, it will always return headers key even if there's no value or key from request headers

```
Authorization:$((function()
    local value = headers.Authorization
    if not value then
      return
    end
  end)())
```

result : 
```
headers: {
  Authorization: ""
}
```

expected: 
```
headers: { }
```

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
