### ISSUE TITLE
How do I configure URI correctly

### ISSUE THREAD

**Issue by cunhazord** [Kong/kong#8060]
Hi, I have a route like /pinapple/color, and I configured the plugin URI to /api/color, when i go to kong/pineapple/color/12 the route always return /api/color only, without the /12 after the color. How do i configure that?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
