### ISSUE TITLE
Cannot fetch HMAC secret code

### ISSUE THREAD

**Issue by etoanik** [Kong/kong#8097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.6.0

### Current Behavior

My HMAC credential name is get from iPhone's identifierForVendor, e.g. 26DE073B-7835-48AD-917C-8E9F34E6A217

In case I try to get credential, but return {"message":"Not found"}
```
curl -X GET http://kong:8001/consumers/email}/hmac-auth/26DE073B-7835-48AD-917C-8E9F34E6A217
```

### Expected Behavior

Should return as bellow
```
{"secret":"xxxxxxxxxxxxxx","username":"26DE073B-7835-48AD-917C-8E9F34E6A217","consumer":{"id":"ac654f30-5a10-43ec-8196-xxxxxxxxxxxxxx"},"id":"e44cfbad-4b34-4c91-9177-xxxxxxxxxxxxxxxx","created_at":1637628953,"tags":null}
```

### Steps To Reproduce

```markdown
1. Add credential 

$ curl -i -X POST http://localhost:8001/consumers/{email}/hmac-auth \
      -d "username=26DE073B-7835-48AD-917C-8E9F34E6A217" \
      -d "secret=secret"
```

2. Get credential
```
curl -X GET http://kong:8001/consumers/email}/hmac-auth/26DE073B-7835-48AD-917C-8E9F34E6A217
```
```

**Comment by dndx** [comment]
@bungle @gszr What's your thought on this one? I think you folks encountered issues like this before, what was our solution at the end?

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
