### ISSUE TITLE
Accepting unpadded trace and span IDs in jaeger trace header values

### ISSUE THREAD

**Issue by henry-fraser** [Kong/kong#8119]
Hello

What are your thoughts on accepting unpadded trace, span and parent span ID components in `uber-trace-id` header values? 

We have run into an issue where the zipkin plugin rejects these values when trace and span IDs are "short", i.e. not left-padded with zeroes to the expected length in bytes. We configure a byte count of 8, but might receive an ID of low value truncated to 7 bytes (or fewer...). The zipkin plugin will warn about the mismatched length and regenerate IDs, thus we fail to propagate the trace correctly.

We have worked around the issue by fixing up such header values on the incoming request before the zipkin plugin performs validation.

If the following documentation is relevant, perhaps the zipkin plugin could be more forgiving of such input? It would of course be stricter about what values it propagated.

https://www.jaegertracing.io/docs/1.25/client-libraries/#value

For example, we must perform the following sort of correction to avoid the occasional "short" incoming value from being discarded by the zipkin plugin:

```
received: 111111111111:22222222:3333333333333333:0

fixed up: 0000111111111111:0000000022222222:3333333333333333:0

```

We'd be happy to support making this change if you thought it was a good idea.

Cheers
Henry

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
