### ISSUE TITLE
Span Tag with header "x-request-id"

### ISSUE THREAD

**Issue by carnei-ro** [Kong/kong#8123]
Hello guys, I'm using Kong as API Gw for North-South requests and Istio for East-West requests;
Istio (envoy) ships the "x-request-id" as a tag at the span (guid:x-request-id), it would be nice if Kong could do the same.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
