### ISSUE TITLE
Add option to return the traceId to the API user

### ISSUE THREAD

**Issue by r1ckr** [Kong/kong#8124]
Would be nice to be able to return the trace id back to the API user as an X-Request-Id or X-Correlation-Id header. The same way that the correlation id plugin does.

Something like:
```config.external_http_header_name=X-Request-Id```

If set, it would send back to the users the trace id in it.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
