### ISSUE TITLE
Feature Request: Rate sample option vs existing Probabilistic

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#8127]
https://www.jaegertracing.io/docs/1.12/sampling/#client-sampling-configuration

Zipkin plugin currently supports only probabilistic sampling, rate sample would be dope too:

> Rate Limiting (sampler.type=ratelimiting) sampler uses a leaky bucket rate limiter to ensure that traces are sampled with a certain constant rate. For example, when sampler.param=2.0 it will sample requests with the rate of 2 traces per second.

We may implement this in the future as well and PR to plugin as well if we get some time.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
