### ISSUE TITLE
What happens if Kong pod crashed before writing cache invalidation cluster event to DB ?

### ISSUE THREAD

**Issue by shettyh** [Kong/kong#8176]
### Discussed in https://github.com/Kong/kong/discussions/8132

<div type='discussions-op-text'>

<sup>Originally posted by **shettyh** December  1, 2021</sup>
How the cache is invalidated on other pods in this case ?

// @kikito </div>

**Comment by bungle** [comment]
On traditional mode it may lead to inconsistent state. That is, some nodes on cluster may not get invalidation and thus their caches are not cleared. On DBless or hybrid you won't see this issue as there the data planes are not connected to the database and they don't even receive any invalidation events. In future we will make dbless nodes and data plane nodes a bit more stateful because some use cases require it. In general kong pods should not be crashing and if that is frequent, then there is issue that needs to be fixed.

**Comment by bungle** [comment]
It would be great to have this transactional, so that no entity is changed without proper invalidation event written in database too.

**Comment by shettyh** [comment]
Thanks @bungle. Concern was that it is very difficult to figure out if there was a cache inconsistency when this rare edge case happens.

> It would be great to have this transactional, so that no entity is changed without proper invalidation event written in database too.

Yes this would be great
