### ISSUE TITLE
Grpc two-way flow, there will be disconnection every 60s

### ISSUE THREAD

**Issue by longxinH** [Kong/kong#8218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.0

#### Create command

```shell
curl -XPOST localhost:8002/services \
  --data name=CustomerService \
  --data protocol=grpc \
  --data host=docker.for.mac.host.internal \
  --data port=10065
```
```shell
curl -XPOST localhost:8002/services/CustomerService/routes \
  --data protocols=grpc \
  --data name=CustomerService \
  --data paths=/customer_service.CustomerService/
```

#### GW response log
![image](https://user-images.githubusercontent.com/12230340/146736445-766a97e8-93bd-43eb-b74e-943ad88f411d.png)

**Comment by hbagdi** [comment]
This is most likely due to the `read_timeout` and `write_timeout` properties on the Service object. Set them to a higher value as a workaround.

**Comment by longxinH** [comment]
I tried to create with the following command, but the problem still exists. The link is disconnected every 60s, not the set 120s
```shell
curl -XPOST localhost:8002/services \
  --data name=CustomerService \
  --data protocol=grpc \
  --data host=docker.for.mac.host.internal \
  --data port=10065 \
  --data write_timeout=120000 \
  --data read_timeout=120000 \
  --data connect_timeout=120000
```
I tried to use the nginx configuration ```KONG_NGINX_HTTP_CLIENT_BODY_TIMEOUT: 86400```, the problem was solved, but this configuration belongs to the global configuration and will affect all services

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
