### ISSUE TITLE
 High Latency P99  in 2.6.0

### ISSUE THREAD

**Issue by chensunny** [Kong/kong#8463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.0

### Current Behavior

P99 is rising from 600ms to 4s Where I upgrade Kong from 2.2.2 to 2.6.0

### Expected Behavior

Latency Should not increase

### Steps To Reproduce

```markdown
* upgrade Kong from 2.2.2 to 2.6.0
* service 75
* router 150
```

### Anything else?

none

**Comment by chensunny** [comment]
![image](https://user-images.githubusercontent.com/6245343/155696833-b9333675-7c9a-4b72-9d72-c572f1caefc4.png)

**Comment by chensunny** [comment]
when I change to `2.5.1`, It becomes normal

![image](https://user-images.githubusercontent.com/6245343/155697071-db199b04-1421-4d5e-bc1a-262b52ddb540.png)

**Comment by bungle** [comment]
@chensunny, can you also try `2.7.1`? We are about to release `2.8.0` soon, but this bug is puzzling me.

**Comment by mayocream** [comment]
friendly ping @chensunny to see if we have any updates :)

**Comment by soulseen** [comment]
@chensunny Have you solved the issue? I had the same problem, and the Kong version is 2.6.0 too. cc: @bungle @mayocream

**Comment by dingjiayi** [comment]
@soulseen In our case, it's caused by the `metric_data` function in the prometheus plugin, especially in this line
https://github.com/Kong/kong/blob/96c5328d3393777f2d752d10e2940021e5840da7/kong/plugins/prometheus/prometheus.lua#L818
Base on my local test data, this problem has been improved in #9028.

There are two main changes implemented to reduce long tail latency:

1. Reduction of calls to the `fix_histogram_bucket_labels` function
2. Yielding CPU time slices: call `yield()`
CC @chensunny  @fffonion
