### ISSUE TITLE
RabbitMQ protocol translation support

### ISSUE THREAD

**Issue by sonicaghi** [Kong/kong#866]
requested two times in the last few months

**Comment by ahmadnassri** [comment]
without more details, this does not sound meaningful, neither a fit for an HTTP API Gateway ... typically AMQP requires a Messaging Queue service, something Kong is not architected to provide.

**Comment by wstam88** [comment]
"Pushpin is the open source reverse proxy for the realtime web. One of the benefits of Pushpin functioning as a proxy is that it can be combined with an API management system, such as Mashape’s Kong. Kong is the open source management layer for APIs. To use Kong with Pushpin, simply chain the two together on the same network path."

 [source](http://blog.fanout.io/2015/07/14/realtime-api-management-pushpin-kong/)

**Comment by gsdenys** [comment]
I'm Working on It, the code is stored at [git repository](https://github.com/gsdenys/kong-plugin-amqp). Unfortunately, to provide the AMQP support natively like we need to change a kong internal package `kong.constants` and insert the line `amqp = "http"` to the constants.

I know it is not the better way, because that, I am inclined to change the direction from plugin to kong code and make a pull request. As I don't know if kong want to have AMQP as accepted protocol i'm afraid to lose my time.
