### ISSUE TITLE
Kong 2.7.1 Admin API Plugin PUT Validation is wrong per docs + functionality. 

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#8664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.1

### Current Behavior

Changing from one type of auth(jwt) to another (oauth2) via the admin API using same plugin id does not behave per docs:

https://docs.konghq.com/gateway/2.8.x/admin-api/#create-or-update-plugin-associated-to-a-specific-route

![image](https://user-images.githubusercontent.com/31913027/162689886-6d4eff0d-4dd6-4693-8d67-162d40552154.png)

Admin API Call:

PUT:
https://gateway-url.company.com/admin-api-proxy-path/routes/" + route_id + "/plugins/" + plugin_id

{
  "config": {
    "mandatory_scope": false,
    "accept_http_if_already_terminated": false,
    "hide_credentials": false,
    "enable_implicit_grant": false,
    "global_credentials": true,
    "enable_client_credentials": true,
    "enable_password_grant": false,
    "enable_authorization_code": false,
    "token_expiration": 3600,
    "auth_header_name": "authorization"
  },
  "name": "oauth2"
}

Admin API Response:
HTTP Status 400
invalid primary key: '{id="expected a valid UUID"}'
^^^ Refers to the plugins ID not present in the PUT body I assume.

NOTE: The API call DOES still work, my proxy does get updated with the plugin changes I PUT going from jwt to oauth2 authentication. 

### Expected Behavior

Status 200 response for successful update, no JSON errors thrown.

When the plugin ID is present in the URI the HTTP Body validation should not be throwing that 400 level error.

AGAIN NOTE: The API call DOES still work, my proxy does get updated with the plugin changes I PUT from jwt to oauth2. The error message/validation is whats wrong.

### Steps To Reproduce

```markdown
1. Create a proxy with route, assign the JWT plugin to with with the jwt plugins ID saved down.

2. PUT OAuth2.0 plugin with the above body all the way out to the routes + plugin id of the JWT plugin to turn it into a OAuth2.0 protected proxy rather than JWT.

Watch it work via the admin API in terms of underlying resources but throw you a 400 error with a JSON body error.
```

### Anything else?

/ $ kong version --vv
2022/04/11 07:47:51 [verbose] Kong: 2.7.1
2022/04/11 07:47:51 [debug] ngx_lua: 10020
2022/04/11 07:47:51 [debug] nginx: 1019009
2022/04/11 07:47:51 [debug] Lua: LuaJIT 2.1.0-beta3
2.7.1

This is likely a remaining issue for newer iterations of Kong too. And likely applies to all plugin PUT approaches leveraging the same plugin ID to config totally different plugins on the same ID.

**Comment by agattone** [comment]
Hello,
I noted a similar problem using Create Or Update Plugin Associated to a specific route.

Request used is:  PUT /routes/{route name or id}/plugins/{plugin id}

From https://docs.konghq.com/gateway/2.7.x/admin-api/#update-or-create-plugin
It is specified after the body description:

`Inserts (or replaces) the Plugin under the requested resource with the definition specified in the body. The Plugin will be identified via the name or id attribute.
When the name or id attribute has the structure of a UUID, the Plugin being inserted/replaced will be identified by its id. Otherwise it will be identified by its name.
When creating a new Plugin without specifying id (neither in the URL nor in the body), then it will be auto-generated.
Notice that specifying a name in the URL and a different one in the request body is not allowed.`

My understanding could be wrong but I tried to use this method providing the plugin name as a string instead of providing the plugin id as UUID.

Indeed, at creation time, I don't have this id which is automatically generated.
In same way, Plugin request body has no id.
Plugin name is also present in the body and it is the same as the path parameter.

If the plugin already exists, an update is expected, otherwise a create is expected.

I got the following response:
Status = 400
Response body:
`{
  "code": 1,
  "fields": {
    "id": "expected a valid UUID"
  },
  "name": "invalid primary key",
 "message": "invalid primary key: '{id="expected a valid UUID"}'"
}`

Is my understanding regarding the expected behavior is incorrect?
Is there another method to do this job?

Plugin name support in this case (Create Or Update) is more user friendly.
