### ISSUE TITLE
high memory used

### ISSUE THREAD

**Issue by bruse-peng** [Kong/kong#8910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

kong:2.0.2-centos

### Current Behavior

high memory userd

### Expected Behavior

high memory userd

### Steps To Reproduce

```markdown
pod of kong high memory used, how to decrease memory
```

### Anything else?

![image](https://user-images.githubusercontent.com/47881861/172293529-212e072f-1b82-41f1-94a9-4ebdb1095cee.png)

**Comment by jschmid1** [comment]
Hi @bruse-peng 

Thanks for the report. In order to help you, we may need additional information such as

* Deployment mode (hybrid, traditional, db-less)
* How many kong nodes are you running?
* How does your request pattern look like? (RPS in particular)

Also, I'm seeing that you have RAM to spare. Could you elaborate why the memory usage you're seeing is problematic in this case and maybe what you're expecting in this case?

TIA
