### ISSUE TITLE
*-log - 4xx response from Kong are not logged

### ISSUE THREAD

**Issue by ahmadnassri** [Kong/kong#892]
when Kong responds in a `4xx` _(e.g. `401`, `403`)_ the logging plugins (all `*-log` and Galileo) are not logging those requests.

this might affect runscope as well.

**Comment by thefosk** [comment]
I think this happens when a plugin terminates the request, but not when the usptream service returns a `4**` response.

**Comment by thibaultCha** [comment]
Yes, logging plugins have always been intended to log *successful* requests.

See #490 and https://groups.google.com/forum/#!topic/konglayer/Dx45HAHdf8k for why.

**Comment by nijikokun** [comment]
Perhaps it should be configurable based on the client's needs. Such as per *method*, *status code*, *path*, and *headers*.

Not sure whether we want to get into filtering out certain strings and data that is being passed but I know for a fact that certain logging utilities (raygun) already provide such a service in their agents and libraries.

**Comment by ahmadnassri** [comment]
> See #490 and https://groups.google.com/forum/#!topic/konglayer/Dx45HAHdf8k for why.

we'll have to come up with a possible solution for logging errors in this scenario, a production system would be lacking if those types of errors are not captured in logs.

**Comment by ryanwilsonperkin** [comment]
Hey all, I'd love to weigh in on this since it's a feature we'd be interested in taking advantage of. We're hoping to use the rate-limiting plugin and use Galileo for visualizing of how many requests are being rate limited, and especially being able to break those down by header or path. We'd also love to visualize this for other plugins, such as how many requests are being rejected for authentication reasons.

If there's any other information we can provide, feel free to ask. @ahmadnassri thanks for filing this issue.

**Comment by nicklanng** [comment]
Hi, I've just been working on a PoC of Kong and run into this very issue - has there been any more work done in this area? Thanks.

**Comment by BrianHutchison** [comment]
+1 for letting us control how Kong logs in potential DDOS scenarios.

We would like to enable alerting in our production environment if we are denying requests (past some threshold) based on reaching a rate limit.

@ahmadnassri Have you come up with a work-around?

**Comment by Tieske** [comment]
Code wise it happens when a plugin (or any other piece of Kong) exits prematurely like @thefosk mentioned. To catch those we could try and wrap those ngx functions/methods and catch the errors in between.

To prevent any dos problems we could set a limit of how many of a particular error type are logged per second. Eg. max 10 per second. So if more than 10 errors of 4xx are generated, it will stop logging those and only report the total count once per second until the rate goes below the 10 per second again.

**Comment by codebien** [comment]
For our service this feature is a must-have, so we are discussing internal on a workaround. It could be ok for us to support the cost for developing a basic implementation of this feature and pull request it.

IMO, to develop this feature in the minimum possible time, the rate limit issue shouldn't be taken into account.
It could be handled outside the plugin and Kong for now. Then, in future and advanced versions, one or more rate limit techniques could be added.

We are thinking of 2 possibilities:
 - @thibaultCha says that the current plugin is for logging _proxied_ requests, so we could implement a log plugin for _not proxied_ requests. @mashape-team Are proxied requests identifiable from within the plugin scope?

 - A more complex but much more powerful solution would be to implement a per request access logger with a global vision directly in kong core.
This would allow to achieve 2 goals:
 1- Catching all requests, includnig requests that do not match any API (404 generated by kong), while still keeping per-request logs.
 2- Loggins calls to the Admin API the same way gateway would do.

This is my simple idea to implement it:
 
For each request, a new Logger Record instance is generated. The information available at Kong core is added (The arrived request, the returned response, etc.). In addition, the Logger instance is injected within each plugin, so that they can log additional information available only within the plugin's scope.

@all What do you think, guys?

Thanks!

**Comment by ewilde** [comment]
Just to mention this issue affects the **runscope** plugin as well. 

It's a shame. It would be very useful for us to help diagnose customer authentication issues if 401's were being forwarded on. At the moment we only see 200s in the runscope traffic monitor sent by the plugin.

**Comment by Krieke** [comment]
+1

**Comment by robotnic** [comment]
+1

**Comment by thibaultcha** [comment]
Closing this now that Kong 0.12.0 has been released and logs such errors when returned by plugins!
