### ISSUE TITLE
proposal: rename "api" to "route"

### ISSUE THREAD

**Issue by ahmadnassri** [Kong/kong#893]
- adding an "API" is not a clear description of the actual behaviour it produces, its better described as adding a "route"
- users may or many not be actually routing to "APIs", different term clashes here (API, vs Microservice, vs Service, etc ...)
- ability to support Websockets (https://github.com/Mashape/kong/issues/218) and Forward Proxying (https://github.com/Mashape/kong/issues/214) in the future would also clash with the "API" terminology

there seems be a good argument for renaming to "route", any argument against?

**Comment by sinzone** [comment]
could be just "service"

**Comment by ahmadnassri** [comment]
> could be just "service"

that would also work, but "route" is the most descriptive of its actual role.

**Comment by thibaultCha** [comment]
Originally proposed this so I agree.

- "Route" is confusing when you have request_path and request_host (especially multiple request_paths for a given "API", since those are your actual routes.

- "Services" is more abstract but confusing in the context of a forward proxy setup where your upstream is literally anything.

**Comment by sinzone** [comment]
then, maybe we don't want to do everything. we stay focused on APIs. we're API mgmt. after all.

**Comment by thefosk** [comment]
I think `route` is confusing and could be interpreted as "endpoint".

**Comment by ahmadnassri** [comment]
other naming from nginx's usage: `server`, `location`

I kinda like `location` as a substitution to `route` with same meaning.

**Comment by nijikokun** [comment]
I'm in favor of `upstream` or `api`.

`upstream` because that's what it is.

`api` because it's short and already exists, no change required.

**Comment by nikz** [comment]
I vote for `route`. Could we alias it for a while until people have time to adjust?

**Comment by thefosk** [comment]
This proposal was made because it was inserted in a wider context of changing how the resolver works. We should discuss that idea first, and then the implementation details.

On a side note Kong is a gateway for APIs and microservices, and people add APIs and services to it - adding routes would change that perspective, so this is not just a renaming issue.

**Comment by andyfleming** [comment]
I would vote for `route`. It doesn't bother me that it could just be a different host (as opposed to path). I think `route` still makes sense.

The terms `api` and `service` seem to be more synonymous with `upstream` in my mind.

**Comment by samgaw** [comment]
If `route` is considered as implying an endpoint, what about `resource`? A resource can be many routes/endpoints/hosts and it's broad enough to cover _hopefully future_ support for internal & external APIs.

**Comment by iam-merlin** [comment]
`route` is good :) . Why not rename `plugins` to `middlewares` too?

For a js developper... the reference will be crystal-clear.

**Comment by thibaultcha** [comment]
Routes now exist since 0.13.0 - some reading: https://konghq.com/blog/kong-ce-0-13-0-released/

Closing this now!
