### ISSUE TITLE
Field that logs request sizes may be inaccurate?

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong#9285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.7.1 AND 2.8.1 (We are unsure how far back it goes that this field has been inaccurate but we certainly see it in older and newer runtimes we are currently on)

### Current Behavior

Seems the field that logs request sizes may be inaccurate?

In Kong/Nginx the field ngx.var.request_length helps give the size of request headers + body as long as the body is not too big and temp written to disk. It seems for us at least to our knowledge 2.7.x and 2.8.x Kong this field is reportedly not capturing the request body size accurately for me just doing typical application/json payload testing here recently.

We use this field in our own plugin https://github.com/Optum/kong-splunk-log/blob/master/src/basic.lua#L80 and its always worked fine in the past, until now applying more scrutiny it seems like its capturing the bytes of the request headers but all together losing the request body size being included in the bytes count. Can anyone from Kong do some of their own testings around this field with runtime Kong instances? This field gets used in all your logging plugins too so using our plugin specifically is not necessary.

Worth noting I just checked right now on Response sizing derived from: ngx.var.bytes_sent , this field still is being set and working as expected so I think I just caught a bug that has fallen through the cracks during some Kong release cycle, not sure how far back it goes.

Ent. portal case number as well but since this impacts OSS I figured I would go through this channel too since its not really enterprise specific maybe Kong can clarify what the best approach is for bugs like this for things that effect OSS codebase but your still an Enterprise customer for getting eyes on bugs:
00029757

### Expected Behavior

When I send a 9kb+ etc. application/json payload size I should see that reflected in the request size bytes. Seems right now the field has started to only log header bytes seen for us...

### Steps To Reproduce

```markdown
1. Send the payload as described in the expected behavior.
```

**Comment by samugi** [comment]
Hello @jeremyjpj0916, thank you for reporting this.
I tested the `kong-splunk-log` plugin on 2.8.1.0 and 2.8.1.4 but I wasn't able to reproduce the behaviour described.

I sent a 1M file in the request body and the plugin reported: `RequestSize: '1048793',`, and a 5M body reported: `RequestSize: '5243097'`.

I tested this with Kong running in Docker with a configuration similar to the one [from our docs](https://docs.konghq.com/gateway/2.8.x/install-and-run/docker/) with no additional plugins or configurations. Could you confirm you get the same result in these conditions?

**Comment by jeremyjpj0916** [comment]
@samugi Could you touch base internally on this case?

<img width="660" alt="image" src="https://user-images.githubusercontent.com/31913027/186800537-317dfd92-7087-4415-97be-a69a6e5335fc.png">

Although I am surprised on company stance to not attempt to fix this if at the OpenResty layer if its OpenResty and not Nginx itself. And I would think base nginx variable would work, I Imagine they have unit tests around this field in their direct webserver impl(not the lua bridge probs) so I bet its an OpenResty or Kong addition thats causing the discrepancy.

**Comment by samugi** [comment]
Hi @jeremyjpj0916, I reached out to Support internally and we could confirm the variable `request_length` contains the expected values that always reflected the size of the request body during our tests (it appears that the apparent failures initially detected could have been false positives).
 
I'd recommend continuing the conversation with Support as there isn't evidence of an issue affecting the product at the moment. Support can proceed with the investigation of your environment to determine the root cause of this behaviour.

**Comment by jeremyjpj0916** [comment]
@samugi I figured it out... So if you call a path on Kong that does not explicitly exist and get a 404 back... Thats when the request body size gets dropped.

If I call a proxy path that does exist, it logs the request size accurately.

Same body, 2 diff logs:

```
{ 
   BackendLatency: -1
   ClientIP: XXXXX
   GatewayHost: XXXXX
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 404
   KongLatency: 0
   RequestSize: 343
   ResponseSize: 282
   RoutingURL:
   StartedAt: 1661551688414
   TotalLatency: 65
   URI: /echo/post/test/3
}
```

```
{  
   BackendLatency: -1
   ClientIP: XXXXX
   GatewayHost: XXXXXXX
   GatewayPort: 443
   HTTPMethod: POST
   HTTPStatus: 200
   KongLatency: 4
   RequestSize: 29528
   ResponseSize: 382
   RoutingURL: localhost:8001/status/test
   ServiceName: F5MonitorService
   StartedAt: 1661551423734
   TotalLatency: 4
   ]
   URI: /F5/status/test
}
```

**Comment by samugi** [comment]
Hi @jeremyjpj0916, I see what you mean; this is happening because `$request_length` is [calculated by Nginx](https://github.com/nginx/nginx/blob/adbd28b7a9843ebce895f9903f19c5a740d61db4/src/http/ngx_http_request_body.c#L378) when the body is parsed, right before the request is proxied to the upstream API. This, for performance reasons, is done after the routing took place, and that is why `$request_length` only contains the size of the request line & headers, should the flow exit without proxying the request (for example, when a 404 is returned).

In other words, in the event of a 404 (due to missing route), the _request length_ does not include the body because Nginx did not need to read the body in order to return a response, and the only parts of the request that were handled are in fact the request line and headers, which produced the 404 response.

To get the body size without parsing the body, you could use `ngx.var.content_length` which provides the value of the Content-Length header regardless of whether the request was proxied to an upstream or not. Would this variable suit your use case?

**Comment by d19dotca** [comment]
@jeremyjpj0916 - Just wanted to say that we plan to generate a KB article in the near future to better explain this specific behaviour since it may come up again as a question of why the request_size appears to be inaccurate in some circumstances. As @samugi has mentioned, there's no product issue at this time and the discrepancies seen earlier appear to be explained by the situation where 404 responses are generated by Nginx.

Side note: Can I kindly ask you to replace that screenshot you provided earlier from a Support correspondence with just the text of the response instead? In my opinion, that screenshot is exposing what I'd consider to be private information such as email addresses (mine in this case) along with full names. In the future if needing to convey a support message, you'd be better off to simply mention the support case number and the general body of text from the correspondence with identifiable information removed. Thank you for your understanding.
