### ISSUE TITLE
Clarification about PDK & Kong version compatibility

### ISSUE THREAD

**Issue by JuanMorenoDeveloper** [Kong/kong#9328]
### Where is the problem?

https://docs.konghq.com/gateway/latest/pdk/, generated from https://github.com/Kong/kong/blob/6ce364af0a45120a08b836a0abfd53c69d9a8795/kong/pdk/init.lua#L5-L6

### What happened?

The paragraph says: 

> The PDK is guaranteed to be forward-compatible from its 1.0.0 release and onward.

But the current PDK (JS, Python) readme pages said: 

https://github.com/Kong/kong-js-pdk/blob/master/README.md

https://github.com/Kong/kong-python-pdk/blob/master/README.md

> Requires Kong >= 2.3.0. 

So the compatibility statement (1.0.0) is still valid?

### What did you expect to happen?

Get clarification about PDK & Kong version compatibility.

Related to: https://github.com/Kong/docs.konghq.com/issues/4332

**Comment by samugi** [comment]
Hello @JuanMorenoDeveloper, the statement from our docs "_forward-compatible from its 1.0.0 release_" refers to version 1.0.0 **of the PDK**. The plugin servers for Python and JavaScript that you linked refer to the **Kong version** that is required to use them, in order to interface with the PDK. Forward compatibility applies to the PDK, making it compatible with future versions of itself.

**Comment by JuanMorenoDeveloper** [comment]
Got it, so this statement only applies to Lua's PDK version right? 
I think it should point out that, thus because Python (v0.31) and JS (v0.5.3) PDK have different versions.

**Comment by samugi** [comment]
@JuanMorenoDeveloper correct. Versions are different, because each PDK exists separately with its own versioning.  However, the Go, JavaScript and Python PDKs use the _proxy pattern_ to access the [PDK](https://docs.konghq.com/gateway/latest/pdk/) in Kong via rpc. This is the reason why the forward-compatibility statement with regards to the Lua PDK still applies, even when using the plugin servers for developing plugins in other languages. 
I hope that helps answering your doubts.

**Comment by JuanMorenoDeveloper** [comment]
That's make totally sense. What do you thing about add that clarification here?

**Comment by samugi** [comment]
@JuanMorenoDeveloper I believe the statement [in our documentation](https://docs.konghq.com/gateway/latest/pdk/) is clear enough as it is, but I am really glad I could help clarifying your doubts.
