### ISSUE TITLE
kong(work in docker) can't log in /usr/local/kong/logs/error.log

### ISSUE THREAD

**Issue by Canon4G** [Kong/kong#9338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 2.8.1.2-alpine

### Current Behavior

my plugin code:
   function DemoHandler:access(conf)
      DemoHandler.super.access(self)
      kong.log("hello", "word")
   end

when i access just can read  ' 2022/08/30 03:09:44 [notice] 2090#0: *27 [kong] handler.lua:166 [demo] helloworld, client: 172.18.0.1, server: kong, request: "POST /docker/test HTTP/1.1", host: "127.0.0.1:8000" ' in docker logs like this 
![image](https://user-images.githubusercontent.com/45388559/187340458-6fb7ce67-6865-4c65-956e-657de72bf3f3.png)

but i cant't in container /usr/local/kong/logs/error.log to read my log
this error.log is empty

this is my kong.conf
![image](https://user-images.githubusercontent.com/45388559/187340602-ad59dfad-f21f-4996-9012-1b4e42d49d82.png)

**Comment by samugi** [comment]
Hello @Canon4G,
your logs are outputed in the file `logs/error.log` correctly, however, by default the file `error.log` points to `/dev/stderr`, so anything that is printed there is automatically redirected to standard error:
```
bash-5.1$ ls -l /usr/local/kong/logs/error.log 
lrwxrwxrwx    1 kong     nogroup         11 Aug 30 09:06 /usr/local/kong/logs/error.log -> /dev/stderr
```
and this is why you are currently able to see the log output in `docker logs`.

It is possible to configure a different file as the target for the `proxy` and `admin` error logs via the configuration parameters [proxy_error_log](https://docs.konghq.com/gateway/latest/reference/configuration/#proxy_error_log) and [admin_error_log](https://docs.konghq.com/gateway/latest/reference/configuration/#proxy_error_log) as in the following example:
`proxy_error_log=logs/myerror.log`
However this is not recommended because the container may easily fill the available storage and this can result in failures and downtime on the gateway.

**Comment by Canon4G** [comment]
> 

thanks
