### ISSUE TITLE
unhealthy status of upstream servers are not updated on all kong

### ISSUE THREAD

**Issue by raza1993** [Kong/kong#9588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

2.6.0

### Current Behavior

unhealthy status of upstream servers are not getting updated on all kong nodes in a cluster which leads kong to send traffic to upstream hosts that are not healthy at all. we have set unhealthy timeout to 5 but even after 10-15  mins traffic  continues to go on unhealthy servers.

### Expected Behavior

traffic to host which is unhealthy should not be sent via kong and should be marked unhealthy within specified time in unhealthy timeout.

### Steps To Reproduce

```markdown
setup kong cluster
and onboard service and respective routes and upstream servers
on one of the upstream server stop the service
monitor the time/number of hits that are still sent to unhealthy hosts.
```

**Comment by flrgh** [comment]
Hi @raza1993 :wave: 

Of note, upstream target status is [not propagated between Kong hosts](https://docs.konghq.com/gateway/2.6.x/reference/health-checks-circuit-breakers/#targets):
> The objective of the health checks functionality is to dynamically mark targets as healthy or unhealthy, for a given Kong node. There is no cluster-wide synchronization of health information: each Kong node determines the health of its targets separately. This is desirable since at a given point one Kong node may be able to connect to a target successfully while another node is failing to reach it: the first node will consider it healthy, while the second will mark it as unhealthy and start routing traffic to other targets of the upstream.

So, _some_ of what you're observing here is expected behavior for Kong.

If an upstream is configured with health checks, each Kong node in your cluster _should_ be able to individually detect an unhealthy target and exclude it from load balancing. The semantics of this will vary greatly depending on how the health checks are configured, and due to their complexity, it can be tricky to get them working exactly as required for a given environment.

If you can share a complete example of your service+upstream entities as well as any more details about your network/system architecture, this will help with debugging efforts.
